# Generated by Django 5.1.15 on 2026-01-13 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0006_client_stripe_customer_id'),
        ('organizations', '0004_gym_facebook_gym_instagram_gym_tiktok_gym_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Día 1', max_length=50, verbose_name='Nombre Día')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Día de Rutina',
                'verbose_name_plural': 'Días de Rutina',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción/Técnica')),
                ('muscle_group', models.CharField(choices=[('CHEST', 'Pecho'), ('BACK', 'Espalda'), ('LEGS', 'Piernas'), ('ARMS', 'Brazos'), ('SHOULDERS', 'Hombros'), ('CORE', 'Core'), ('CARDIO', 'Cardio'), ('FULL_BODY', 'Cuerpo Completo')], default='FULL_BODY', max_length=20, verbose_name='Grupo Muscular')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo', verbose_name='Video URL')),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('sets', models.CharField(blank=True, help_text="Ej: 3, 4, o '3-4'", max_length=50, verbose_name='Series')),
                ('reps', models.CharField(blank=True, help_text="Ej: 8-12, 10, 'Fallo'", max_length=50, verbose_name='Repeticiones')),
                ('rest', models.CharField(blank=True, help_text='Ej: 60s, 2m', max_length=50, verbose_name='Descanso')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='routines.routineday')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.exercise')),
            ],
            options={
                'verbose_name': 'Ejercicio de Rutina',
                'verbose_name_plural': 'Ejercicios de Rutina',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Rutina')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('goal', models.CharField(choices=[('STRENGTH', 'Fuerza'), ('HYPERTROPHY', 'Hipertrofia'), ('ENDURANCE', 'Resistencia'), ('WEIGHT_LOSS', 'Pérdida Peso'), ('GENERAL', 'General')], default='GENERAL', max_length=20, verbose_name='Objetivo')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Principiante'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzado')], default='BEGINNER', max_length=20, verbose_name='Nivel')),
                ('is_template', models.BooleanField(default=True, help_text='Si es True, puede asignarse a múltiples clientes.', verbose_name='Es Plantilla')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
            },
        ),
        migrations.AddField(
            model_name='routineday',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='routines.workoutroutine'),
        ),
        migrations.CreateModel(
            name='ClientRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='clients.client')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.workoutroutine')),
            ],
            options={
                'verbose_name': 'Asignación de Rutina',
                'verbose_name_plural': 'Asignaciones de Rutina',
            },
        ),
    ]
