# Generated by Django 4.2.27 on 2026-01-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_franchise_owners'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_tags', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Etiqueta de Ejercicio',
                'verbose_name_plural': 'Etiquetas de Ejercicio',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='routines.exercisetag'),
        ),
    ]
