# Generated by Django 4.2.27 on 2026-01-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0103_client_other_document_type'),
        ('routines', '0002_exercisetag_exercise_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Hora Inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duración (min)')),
                ('difficulty_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-10', null=True, verbose_name='Dificultad percibida')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('total_sets', models.PositiveIntegerField(default=0)),
                ('total_reps', models.PositiveIntegerField(default=0)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Volumen total (kg)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to='clients.client')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routines.workoutroutine')),
                ('routine_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routines.routineday')),
            ],
            options={
                'verbose_name': 'Registro de Entrenamiento',
                'verbose_name_plural': 'Registros de Entrenamiento',
                'ordering': ['-date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_completed', models.PositiveSmallIntegerField(default=0, verbose_name='Series completadas')),
                ('sets_data', models.JSONField(blank=True, default=list, verbose_name='Datos de series')),
                ('total_reps', models.PositiveIntegerField(default=0, verbose_name='Total repeticiones')),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Volumen (kg)')),
                ('max_weight', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Peso máximo (kg)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.exercise')),
                ('routine_exercise', models.ForeignKey(blank=True, help_text='Referencia al ejercicio de la rutina (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='routines.routineexercise')),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='routines.workoutlog')),
            ],
            options={
                'verbose_name': 'Registro de Ejercicio',
                'verbose_name_plural': 'Registros de Ejercicios',
                'ordering': ['id'],
            },
        ),
    ]
