# Generated by Django 5.1.15 on 2026-01-11 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_gym_brand_color'),
        ('staff', '0005_alter_workshift_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='activity_icons/')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_categories', to='organizations.gym')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='activities.activitycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Actividad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Duración (min)')),
                ('base_capacity', models.PositiveIntegerField(help_text='El aforo final dependerá de la sala', verbose_name='Aforo Base')),
                ('intensity_level', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='MEDIUM', max_length=20, verbose_name='Intensidad')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('eligible_staff', models.ManyToManyField(blank=True, related_name='qualified_activities', to='staff.staffprofile')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='organizations.gym')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.activitycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Sala')),
                ('capacity', models.PositiveIntegerField(verbose_name='Aforo Máximo')),
                ('layout_configuration', models.JSONField(blank=True, default=dict, verbose_name='Configuración de Diseño')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='organizations.gym')),
            ],
        ),
    ]
