# Generated by Django 5.1.15 on 2026-01-11 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('organizations', '0002_gym_brand_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Política')),
                ('window_hours', models.PositiveIntegerField(help_text='Horas antes de la clase para cancelar sin penalización', verbose_name='Ventana de Cancelación (Horas)')),
                ('penalty_type', models.CharField(choices=[('STRIKE', 'Strike (Falta)'), ('FEE', 'Cobro Monetario'), ('FORFEIT', 'Pérdida de Crédito')], default='FORFEIT', max_length=20, verbose_name='Tipo de Penalización')),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Solo si el tipo es Cobro Monetario', max_digits=6, null=True, verbose_name='Monto de Multa')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='organizations.gym')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='cancellation_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.cancellationpolicy'),
        ),
    ]
