# Generated by Django 5.1.15 on 2026-01-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_cancellationpolicy_activity_cancellation_policy'),
        ('clients', '0005_clientsale_staff_clientvisit_staff'),
        ('organizations', '0002_gym_brand_color'),
        ('staff', '0005_alter_workshift_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('start_time', models.TimeField(verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Fin')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Vigente desde')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='activities.activity')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_rules', to='organizations.gym')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.room')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fin')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada')], default='SCHEDULED', max_length=20)),
                ('max_capacity', models.PositiveIntegerField(default=0, verbose_name='Aforo Máximo')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='activities.activity')),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_sessions', to='clients.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='organizations.gym')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.room')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_sessions', to='activities.schedulerule')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
