# Generated by Django 5.1.15 on 2026-01-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_schedulerule_activitysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Código HEX (ej: #3B82F6)', max_length=7, verbose_name='Color en Calendario'),
        ),
    ]
