# Generated by Django 4.2.27 on 2026-01-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_stripe_customer_id'),
        ('organizations', '0005_franchise_owners'),
        ('activities', '0004_activity_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Política')),
                ('booking_window_mode', models.CharField(choices=[('RELATIVE_START', 'Horas antes del inicio'), ('FIXED_TIME', 'Días antes (hora fija)')], default='RELATIVE_START', max_length=20, verbose_name='Modo de Apertura')),
                ('booking_window_value', models.PositiveIntegerField(default=48, help_text='Horas (si es relativo) o Días (si es fijo)', verbose_name='Valor Antelación')),
                ('booking_time_release', models.TimeField(blank=True, help_text='Solo si el modo es Hora Fija (ej: 00:00)', null=True, verbose_name='Hora de Apertura')),
                ('cancellation_window_hours', models.PositiveIntegerField(help_text='Horas antes de la clase para cancelar sin penalización', verbose_name='Ventana de Cancelación (Horas)')),
                ('penalty_type', models.CharField(choices=[('STRIKE', 'Strike (Falta)'), ('FEE', 'Cobro Monetario'), ('FORFEIT', 'Pérdida de Crédito')], default='FORFEIT', max_length=20, verbose_name='Tipo de Penalización')),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Solo si el tipo es Cobro Monetario', max_digits=6, null=True, verbose_name='Monto de Multa')),
                ('waitlist_enabled', models.BooleanField(default=True, verbose_name='Lista de Espera Activa')),
                ('waitlist_mode', models.CharField(choices=[('AUTO_PROMOTE', 'Auto-Promoción (Automático)'), ('BROADCAST', 'Broadcast (Primero en llegar)')], default='AUTO_PROMOTE', max_length=20, verbose_name='Modo de Lista')),
                ('waitlist_limit', models.PositiveIntegerField(default=0, help_text='0 = Sin límite', verbose_name='Límite Lista Espera')),
                ('auto_promote_cutoff_hours', models.PositiveIntegerField(default=1, help_text='Horas antes donde la lista deja de correr sola', verbose_name='Cierre Auto-Promoción (Horas)')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_policies', to='organizations.gym')),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('WAITING', 'En espera'), ('PROMOTED', 'Promovido (Dentro)'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado')], default='WAITING', max_length=20)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='clients.client')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='activities.activitysession')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('session', 'client')},
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='cancellation_policy',
        ),
        migrations.DeleteModel(
            name='CancellationPolicy',
        ),
        migrations.AddField(
            model_name='activity',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.activitypolicy'),
        ),
    ]
