# Generated by Django 4.2.27 on 2026-01-18 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_clientvisit_cancellation_type'),
        ('staff', '0006_auditlog'),
        ('organizations', '0009_gymgoal'),
        ('activities', '0005_activitypolicy_waitlistentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Activar sistema de valoraciones')),
                ('delay_hours', models.PositiveIntegerField(default=3, help_text='Horas después de clase para solicitar review')),
                ('request_mode', models.CharField(choices=[('ALL', 'Solicitar a todos los asistentes'), ('RANDOM', 'Solicitud aleatoria')], default='RANDOM', max_length=20)),
                ('random_probability', models.PositiveIntegerField(default=30, help_text='Probabilidad % de solicitar review (solo si modo aleatorio)')),
                ('points_per_review', models.PositiveIntegerField(default=10, help_text='Puntos de fidelidad por dejar review')),
                ('reviews_public', models.BooleanField(default=False, help_text='Reviews visibles públicamente')),
                ('require_approval', models.BooleanField(default=True, help_text='Requiere aprobación del staff antes de publicar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_settings', to='organizations.gym')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Fecha límite para completar la review')),
                ('email_sent', models.BooleanField(default=False)),
                ('popup_created', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='clients.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='organizations.gym')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='activities.activitysession')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'client')},
            },
        ),
        migrations.CreateModel(
            name='ClassReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_rating', models.PositiveIntegerField(help_text='Valoración del instructor (1-5)')),
                ('class_rating', models.PositiveIntegerField(help_text='Valoración de la clase (1-5)')),
                ('comment', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags: Limpio, Intenso, Amigable, etc.')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reviews', to='staff.staffprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reviews', to='clients.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reviews', to='organizations.gym')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='activities.activitysession')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'client')},
            },
        ),
    ]
