# Generated by Django 4.2.27 on 2026-01-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_clientvisit_cancellation_type'),
        ('staff', '0007_ratingincentive'),
        ('organizations', '0009_gymgoal'),
        ('activities', '0006_reviewsettings_reviewrequest_classreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='qr_checkin_enabled',
            field=models.BooleanField(default=False, help_text='Permite a los clientes marcar asistencia escaneando QR', verbose_name='Check-in QR habilitado'),
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_mode', models.CharField(choices=[('STAFF_ONLY', 'Solo el staff marca asistencia'), ('QR_ENABLED', 'Clientes pueden marcar con QR'), ('BOTH', 'Ambos métodos disponibles')], default='STAFF_ONLY', help_text='Define cómo los clientes pueden marcar asistencia', max_length=20, verbose_name='Modo de Check-in')),
                ('qr_checkin_minutes_before', models.PositiveIntegerField(default=15, help_text='Minutos antes del inicio que se permite el check-in', verbose_name='Minutos antes de clase')),
                ('qr_checkin_minutes_after', models.PositiveIntegerField(default=30, help_text='Minutos después del inicio que se permite el check-in', verbose_name='Minutos después del inicio')),
                ('qr_refresh_seconds', models.PositiveIntegerField(default=30, help_text='Segundos para renovar el código QR (seguridad)', verbose_name='Renovar QR cada (segundos)')),
                ('checkin_success_message', models.CharField(default='✅ ¡Check-in completado! Te esperamos en clase.', help_text='Mensaje mostrado al cliente tras check-in exitoso', max_length=200, verbose_name='Mensaje de éxito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Configuración de Asistencias',
                'verbose_name_plural': 'Configuraciones de Asistencias',
            },
        ),
        migrations.CreateModel(
            name='SessionCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('STAFF', 'Marcado por Staff'), ('QR', 'Escaneado QR por cliente'), ('APP', 'Desde App del cliente'), ('AUTO', 'Automático (reserva previa)')], default='STAFF', max_length=20, verbose_name='Método de check-in')),
                ('qr_token', models.CharField(blank=True, max_length=64, null=True)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_performed', to='staff.staffprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_checkins', to='clients.client')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='activities.activitysession')),
            ],
            options={
                'verbose_name': 'Check-in de Sesión',
                'verbose_name_plural': 'Check-ins de Sesiones',
                'ordering': ['-checked_in_at'],
                'unique_together': {('session', 'client')},
            },
        ),
    ]
