# Generated by Django 4.2.27 on 2026-01-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_qr_checkin_enabled_attendancesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_visible_online',
            field=models.BooleanField(default=False, help_text='Si se activa, la actividad aparecerá en el horario público de la web/app', verbose_name='Visible en Horario Público'),
        ),
    ]
