# Generated by Django 4.2.27 on 2026-01-19 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_clientmembership_created_by_clientmembership_gym_and_more'),
        ('activities', '0008_activity_is_visible_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('PENDING', 'Pendiente de Pago')], default='CONFIRMED', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clients.client')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='activities.activitysession')),
            ],
            options={
                'verbose_name': 'Reserva de Clase',
                'verbose_name_plural': 'Reservas de Clases',
                'ordering': ['-booked_at'],
                'unique_together': {('session', 'client')},
            },
        ),
    ]
