# Generated by Django 4.2.27 on 2026-01-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_ratingincentive'),
        ('activities', '0009_activitysessionbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysessionbooking',
            name='attendance_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ATTENDED', 'Asistió'), ('NO_SHOW', 'No Asistió'), ('LATE_CANCEL', 'Canceló Tarde')], default='PENDING', help_text='Estado de asistencia a la clase', max_length=20),
        ),
        migrations.AddField(
            model_name='activitysessionbooking',
            name='marked_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se marcó la asistencia', null=True),
        ),
        migrations.AddField(
            model_name='activitysessionbooking',
            name='marked_by',
            field=models.ForeignKey(blank=True, help_text='Staff que marcó la asistencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to='staff.staffprofile'),
        ),
    ]
