# Generated by Django 4.2.27 on 2026-01-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_publicportalsettings'),
        ('activities', '0010_add_attendance_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_room_overlaps', models.BooleanField(default=False, help_text='Si está desactivado, no se podrán crear clases simultáneas en la misma sala', verbose_name='Permitir solapamiento de salas')),
                ('allow_staff_overlaps', models.BooleanField(default=False, help_text='Si está desactivado, un instructor no podrá impartir dos clases a la vez', verbose_name='Permitir solapamiento de instructores')),
                ('min_break_between_classes', models.IntegerField(default=0, help_text='Tiempo mínimo que debe pasar entre dos clases del mismo instructor', verbose_name='Descanso mínimo entre clases (minutos)')),
                ('max_consecutive_classes', models.IntegerField(default=0, help_text='Número máximo de clases seguidas que puede impartir un instructor (0 = sin límite)', verbose_name='Máximo de clases consecutivas')),
                ('max_advance_booking_days', models.IntegerField(default=30, help_text='Cuántos días de antelación pueden reservar los clientes (0 = sin límite)', verbose_name='Días máximos de antelación para reservar')),
                ('min_advance_booking_hours', models.IntegerField(default=0, help_text='Mínimo de horas de antelación para hacer una reserva', verbose_name='Horas mínimas de antelación para reservar')),
                ('allow_cancellation', models.BooleanField(default=True, help_text='Los clientes pueden cancelar sus reservas', verbose_name='Permitir cancelación de reservas')),
                ('cancellation_deadline_hours', models.IntegerField(default=2, help_text='Horas mínimas de antelación para cancelar sin penalización', verbose_name='Plazo para cancelar (horas)')),
                ('enable_waitlist', models.BooleanField(default=True, help_text='Permitir lista de espera cuando una clase está llena', verbose_name='Habilitar lista de espera')),
                ('auto_assign_from_waitlist', models.BooleanField(default=True, help_text='Asignar plaza automáticamente cuando alguien cancela', verbose_name='Asignar automáticamente desde lista de espera')),
                ('notify_class_changes', models.BooleanField(default=True, help_text='Enviar notificaciones cuando se modifica o cancela una clase', verbose_name='Notificar cambios de clases')),
                ('reminder_hours_before', models.IntegerField(default=2, help_text='Enviar recordatorio X horas antes de la clase (0 = desactivado)', verbose_name='Recordatorio (horas antes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_settings', to='organizations.gym', verbose_name='Gimnasio')),
            ],
            options={
                'verbose_name': 'Configuración de Horarios',
                'verbose_name_plural': 'Configuraciones de Horarios',
            },
        ),
    ]
