# Generated by Django 4.2.27 on 2026-01-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_schedulesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'permissions': [('access_calendar', 'Acceder al Calendario de Clases'), ('manage_activity_sessions', 'Gestionar Sesiones de Actividades')]},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('access_calendar', 'Acceder al Calendario de Clases'), ('create_class_sessions', 'Crear Sesiones de Clases')]},
        ),
        migrations.AlterModelOptions(
            name='schedulesettings',
            options={'permissions': [('access_schedule_settings', 'Acceder a Configuración de Horarios'), ('modify_schedule_settings', 'Modificar Configuración de Horarios')], 'verbose_name': 'Configuración de Horarios', 'verbose_name_plural': 'Configuraciones de Horarios'},
        ),
    ]
