# Generated by Django 4.2.27 on 2026-01-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_alter_activity_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='allow_spot_booking',
            field=models.BooleanField(default=False, help_text='Permite a los clientes elegir un puesto/máquina específico al reservar', verbose_name='Permitir reserva de puesto'),
        ),
        migrations.AddField(
            model_name='activitysessionbooking',
            name='spot_number',
            field=models.PositiveIntegerField(blank=True, help_text='Número de puesto/máquina reservado (si la actividad lo permite)', null=True, verbose_name='Número de puesto'),
        ),
    ]
