# Generated by Django 4.2.27 on 2026-01-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0100_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitysession',
            name='session_calendar_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitysession',
            name='session_activity_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitysession',
            name='session_staff_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitysession',
            name='session_room_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitysessionbooking',
            name='booking_client_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitysessionbooking',
            name='booking_attendance_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitysessionbooking',
            name='booking_recent_idx',
        ),
    ]
