# Generated by Django 4.2.27 on 2026-01-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0101_remove_activitysession_session_calendar_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesettings',
            name='checkin_mode',
            field=models.CharField(choices=[('STAFF_ONLY', 'Solo el staff marca asistencia'), ('QR_ENABLED', 'Clientes pueden marcar con QR'), ('FACE_ENABLED', 'Reconocimiento facial habilitado'), ('BOTH', 'Ambos métodos disponibles'), ('ALL', 'Todos los métodos (QR, Facial, Staff)')], default='STAFF_ONLY', help_text='Define cómo los clientes pueden marcar asistencia', max_length=20, verbose_name='Modo de Check-in'),
        ),
        migrations.AlterField(
            model_name='sessioncheckin',
            name='method',
            field=models.CharField(choices=[('STAFF', 'Marcado por Staff'), ('QR', 'Escaneado QR por cliente'), ('FACE', 'Reconocimiento facial'), ('APP', 'Desde App del cliente'), ('AUTO', 'Automático (reserva previa)')], default='STAFF', max_length=20, verbose_name='Método de check-in'),
        ),
    ]
