# Generated by Django 5.2.10 on 2026-02-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0102_alter_attendancesettings_checkin_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesettings',
            name='allow_late_checkin',
            field=models.BooleanField(default=True, help_text='Permitir check-in después de que haya empezado la clase', verbose_name='Permitir check-in tardío'),
        ),
        migrations.AddField(
            model_name='schedulesettings',
            name='block_holidays',
            field=models.BooleanField(default=True, help_text='No permitir crear clases en días marcados como festivos cerrados', verbose_name='Bloquear clases en festivos'),
        ),
        migrations.AddField(
            model_name='schedulesettings',
            name='calendar_slot_minutes',
            field=models.IntegerField(default=30, help_text='Duración de cada slot en el calendario (15, 30, 60 min)', verbose_name='Intervalo de calendario (minutos)'),
        ),
        migrations.AddField(
            model_name='schedulesettings',
            name='enforce_opening_hours',
            field=models.BooleanField(default=True, help_text='Las clases deben estar dentro del horario de apertura del gimnasio', verbose_name='Respetar horario de apertura'),
        ),
        migrations.AddField(
            model_name='schedulesettings',
            name='late_checkin_grace_minutes',
            field=models.IntegerField(default=10, help_text='Cuántos minutos después del inicio se permite el check-in', verbose_name='Minutos de gracia para llegar tarde'),
        ),
        migrations.AddField(
            model_name='schedulesettings',
            name='schedule_end_time',
            field=models.TimeField(default='22:00', help_text='Hora más tardía para que terminen las clases', verbose_name='Hora fin de clases'),
        ),
        migrations.AddField(
            model_name='schedulesettings',
            name='schedule_start_time',
            field=models.TimeField(default='07:00', help_text='Hora más temprana para programar clases', verbose_name='Hora inicio de clases'),
        ),
    ]
