# Generated by Django 5.2.10 on 2026-02-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0103_add_schedule_operating_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulesettings',
            name='allow_cancellation',
        ),
        migrations.RemoveField(
            model_name='schedulesettings',
            name='auto_assign_from_waitlist',
        ),
        migrations.RemoveField(
            model_name='schedulesettings',
            name='cancellation_deadline_hours',
        ),
        migrations.RemoveField(
            model_name='schedulesettings',
            name='enable_waitlist',
        ),
        migrations.RemoveField(
            model_name='schedulesettings',
            name='max_advance_booking_days',
        ),
        migrations.RemoveField(
            model_name='schedulesettings',
            name='min_advance_booking_hours',
        ),
    ]
