# Generated by Django 5.2.10 on 2026-02-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0104_remove_duplicate_booking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypolicy',
            name='cancellation_window_hours',
            field=models.PositiveIntegerField(default=2, help_text='Horas antes de la clase para cancelar sin penalización', verbose_name='Ventana de Cancelación (Horas)'),
        ),
    ]
