# Generated by Django 5.2.10 on 2026-02-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0105_add_client_penalty'),
        ('clients', '0109_add_client_penalty'),
        ('memberships', '0107_add_booking_restrictions_to_planaccess'),
        ('organizations', '0020_add_checkin_methods_and_geolocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'ordering': ['-is_vip', 'joined_at']},
        ),
        migrations.AddField(
            model_name='activitypolicy',
            name='vip_groups',
            field=models.ManyToManyField(blank=True, help_text='Clientes en estos grupos tienen prioridad absoluta en lista de espera', related_name='vip_policies', to='clients.clientgroup', verbose_name='Grupos VIP'),
        ),
        migrations.AddField(
            model_name='activitypolicy',
            name='vip_membership_plans',
            field=models.ManyToManyField(blank=True, help_text='Clientes con estos planes tienen prioridad absoluta en lista de espera', related_name='vip_policies', to='memberships.membershipplan', verbose_name='Planes VIP'),
        ),
        migrations.AddField(
            model_name='activitypolicy',
            name='waitlist_claim_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minutos que tienen los clientes para reclamar. Tras esto, se auto-promociona al primero.', verbose_name='Timeout para Reclamar (Minutos)'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='claim_expires_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo expira el tiempo para reclamar', null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo reclamó la plaza', null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='organizations.gym'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='Cliente tiene prioridad VIP'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se notificó que hay plaza', null=True),
        ),
        migrations.AlterField(
            model_name='activitypolicy',
            name='waitlist_mode',
            field=models.CharField(choices=[('AUTO_PROMOTE', 'Auto-Promoción (Automático)'), ('BROADCAST', 'Broadcast (Notifica a varios)'), ('FIRST_CLAIM', 'Primero que Reclama (Competición)')], default='AUTO_PROMOTE', max_length=20, verbose_name='Modo de Lista'),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='status',
            field=models.CharField(choices=[('WAITING', 'En espera'), ('NOTIFIED', 'Notificado (Esperando claim)'), ('PROMOTED', 'Promovido (Dentro)'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado')], default='WAITING', max_length=20),
        ),
    ]
