# Generated by Django 5.2.10 on 2026-02-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0106_waitlist_vip_first_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitypolicy',
            name='cancellation_window_hours',
        ),
        migrations.AddField(
            model_name='activitypolicy',
            name='booking_weekday_release',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text="Solo para modo 'Día de la semana'", null=True, verbose_name='Día de Apertura'),
        ),
        migrations.AddField(
            model_name='activitypolicy',
            name='cancellation_window_unit',
            field=models.CharField(choices=[('MINUTES', 'Minutos'), ('HOURS', 'Horas'), ('DAYS', 'Días')], default='HOURS', max_length=10, verbose_name='Unidad de Tiempo'),
        ),
        migrations.AddField(
            model_name='activitypolicy',
            name='cancellation_window_value',
            field=models.PositiveIntegerField(default=2, help_text='Tiempo antes de la clase para cancelar sin penalización', verbose_name='Ventana de Cancelación'),
        ),
        migrations.AddField(
            model_name='activitypolicy',
            name='require_active_membership',
            field=models.BooleanField(default=True, help_text='El cliente debe tener una membresía activa para reservar', verbose_name='Requiere Membresía Activa'),
        ),
        migrations.AddField(
            model_name='activitypolicy',
            name='require_paid_membership',
            field=models.BooleanField(default=False, help_text='El cliente debe tener los pagos al día para reservar (más restrictivo)', verbose_name='Requiere Membresía Pagada'),
        ),
        migrations.AlterField(
            model_name='activitypolicy',
            name='booking_window_mode',
            field=models.CharField(choices=[('OPEN', 'Abierto (Sin restricción)'), ('RELATIVE_START', 'Horas antes del inicio'), ('FIXED_TIME', 'Días antes (hora fija)'), ('WEEKLY_FIXED', 'Día de la semana (hora fija)')], default='RELATIVE_START', max_length=20, verbose_name='Modo de Apertura'),
        ),
    ]
