# Generated by Django 5.2.10 on 2026-02-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0107_booking_policy_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypolicy',
            name='require_active_membership',
            field=models.BooleanField(blank=True, default=None, help_text='Dejar vacío para usar la configuración general del gimnasio', null=True, verbose_name='Requiere Membresía Activa'),
        ),
        migrations.AlterField(
            model_name='activitypolicy',
            name='require_paid_membership',
            field=models.BooleanField(blank=True, default=None, help_text='Dejar vacío para usar la configuración general del gimnasio', null=True, verbose_name='Requiere Membresía Pagada'),
        ),
    ]
