# Generated by Django 4.2.27 on 2026-01-15 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_purchaseorder_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='providers.provider'),
        ),
    ]
