# Generated by Django 5.1.15 on 2026-01-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: IVA 21%', max_length=50, verbose_name='Nombre del Impuesto')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Ej: 0.21 para 21%', max_digits=5, verbose_name='Porcentaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
    ]
