# Generated by Django 5.1.15 on 2026-01-11 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('organizations', '0002_gym_brand_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrate',
            name='rate',
        ),
        migrations.AddField(
            model_name='taxrate',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='organizations.gym'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='rate_percent',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Ej: 21.00', max_digits=5, verbose_name='Porcentaje'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fondo Inicial')),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculado automáticamente', max_digits=10, verbose_name='Ventas Efectivo Sistema')),
                ('total_cash_withdrawals', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Retiradas')),
                ('total_cash_additions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ingresos Extra')),
                ('expected_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Esperado en Caja')),
                ('actual_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Contado Real (Arqueo)')),
                ('discrepancy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuadre')),
                ('notes', models.TextField(blank=True, verbose_name='Notas de Cierre')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrada')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_sessions', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='organizations.gym')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('is_cash', models.BooleanField(default=False, help_text='Si se marca, este método requiere una Sesión de Caja abierta y suma al efectivo físico.', verbose_name='Control de Caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('provider_code', models.CharField(blank=True, help_text="ej: 'stripe_terminal', 'redsys', etc.", max_length=50, null=True, verbose_name='Código Proveedor')),
                ('gym', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
    ]
