# Generated by Django 5.1.15 on 2026-01-11 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_taxrate_rate_taxrate_gym_taxrate_rate_percent_and_more'),
        ('organizations', '0004_gym_facebook_gym_instagram_gym_tiktok_gym_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_public_key', models.CharField(blank=True, help_text='Clave Pública (pk_test_...)', max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, help_text='Clave Secreta (sk_test_...)', max_length=255)),
                ('currency', models.CharField(default='EUR', help_text='Código de moneda ISO (EUR, USD...)', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_settings', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Ajustes Financieros',
                'verbose_name_plural': 'Ajustes Financieros',
            },
        ),
    ]
