# Generated by Django 5.1.15 on 2026-01-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='redsys_environment',
            field=models.CharField(choices=[('TEST', 'Pruebas / Sandbox'), ('REAL', 'Producción / Real')], default='TEST', max_length=10, verbose_name='Entorno'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='redsys_merchant_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='FUC (Código de Comercio)'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='redsys_merchant_terminal',
            field=models.CharField(blank=True, default='001', max_length=10, verbose_name='Terminal'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='redsys_secret_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Clave Secreta (clave256)'),
        ),
        migrations.AlterField(
            model_name='financesettings',
            name='currency',
            field=models.CharField(default='EUR', help_text='Ej: EUR, USD', max_length=3, verbose_name='Moneda Principal'),
        ),
        migrations.AlterField(
            model_name='financesettings',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Public Key'),
        ),
        migrations.AlterField(
            model_name='financesettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Secret Key'),
        ),
    ]
