# Generated by Django 5.1.15 on 2026-01-11 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_stripe_customer_id'),
        ('finance', '0004_financesettings_redsys_environment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financesettings',
            options={'verbose_name': 'Configuración Financiera', 'verbose_name_plural': 'Configuraciones Financieras'},
        ),
        migrations.CreateModel(
            name='ClientRedsysToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Suele ser el Ds_Order de la primera operación', max_length=100, verbose_name='Token / Referencia')),
                ('card_brand', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('card_number', models.CharField(blank=True, max_length=20, verbose_name='Número Enmascarado')),
                ('expiration', models.CharField(blank=True, max_length=10, verbose_name='Caducidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redsys_tokens', to='clients.client')),
            ],
            options={
                'verbose_name': 'Token Redsys Cliente',
                'verbose_name_plural': 'Tokens Redsys Cliente',
            },
        ),
    ]
