# Generated by Django 5.1.15 on 2026-01-13 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_financesettings_options_clientredsystoken'),
        ('organizations', '0004_gym_facebook_gym_instagram_gym_tiktok_gym_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Recepción Principal', max_length=100, verbose_name='Nombre del Dispositivo')),
                ('device_type', models.CharField(choices=[('STRIPE_READER', 'Lector Tartjetas (Stripe Terminal)'), ('PRINTER_NETWORK', 'Impresora Térmica (Red)'), ('TURNSTILE', 'Torno de Acceso')], max_length=20)),
                ('identifier', models.CharField(help_text='Serial Number (Stripe) o IP (Impresora)', max_length=255, verbose_name='Identificador / IP')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Dispositivo Físico',
                'verbose_name_plural': 'Dispositivos Físicos',
            },
        ),
    ]
