# Generated by Django 4.2.27 on 2026-01-15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_financesettings_allow_client_delete_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='allow_client_pay_next_fee',
            field=models.BooleanField(default=False, help_text='Permitir que el cliente adelante/pague su siguiente cuota desde la app.'),
        ),
    ]
