# Generated by Django 4.2.27 on 2026-01-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_financesettings_allow_client_pay_next_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='available_for_online',
            field=models.BooleanField(default=False, help_text='Si se marca, este método estará disponible en el portal público', verbose_name='Disponible para compra online'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='gateway',
            field=models.CharField(choices=[('NONE', 'Sin pasarela (Efectivo/Manual)'), ('STRIPE', 'Stripe'), ('REDSYS', 'Redsys'), ('PAYPAL', 'PayPal')], default='NONE', max_length=20, verbose_name='Pasarela de pago'),
        ),
    ]
