# Generated by Django 4.2.27 on 2026-01-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_clientmembership_created_by_clientmembership_gym_and_more'),
        ('finance', '0009_alter_paymentmethod_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('concept', models.CharField(help_text='Ej: Cuota Enero 2026', max_length=255)),
                ('payment_method', models.CharField(blank=True, help_text='Ej: Visa **** 4242', max_length=50)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
            ],
            options={
                'verbose_name': 'Pago de Cliente',
                'verbose_name_plural': 'Pagos de Clientes',
                'ordering': ['-date'],
            },
        ),
    ]
