# Generated by Django 4.2.27 on 2026-01-21 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_publicportalsettings'),
        ('products', '0002_product_preferred_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0010_clientpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='CIF/NIF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('bank_account', models.CharField(blank=True, max_length=34, verbose_name='Cuenta Bancaria (IBAN)')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Persona de Contacto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('color', models.CharField(default='#6366f1', help_text='Código hexadecimal, ej: #3b82f6', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(default='💰', help_text='Emoji o nombre de icono', max_length=50, verbose_name='Icono')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=255, verbose_name='Concepto')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Nº Factura/Referencia')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Imponible')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='% IVA')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe IVA')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('issue_date', models.DateField(help_text='Fecha de la factura', verbose_name='Fecha Emisión')),
                ('due_date', models.DateField(help_text='Fecha límite de pago', verbose_name='Fecha Vencimiento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('PAID', 'Pagado'), ('OVERDUE', 'Vencido'), ('PARTIAL', 'Parcialmente Pagado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe Pagado')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Gasto Recurrente')),
                ('recurrence_frequency', models.CharField(choices=[('NONE', 'Puntual'), ('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('YEARLY', 'Anual')], default='NONE', max_length=20, verbose_name='Frecuencia')),
                ('recurrence_day', models.IntegerField(blank=True, help_text='Día en que se genera (1-28)', null=True, verbose_name='Día del Mes')),
                ('next_generation_date', models.DateField(blank=True, null=True, verbose_name='Próxima Generación')),
                ('is_active_recurrence', models.BooleanField(default=True, help_text='Pausar/reactivar generación automática', verbose_name='Recurrencia Activa')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/%Y/%m/', verbose_name='Adjunto (Factura)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='organizations.gym')),
                ('parent_expense', models.ForeignKey(blank=True, help_text='Si este gasto fue generado automáticamente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='finance.expense')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.paymentmethod')),
                ('related_products', models.ManyToManyField(blank=True, help_text='Productos comprados en este gasto', related_name='expenses', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.supplier')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
