# Generated by Django 4.2.27 on 2026-01-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_add_expenses_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='auto_charge_enabled',
            field=models.BooleanField(default=False, help_text='Si está activo, el sistema intentará cobrar automáticamente las cuotas vencidas', verbose_name='Cobro automático habilitado'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='auto_charge_max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Número máximo de intentos de cobro si falla (ej: tarjeta sin fondos, caducada)', verbose_name='Máximo de reintentos'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='auto_charge_retry_days',
            field=models.PositiveIntegerField(default=3, help_text='Días que esperar antes de reintentar un cobro fallido', verbose_name='Días entre reintentos'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='auto_charge_time',
            field=models.TimeField(default='08:00', help_text='Hora a la que se ejecuta el cobro automático diario', verbose_name='Hora del cobro automático'),
        ),
    ]
