# Generated by Django 4.2.27 on 2026-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_add_auto_charge_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='app_gateway_strategy',
            field=models.CharField(choices=[('STRIPE_ONLY', 'Solo Stripe'), ('REDSYS_ONLY', 'Solo Redsys'), ('STRIPE_PRIMARY', 'Stripe principal, Redsys backup'), ('REDSYS_PRIMARY', 'Redsys principal, Stripe backup'), ('CLIENT_CHOICE', 'Cliente elige')], default='STRIPE_ONLY', help_text='Estrategia de pasarela para pagos desde la app móvil y portal online', max_length=20, verbose_name='Pasarela App/Online'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='pos_gateway_strategy',
            field=models.CharField(choices=[('STRIPE_ONLY', 'Solo Stripe'), ('REDSYS_ONLY', 'Solo Redsys'), ('STRIPE_PRIMARY', 'Stripe principal, Redsys backup'), ('REDSYS_PRIMARY', 'Redsys principal, Stripe backup'), ('CLIENT_CHOICE', 'Cliente elige')], default='STRIPE_ONLY', help_text='Estrategia de pasarela para cobros desde el backoffice/POS', max_length=20, verbose_name='Pasarela POS/Backoffice'),
        ),
    ]
