# Generated by Django 4.2.27 on 2026-02-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_add_provider_logo'),
        ('finance', '0013_gateway_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='providers.provider'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.supplier'),
        ),
    ]
