# Generated by Django 5.2.10 on 2026-02-01 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_add_expense_provider'),
        ('organizations', '0018_add_membership_purchase_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='verifactu_certificate',
            field=models.FileField(blank=True, help_text='Certificado digital para firmar los registros (requerido para modo FULL)', null=True, upload_to='verifactu_certs/', verbose_name='Certificado Digital (.p12/.pfx)'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='verifactu_certificate_password',
            field=models.CharField(blank=True, help_text='Contraseña para desbloquear el certificado .p12', max_length=255, verbose_name='Contraseña del Certificado'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='verifactu_enabled',
            field=models.BooleanField(default=False, help_text='⚠️ ATENCIÓN: Una vez activado, NO SE PUEDE DESACTIVAR. Cumplimiento RD 1007/2023', verbose_name='Verifactu Activado'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='verifactu_enrolled_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se activó Verifactu', null=True, verbose_name='Fecha de Alta Verifactu'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='verifactu_mode',
            field=models.CharField(choices=[('LOCAL', 'Solo local (hash + QR, sin envío)'), ('FULL', 'Completo (envío inmediato a AEAT)')], default='LOCAL', help_text='LOCAL: genera hash/QR pero no envía. FULL: envía cada factura a la AEAT.', max_length=20, verbose_name='Modo Verifactu'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='verifactu_software_name',
            field=models.CharField(default='GymCRM', help_text='Nombre del software que genera las facturas', max_length=100, verbose_name='Nombre del Software'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='verifactu_software_nif',
            field=models.CharField(blank=True, help_text='NIF de la empresa desarrolladora del software', max_length=15, verbose_name='NIF del Desarrollador'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='verifactu_software_version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='Versión del Software'),
        ),
        migrations.CreateModel(
            name='VerifactuRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(default='INVOICE', max_length=50, verbose_name='Tipo de documento')),
                ('invoice_id', models.PositiveIntegerField(verbose_name='ID del documento')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Número de factura')),
                ('invoice_series', models.CharField(blank=True, default='', max_length=20, verbose_name='Serie')),
                ('issuer_nif', models.CharField(max_length=15, verbose_name='NIF Emisor')),
                ('issuer_name', models.CharField(max_length=255, verbose_name='Nombre/Razón Social Emisor')),
                ('recipient_nif', models.CharField(blank=True, max_length=15, verbose_name='NIF Receptor')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Nombre Receptor')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Imponible')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=21, max_digits=5, verbose_name='Tipo IVA')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cuota IVA')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Factura')),
                ('invoice_date', models.DateField(verbose_name='Fecha de factura')),
                ('record_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Momento de registro')),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash del registro anterior')),
                ('record_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash de este registro')),
                ('qr_code', models.TextField(blank=True, help_text='URL de verificación codificada', verbose_name='Datos del QR')),
                ('verification_url', models.URLField(blank=True, max_length=500, verbose_name='URL de verificación')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de envío'), ('SENT', 'Enviado a AEAT'), ('ACCEPTED', 'Aceptado por AEAT'), ('REJECTED', 'Rechazado por AEAT'), ('ERROR', 'Error de envío'), ('LOCAL_ONLY', 'Solo local (sin envío)')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('aeat_response_code', models.CharField(blank=True, max_length=50, verbose_name='Código respuesta AEAT')),
                ('aeat_response_message', models.TextField(blank=True, verbose_name='Mensaje AEAT')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado a AEAT')),
                ('signature', models.TextField(blank=True, help_text='Firma del registro', verbose_name='Firma electrónica')),
                ('software_name', models.CharField(default='GymCRM', max_length=100, verbose_name='Software')),
                ('software_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Versión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifactu_records', to='organizations.gym')),
                ('previous_record', models.ForeignKey(blank=True, help_text='Registro anterior en la cadena', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_record', to='finance.verifacturecord')),
            ],
            options={
                'verbose_name': 'Registro Verifactu',
                'verbose_name_plural': 'Registros Verifactu',
                'ordering': ['-record_timestamp'],
                'indexes': [models.Index(fields=['gym', 'invoice_number'], name='finance_ver_gym_id_f95961_idx'), models.Index(fields=['gym', 'record_timestamp'], name='finance_ver_gym_id_679611_idx'), models.Index(fields=['status'], name='finance_ver_status_956915_idx')],
            },
        ),
    ]
