# Generated by Django 5.2.10 on 2026-02-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_add_verifactu_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='verifactu_developer_country',
            field=models.CharField(choices=[('ES', 'España (NIF/CIF)'), ('EU', 'Unión Europea (VAT)'), ('US', 'Estados Unidos (EIN)'), ('OTHER', 'Otro país')], default='ES', help_text='País donde está registrada la empresa desarrolladora', max_length=5, verbose_name='País del Desarrollador'),
        ),
        migrations.AlterField(
            model_name='financesettings',
            name='verifactu_software_nif',
            field=models.CharField(blank=True, help_text='NIF español, VAT europeo (ej: DE123456789), EIN americano (ej: 12-3456789), u otro ID fiscal', max_length=50, verbose_name='ID Fiscal del Desarrollador'),
        ),
    ]
