# Generated by Django 5.2.10 on 2026-02-03 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0107_referral_system'),
        ('finance', '0016_add_verifactu_developer_country'),
        ('organizations', '0019_referral_system'),
        ('sales', '0104_deferred_payment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Disponible')),
                ('allow_negative', models.BooleanField(default=False, help_text='Permite que el cliente tenga saldo negativo (fiado)', verbose_name='Permitir Saldo Negativo')),
                ('negative_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Máximo saldo negativo permitido', max_digits=10, verbose_name='Límite de Saldo Negativo')),
                ('auto_topup_enabled', models.BooleanField(default=False, verbose_name='Auto-Recarga Activada')),
                ('auto_topup_threshold', models.DecimalField(decimal_places=2, default=10.0, help_text='Recargar cuando el saldo baje de esta cantidad', max_digits=10, verbose_name='Umbral de Auto-Recarga')),
                ('auto_topup_amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Cantidad de Auto-Recarga')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('total_topups', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Recargado')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Gastado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='clients.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_wallets', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Monedero de Cliente',
                'verbose_name_plural': 'Monederos de Clientes',
                'unique_together': {('client', 'gym')},
            },
        ),
        migrations.CreateModel(
            name='WalletSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_enabled', models.BooleanField(default=False, verbose_name='Sistema de Monedero Habilitado')),
                ('auto_create_wallet', models.BooleanField(default=True, help_text='Crear monedero al registrar nuevo cliente', verbose_name='Crear Monedero Automáticamente')),
                ('allow_negative_default', models.BooleanField(default=False, verbose_name='Permitir Saldo Negativo por Defecto')),
                ('default_negative_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Límite de Saldo Negativo por Defecto')),
                ('topup_bonus_enabled', models.BooleanField(default=False, help_text='Dar extra cuando el cliente recarga su monedero', verbose_name='Bonificación por Recarga')),
                ('topup_bonus_type', models.CharField(choices=[('PERCENT', 'Porcentaje'), ('FIXED', 'Cantidad Fija'), ('TIERED', 'Por Tramos')], default='PERCENT', max_length=20, verbose_name='Tipo de Bonificación')),
                ('topup_bonus_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='Ej: 10 = cliente recarga 50€, recibe 55€', max_digits=5, verbose_name='% de Bonificación')),
                ('topup_bonus_min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Recarga Mínima para Bonificación')),
                ('topup_bonus_max_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='0 = sin límite', max_digits=10, verbose_name='Bonificación Máxima')),
                ('topup_bonus_tiers', models.JSONField(blank=True, default=list, help_text='Ej: [{"min": 50, "bonus": 5}, {"min": 100, "bonus": 15}]', verbose_name='Tramos de Bonificación')),
                ('allow_auto_topup', models.BooleanField(default=False, help_text='Los clientes pueden configurar recarga automática', verbose_name='Permitir Auto-Recarga')),
                ('use_wallet_first', models.BooleanField(default=True, help_text='Intentar usar saldo antes que otros métodos de pago', verbose_name='Usar Saldo Primero')),
                ('allow_partial_wallet_payment', models.BooleanField(default=True, help_text='Si no hay saldo suficiente, usar lo disponible y pagar el resto con otro método', verbose_name='Permitir Pago Parcial con Saldo')),
                ('refunds_to_wallet', models.BooleanField(default=True, help_text='Las devoluciones van al saldo en lugar de al método original', verbose_name='Devoluciones al Monedero')),
                ('balance_expires', models.BooleanField(default=False, verbose_name='El Saldo Caduca')),
                ('balance_expiry_months', models.PositiveIntegerField(default=12, help_text='Meses de inactividad antes de que caduque el saldo', verbose_name='Meses hasta Caducidad')),
                ('show_in_client_portal', models.BooleanField(default=True, verbose_name='Mostrar en Portal del Cliente')),
                ('show_in_app', models.BooleanField(default=True, verbose_name='Mostrar en App Móvil')),
                ('allow_online_topup', models.BooleanField(default=True, help_text='El cliente puede recargar desde el portal/app', verbose_name='Permitir Recarga Online')),
                ('topup_preset_amounts', models.JSONField(blank=True, default=list, help_text='Ej: [20, 50, 100, 200]', verbose_name='Montos Predefinidos para Recarga')),
                ('min_topup_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Recarga Mínima')),
                ('max_topup_amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Recarga Máxima')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_settings', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Configuración de Monedero',
                'verbose_name_plural': 'Configuraciones de Monedero',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('TOPUP', 'Recarga'), ('TOPUP_BONUS', 'Bonificación por Recarga'), ('PAYMENT', 'Pago'), ('REFUND', 'Devolución'), ('ADJUSTMENT', 'Ajuste Manual'), ('REFERRAL_BONUS', 'Bonus por Referido'), ('POINTS_CONVERSION', 'Conversión de Puntos'), ('EXPIRY', 'Caducidad'), ('TRANSFER_IN', 'Transferencia Recibida'), ('TRANSFER_OUT', 'Transferencia Enviada')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positivo para ingresos, negativo para gastos', max_digits=10, verbose_name='Monto')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Anterior')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Posterior')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('external_payment_ref', models.CharField(blank=True, help_text='ID de pago en Stripe/Redsys si aplica', max_length=100, verbose_name='Referencia de Pago Externa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='sales.order')),
                ('topup_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_topups', to='finance.paymentmethod')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.clientwallet')),
            ],
            options={
                'verbose_name': 'Transacción de Monedero',
                'verbose_name_plural': 'Transacciones de Monedero',
                'ordering': ['-created_at'],
            },
        ),
    ]
