# Generated by Django 4.2.27 on 2026-01-19 15:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0010_publicportalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Razón social de tu empresa', max_length=200)),
                ('company_tax_id', models.CharField(help_text='CIF/NIF', max_length=50)),
                ('company_address', models.TextField(help_text='Dirección fiscal completa')),
                ('company_email', models.EmailField(help_text='Email de soporte', max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='billing/company/')),
                ('stripe_publishable_key', models.CharField(blank=True, help_text='Clave pública de Stripe (pk_...)', max_length=200)),
                ('stripe_secret_key', models.CharField(blank=True, help_text='Clave secreta de Stripe (sk_...) - ENCRIPTADA', max_length=200)),
                ('stripe_webhook_secret', models.CharField(blank=True, help_text='Secret del webhook de Stripe (whsec_...)', max_length=200)),
                ('grace_period_days', models.PositiveIntegerField(default=15, help_text='Días de gracia antes de suspender por falta de pago')),
                ('enable_auto_suspension', models.BooleanField(default=True, help_text='Suspender automáticamente tras el periodo de gracia')),
                ('payment_failed_email_subject', models.CharField(default='Problema con tu pago', max_length=200)),
                ('payment_failed_email_body', models.TextField(default='Tu pago ha fallado. Por favor, actualiza tu método de pago.', help_text='Plantilla de email para pagos fallidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Facturación',
                'verbose_name_plural': 'Configuración de Facturación',
            },
        ),
        migrations.CreateModel(
            name='FranchiseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('PAST_DUE', 'Pago Vencido'), ('SUSPENDED', 'Suspendida'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20)),
                ('billing_frequency', models.CharField(default='MONTHLY', max_length=20)),
                ('current_period_start', models.DateField()),
                ('current_period_end', models.DateField()),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('payment_method_last4', models.CharField(blank=True, max_length=4)),
                ('payment_method_brand', models.CharField(blank=True, max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('suspension_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('covered_gyms', models.ManyToManyField(blank=True, help_text='Gimnasios cubiertos por esta suscripción de franquicia', related_name='franchise_subscription', to='organizations.gym')),
                ('franchise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.franchise')),
            ],
            options={
                'verbose_name': 'Suscripción de Franquicia',
                'verbose_name_plural': 'Suscripciones de Franquicias',
            },
        ),
        migrations.CreateModel(
            name='GymSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('PAST_DUE', 'Pago Vencido'), ('SUSPENDED', 'Suspendida'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20)),
                ('billing_frequency', models.CharField(choices=[('MONTHLY', 'Mensual'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=20)),
                ('current_period_start', models.DateField(help_text='Inicio del período actual')),
                ('current_period_end', models.DateField(help_text='Fin del período actual')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='ID de suscripción en Stripe', max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='ID de cliente en Stripe', max_length=100)),
                ('payment_method_last4', models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=4)),
                ('payment_method_brand', models.CharField(blank=True, help_text='Visa, Mastercard, etc.', max_length=20)),
                ('auto_renew', models.BooleanField(default=True, help_text='Renovar automáticamente')),
                ('suspension_date', models.DateField(blank=True, help_text='Fecha de suspensión (para periodo de gracia)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Suscripción de Gimnasio',
                'verbose_name_plural': 'Suscripciones de Gimnasios',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Número de factura único', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Importe base', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='IVA u otros impuestos', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total a pagar', max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('FAILED', 'Fallida'), ('REFUNDED', 'Reembolsada')], default='PENDING', max_length=20)),
                ('issue_date', models.DateField(help_text='Fecha de emisión')),
                ('due_date', models.DateField(help_text='Fecha de vencimiento')),
                ('paid_date', models.DateField(blank=True, help_text='Fecha de pago', null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/')),
                ('description', models.TextField(blank=True, help_text='Concepto de la factura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.franchise')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Básico, Pro, Enterprise', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción del plan')),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Precio mensual en EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, help_text='Precio anual en EUR (opcional, con descuento)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('module_pos', models.BooleanField(default=True, verbose_name='TPV / Point of Sale')),
                ('module_calendar', models.BooleanField(default=True, verbose_name='Calendario de Clases')),
                ('module_marketing', models.BooleanField(default=False, verbose_name='Marketing y Campañas')),
                ('module_reporting', models.BooleanField(default=False, verbose_name='Reportes Avanzados')),
                ('module_client_portal', models.BooleanField(default=True, verbose_name='Portal de Cliente')),
                ('module_public_portal', models.BooleanField(default=False, verbose_name='Portal Público')),
                ('module_automations', models.BooleanField(default=False, verbose_name='Automatizaciones')),
                ('module_routines', models.BooleanField(default=False, verbose_name='Rutinas de Entrenamiento')),
                ('max_members', models.PositiveIntegerField(blank=True, help_text='Máximo de socios activos (vacío = ilimitado)', null=True)),
                ('max_staff', models.PositiveIntegerField(blank=True, help_text='Máximo de usuarios staff (vacío = ilimitado)', null=True)),
                ('max_locations', models.PositiveIntegerField(blank=True, help_text='Máximo de ubicaciones para franquicias (vacío = ilimitado)', null=True)),
                ('is_demo', models.BooleanField(default=False, help_text='Plan demo/prueba gratuito (no se cobra)')),
                ('is_active', models.BooleanField(default=True, help_text='Puede ser asignado a nuevos gimnasios')),
                ('display_order', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('stripe_product_id', models.CharField(blank=True, help_text='ID del producto en Stripe', max_length=100)),
                ('stripe_price_monthly_id', models.CharField(blank=True, help_text='ID del precio mensual en Stripe', max_length=100)),
                ('stripe_price_yearly_id', models.CharField(blank=True, help_text='ID del precio anual en Stripe', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('FAILED', 'Fallido'), ('RETRYING', 'Reintentando'), ('SUCCEEDED', 'Exitoso')], max_length=20)),
                ('failure_reason', models.TextField(blank=True, help_text='Razón del fallo según Stripe')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('next_retry', models.DateTimeField(blank=True, help_text='Próximo reintento programado', null=True)),
                ('franchise_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='saas_billing.franchisesubscription')),
                ('gym_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='saas_billing.gymsubscription')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='saas_billing.invoice')),
            ],
            options={
                'verbose_name': 'Intento de Pago',
                'verbose_name_plural': 'Intentos de Pago',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gym_subscriptions', to='saas_billing.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='franchisesubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='franchise_subscriptions', to='saas_billing.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_GYM', 'Crear Gimnasio'), ('EDIT_GYM', 'Editar Gimnasio'), ('DELETE_GYM', 'Eliminar Gimnasio'), ('CREATE_FRANCHISE', 'Crear Franquicia'), ('EDIT_FRANCHISE', 'Editar Franquicia'), ('CHANGE_PLAN', 'Cambiar Plan'), ('SUSPEND_GYM', 'Suspender Gimnasio'), ('REACTIVATE_GYM', 'Reactivar Gimnasio'), ('GOD_MODE_LOGIN', 'Acceso Modo Dios'), ('UPDATE_BILLING_CONFIG', 'Actualizar Config Facturación'), ('MANUAL_INVOICE', 'Factura Manual'), ('REFUND', 'Reembolso')], max_length=50)),
                ('description', models.TextField(help_text='Descripción detallada de la acción')),
                ('ip_address', models.GenericIPAddressField(help_text='IP del superadmin')),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superadmin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saas_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saas_billing_logs', to='organizations.franchise')),
                ('target_gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saas_billing_logs', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='saas_billin_created_e15981_idx'), models.Index(fields=['superadmin', '-created_at'], name='saas_billin_superad_f73459_idx')],
            },
        ),
    ]
