# Generated by Django 4.2.27 on 2026-01-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='system_logo',
            field=models.ImageField(blank=True, help_text='Logo del sistema para el login del backoffice (marca blanca)', null=True, upload_to='system/branding/'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='system_name',
            field=models.CharField(default='New CRM', help_text='Nombre del sistema para mostrar en login', max_length=100),
        ),
    ]
