# Generated by Django 4.2.27 on 2026-01-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0002_add_system_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='module_gamification',
            field=models.BooleanField(default=False, verbose_name='Gamificación'),
        ),
    ]
