# Generated by Django 4.2.27 on 2026-02-01 19:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0003_add_module_gamification'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='transaction_fee_apply_to_online',
            field=models.BooleanField(default=True, help_text='Cobrar comisión en ventas del portal público y app', verbose_name='Aplicar a pagos online'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='transaction_fee_apply_to_pos',
            field=models.BooleanField(default=True, help_text='Cobrar comisión en ventas del backoffice/TPV', verbose_name='Aplicar a pagos POS'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='transaction_fee_apply_to_recurring',
            field=models.BooleanField(default=True, help_text='Cobrar comisión en renovaciones automáticas de membresías', verbose_name='Aplicar a cobros recurrentes'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='transaction_fee_exclude_cash',
            field=models.BooleanField(default=True, help_text='No cobrar comisión en transacciones en efectivo', verbose_name='Excluir pagos en efectivo'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='transaction_fee_fixed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cantidad fija en EUR por cada transacción', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Comisión fija por transacción'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='transaction_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ej: 2.50 para 2.5%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Porcentaje de comisión'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='transaction_fee_type',
            field=models.CharField(choices=[('NONE', 'Sin comisión'), ('PERCENT', 'Porcentaje'), ('FIXED', 'Cantidad fija'), ('HYBRID', 'Híbrido (% + fijo)')], default='NONE', max_length=10, verbose_name='Tipo de comisión por transacción'),
        ),
    ]
