# Generated by Django 4.2.27 on 2026-02-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0004_add_transaction_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='module_verifactu',
            field=models.BooleanField(default=False, verbose_name='Verifactu (España)'),
        ),
    ]
