# Generated by Django 4.2.27 on 2026-02-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0005_add_module_verifactu'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifactuDeveloperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(default='GymCRM', help_text='Nombre comercial del software de facturación', max_length=100, verbose_name='Nombre del Software')),
                ('software_version', models.CharField(default='1.0.0', help_text='Versión actual del software', max_length=20, verbose_name='Versión')),
                ('developer_country', models.CharField(choices=[('ES', 'España'), ('EU', 'Unión Europea (otro país)'), ('US', 'Estados Unidos'), ('OTHER', 'Otro país')], default='ES', help_text='País donde está registrada la empresa desarrolladora', max_length=10, verbose_name='País del Desarrollador')),
                ('developer_tax_id', models.CharField(blank=True, help_text='Identificador fiscal de la empresa desarrolladora del software', max_length=50, verbose_name='NIF/VAT/EIN del Desarrollador')),
                ('developer_name', models.CharField(blank=True, help_text='Nombre de la empresa desarrolladora', max_length=200, verbose_name='Nombre/Razón Social del Desarrollador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Verifactu - Desarrollador',
                'verbose_name_plural': 'Configuración Verifactu - Desarrollador',
            },
        ),
    ]
