# Generated by Django 4.2.27 on 2026-02-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0006_add_verifactu_developer_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='company_country',
            field=models.CharField(choices=[('ES', 'España'), ('US', 'Estados Unidos (LLC)'), ('OTHER', 'Otro')], default='ES', help_text='País de la empresa', max_length=10),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='company_state',
            field=models.CharField(blank=True, help_text='Estado (para LLC de EEUU, ej: Delaware, Wyoming)', max_length=100),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='company_tax_id_label',
            field=models.CharField(default='CIF/NIF', help_text='Etiqueta para el identificador fiscal (CIF/NIF, EIN, Tax ID, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='company_tax_id',
            field=models.CharField(help_text='CIF/NIF o EIN/Tax ID', max_length=50),
        ),
    ]
