# Generated by Django 5.2.10 on 2026-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0007_add_company_country_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisesubscription',
            name='billing_mode',
            field=models.CharField(choices=[('AUTO', 'Automático (tarjeta)'), ('MANUAL', 'Manual (transferencia/otro)')], default='AUTO', help_text='Manual permite activar sin tarjeta (cobro por transferencia)', max_length=20, verbose_name='Modo de facturación'),
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='billing_mode',
            field=models.CharField(choices=[('AUTO', 'Automático (tarjeta)'), ('MANUAL', 'Manual (transferencia/otro)')], default='AUTO', help_text='Manual permite activar sin tarjeta (cobro por transferencia)', max_length=20, verbose_name='Modo de facturación'),
        ),
    ]
