# Generated by Django 4.2.27 on 2026-02-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_add_checkin_methods_and_geolocation'),
        ('saas_billing', '0008_add_company_and_billing_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='mailrelay_api_key',
            field=models.CharField(blank=True, help_text='Clave API de tu cuenta de Mailrelay', max_length=200, verbose_name='API Key de Mailrelay'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='mailrelay_api_url',
            field=models.URLField(blank=True, default='https://api.mailrelay.com/v1/', help_text='URL base de la API de Mailrelay', verbose_name='URL de API Mailrelay'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='mailrelay_enabled',
            field=models.BooleanField(default=False, help_text='Activa el servicio de email transaccional para gimnasios sin SMTP propio', verbose_name='Mailrelay habilitado'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='mailrelay_noreply_message',
            field=models.CharField(blank=True, default='Este es un email automático, por favor no responda a esta dirección.', help_text='Mensaje que se añade cuando el gimnasio no tiene email configurado', max_length=200, verbose_name='Mensaje no-reply'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='mailrelay_sender_email',
            field=models.EmailField(blank=True, help_text='Email verificado en Mailrelay para enviar (ej: noreply@tudominio.com)', max_length=254, verbose_name='Email remitente Mailrelay'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='mailrelay_sender_name',
            field=models.CharField(blank=True, help_text='Nombre que aparecerá como remitente (ej: Tu Plataforma)', max_length=100, verbose_name='Nombre remitente Mailrelay'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='module_transactional_email',
            field=models.BooleanField(default=False, help_text='Permite usar el servicio de email transaccional de la plataforma (Mailrelay)', verbose_name='Email Transaccional'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='transactional_email_limit_daily',
            field=models.PositiveIntegerField(blank=True, help_text='Máximo de emails transaccionales por día (vacío = ilimitado)', null=True, verbose_name='Límite diario de emails'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='transactional_email_limit_monthly',
            field=models.PositiveIntegerField(blank=True, help_text='Máximo de emails transaccionales por mes (vacío = ilimitado)', null=True, verbose_name='Límite mensual de emails'),
        ),
        migrations.CreateModel(
            name='GymEmailUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Día del registro', verbose_name='Fecha')),
                ('emails_sent', models.PositiveIntegerField(default=0, help_text='Número de emails transaccionales enviados este día', verbose_name='Emails enviados')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_usage', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Uso de Email Transaccional',
                'verbose_name_plural': 'Uso de Emails Transaccionales',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['gym', 'date'], name='saas_billin_gym_id_7d2af0_idx'), models.Index(fields=['date'], name='saas_billin_date_636998_idx')],
                'unique_together': {('gym', 'date')},
            },
        ),
    ]
