# Generated by Django 5.1.15 on 2026-01-11 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_gym_brand_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'Gerente'), ('TRAINER', 'Entrenador'), ('RECEPTIONIST', 'Recepción'), ('CLEANER', 'Limpieza'), ('OTHER', 'Otro')], default='TRAINER', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Breve biografía o notas sobre el empleado')),
                ('color', models.CharField(default='#3b82f6', help_text='Color para el calendario (HEX)', max_length=7)),
                ('pin_code', models.CharField(blank=True, help_text='PIN de 4-6 dígitos para fichar en Tablet', max_length=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='organizations.gym')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('WEB', 'Web Dashboard'), ('TABLET', 'Tablet/Kiosco (PIN)'), ('MOBILE', 'Móvil (GPS)'), ('AUTO', 'Automático')], default='WEB', max_length=20)),
                ('location_info', models.JSONField(blank=True, default=dict, help_text='Snapshot de ubicación o IP')),
                ('is_closed', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Turno de Trabajo',
                'verbose_name_plural': 'Turnos de Trabajo',
                'ordering': ['-start_time'],
            },
        ),
    ]
