# Generated by Django 5.1.15 on 2026-01-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_gym_brand_color'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto para perfil público y actividades', null=True, upload_to='staff/photos/'),
        ),
        migrations.CreateModel(
            name='IncentiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Comisión 10% Bonos, Clase Yoga', max_length=150)),
                ('type', models.CharField(choices=[('SALE_PCT', '% Comisión Venta'), ('SALE_FIXED', 'Fijo por Venta'), ('CLASS_FIXED', 'Fijo por Clase Impartida'), ('CLASS_ATTENDANCE', 'Variable por Asistente a Clase'), ('TASK_FIXED', 'Fijo por Tarea (To-Do)')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, help_text='Porcentaje (0-100) o Cantidad Fija', max_digits=10)),
                ('criteria', models.JSONField(blank=True, default=dict, help_text="Filtros JSON (ej: product_type='membership')")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_rules', to='organizations.gym')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('MONTHLY', 'Mensual (Fijo)'), ('HOURLY', 'Por Hora')], default='MONTHLY', max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Sueldo base mensual o precio/hora base', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_config', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(help_text='Descripción del origen (ej: Venta Bono #123)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_commissions', to='staff.incentiverule')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='staff.staffprofile')),
            ],
        ),
    ]
