# Generated by Django 5.1.15 on 2026-01-11 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffprofile_photo_incentiverule_salaryconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentiverule',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Si se especifica, aplica solo a este empleado. Si no, es global del gym.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incentive_rules', to='staff.staffprofile'),
        ),
    ]
