# Generated by Django 5.1.15 on 2026-01-11 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_gym_brand_color'),
        ('staff', '0003_incentiverule_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('incentive_amount', models.DecimalField(decimal_places=2, default=0, help_text='Recompensa al completar', max_digits=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_role', models.CharField(blank=True, choices=[('MANAGER', 'Gerente'), ('TRAINER', 'Entrenador'), ('RECEPTIONIST', 'Recepción'), ('CLEANER', 'Limpieza'), ('OTHER', 'Otro')], help_text='Para todo un rol', max_length=20)),
                ('is_global', models.BooleanField(default=False, help_text='Visible para todo el staff')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada (Revisar)'), ('VERIFIED', 'Verificada (Pagada)'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Asignación directa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='staff.staffprofile')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='staff.staffprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_tasks', to='organizations.gym')),
            ],
        ),
    ]
