# Generated by Django 5.1.15 on 2026-01-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_stafftask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='method',
            field=models.CharField(choices=[('WEB', 'Web Dashboard'), ('TABLET', 'Kiosco Tablet'), ('MANUAL', 'Manual Manager'), ('MOBILE', 'Móvil (GPS)'), ('AUTO', 'Automático')], default='WEB', max_length=20),
        ),
    ]
