# Generated by Django 4.2.27 on 2026-01-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_gymgoal'),
        ('staff', '0006_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rating', models.DecimalField(decimal_places=2, help_text='Rating mínimo requerido (ej: 4.5)', max_digits=3)),
                ('bonus_type', models.CharField(choices=[('PERCENTAGE', 'Porcentaje del Salario Base'), ('FIXED', 'Cantidad Fija')], default='PERCENTAGE', max_length=20)),
                ('bonus_value', models.DecimalField(decimal_places=2, help_text='Porcentaje (5-15) o Cantidad Fija en euros', max_digits=10)),
                ('level', models.CharField(blank=True, choices=[('BRONZE', 'Bronce (4.0-4.29)'), ('SILVER', 'Plata (4.3-4.49)'), ('GOLD', 'Oro (4.5-4.79)'), ('PLATINUM', 'Platino (4.8-5.0)')], help_text='Nivel de rendimiento asociado', max_length=20, null=True)),
                ('min_reviews', models.IntegerField(default=10, help_text='Mínimo de reviews necesarias para aplicar el incentivo')),
                ('period_days', models.IntegerField(default=30, help_text='Período en días para calcular el promedio (30 = último mes)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_incentives', to='organizations.gym')),
                ('staff', models.ForeignKey(blank=True, help_text='Si se especifica, aplica solo a este empleado. Si no, es global del gym.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_incentives', to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Incentivo por Rating',
                'verbose_name_plural': 'Incentivos por Rating',
                'ordering': ['-min_rating'],
            },
        ),
    ]
