# Generated by Django 4.2.27 on 2026-01-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_ratingincentive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'permissions': [('view_staffkiosk', 'Ver Kiosco de Fichaje'), ('access_staffkiosk', 'Acceder al Kiosco de Fichaje'), ('manage_roles', 'Gestionar Roles y Permisos'), ('view_incentive', 'Ver Incentivos y Comisiones')]},
        ),
    ]
