# Generated by Django 4.2.27 on 2026-01-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_alter_activity_options_alter_room_options_and_more'),
        ('staff', '0008_alter_staffprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentiverule',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='Actividad específica (dejar vacío para cualquier actividad)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentive_rules', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='activity_category',
            field=models.ForeignKey(blank=True, help_text='Categoría completa (dejar vacío si seleccionas actividad específica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentive_rules', to='activities.activitycategory'),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='time_end',
            field=models.TimeField(blank=True, help_text='Hora fin de la franja (ej: 12:00)', null=True),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='time_start',
            field=models.TimeField(blank=True, help_text='Hora inicio de la franja (ej: 06:00)', null=True),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='weekdays',
            field=models.JSONField(blank=True, default=list, help_text="Array de días: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']. Vacío = todos los días"),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='criteria',
            field=models.JSONField(blank=True, default=dict, help_text="Otros filtros JSON (ej: product_type='membership')"),
        ),
    ]
