# Generated by Django 4.2.27 on 2026-01-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_add_activity_time_filters_to_incentives'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incentiverule',
            options={'permissions': [('view_all_incentives', 'Ver Incentivos de Todo el Staff'), ('view_own_incentives', 'Ver Solo Incentivos Propios')]},
        ),
    ]
