# Generated by Django 4.2.27 on 2026-01-30 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0017_gym_auto_calculate_dni_letter_gym_require_unique_dni'),
        ('staff', '0010_add_incentive_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Vacaciones, Baja Médica', max_length=100)),
                ('category', models.CharField(choices=[('VACATION', 'Vacaciones'), ('SICK', 'Enfermedad / Baja Médica'), ('PERSONAL', 'Asuntos Propios'), ('MATERNITY', 'Maternidad / Paternidad'), ('UNPAID', 'Permiso Sin Sueldo'), ('TRAINING', 'Formación'), ('OTHER', 'Otro')], default='VACATION', max_length=20)),
                ('is_paid', models.BooleanField(default=True, help_text='¿Se remunera este tipo de ausencia?')),
                ('requires_approval', models.BooleanField(default=True, help_text='¿Requiere aprobación del manager?')),
                ('requires_documentation', models.BooleanField(default=False, help_text='¿Requiere justificante?')),
                ('deducts_from_balance', models.BooleanField(default=True, help_text='¿Descuenta del saldo de vacaciones?')),
                ('color', models.CharField(default='#3b82f6', help_text='Color en calendario (HEX)', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_types', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Tipo de Ausencia',
                'verbose_name_plural': 'Tipos de Ausencia',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha de inicio')),
                ('end_date', models.DateField(help_text='Fecha de fin (inclusive)')),
                ('working_days', models.DecimalField(decimal_places=1, default=0, help_text='Días laborables solicitados (excluye fines de semana/festivos si aplica)', max_digits=5)),
                ('reason', models.TextField(blank=True, help_text='Motivo o notas de la solicitud')),
                ('documentation', models.FileField(blank=True, help_text='Justificante si es requerido', null=True, upload_to='staff/vacation_docs/')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente de Aprobación'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Motivo del rechazo si aplica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence_type', models.ForeignKey(help_text='Tipo de ausencia', on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='staff.absencetype')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vacation_requests', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Solicitud de Vacaciones',
                'verbose_name_plural': 'Solicitudes de Vacaciones',
                'ordering': ['-created_at'],
                'permissions': [('approve_vacation', 'Puede aprobar solicitudes de vacaciones'), ('view_all_vacations', 'Ver vacaciones de todo el equipo'), ('view_own_vacations', 'Ver solo sus propias vacaciones')],
            },
        ),
        migrations.CreateModel(
            name='VacationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_days_per_year', models.PositiveIntegerField(default=22, help_text='Días de vacaciones base anuales (típico España: 22-30)')),
                ('extra_days_per_year_worked', models.PositiveIntegerField(default=0, help_text='Días extra por cada año de antigüedad (ej: 1 día extra por año)')),
                ('max_seniority_days', models.PositiveIntegerField(default=5, help_text='Máximo de días extra por antigüedad')),
                ('allow_carry_over', models.BooleanField(default=True, help_text='¿Permitir arrastrar días no usados al siguiente año?')),
                ('max_carry_over_days', models.PositiveIntegerField(default=5, help_text='Máximo de días que se pueden arrastrar')),
                ('carry_over_deadline_months', models.PositiveIntegerField(default=3, help_text='Meses para usar los días arrastrados (ej: 3 = hasta marzo)')),
                ('min_advance_days', models.PositiveIntegerField(default=15, help_text='Días mínimos de antelación para solicitar vacaciones')),
                ('min_consecutive_days', models.PositiveIntegerField(default=1, help_text='Mínimo de días consecutivos por solicitud')),
                ('max_consecutive_days', models.PositiveIntegerField(default=21, help_text='Máximo de días consecutivos por solicitud')),
                ('count_weekends', models.BooleanField(default=False, help_text='¿Contar fines de semana como días de vacaciones?')),
                ('exclude_holidays', models.BooleanField(default=True, help_text='¿Excluir festivos del recuento?')),
                ('max_staff_absent_percent', models.PositiveIntegerField(default=30, help_text='% máximo del equipo que puede estar ausente simultáneamente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_policy', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Política de Vacaciones',
                'verbose_name_plural': 'Políticas de Vacaciones',
            },
        ),
        migrations.CreateModel(
            name='BlockedVacationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Temporada Alta, Navidad', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('applies_to_roles', models.JSONField(blank=True, default=list, help_text="Roles afectados. Vacío = todos. Ej: ['TRAINER', 'RECEPTIONIST']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_vacation_periods', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Período Bloqueado',
                'verbose_name_plural': 'Períodos Bloqueados',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffVacationBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Año fiscal')),
                ('days_allocated', models.DecimalField(decimal_places=1, default=0, help_text='Días asignados para el año', max_digits=5)),
                ('days_carried_over', models.DecimalField(decimal_places=1, default=0, help_text='Días arrastrados del año anterior', max_digits=5)),
                ('days_adjustment', models.DecimalField(decimal_places=1, default=0, help_text='Ajustes manuales (+/-)', max_digits=5)),
                ('days_used', models.DecimalField(decimal_places=1, default=0, help_text='Días ya disfrutados', max_digits=5)),
                ('days_pending', models.DecimalField(decimal_places=1, default=0, help_text='Días en solicitudes pendientes de aprobación', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Notas o comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_balances', to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Saldo de Vacaciones',
                'verbose_name_plural': 'Saldos de Vacaciones',
                'ordering': ['-year', 'staff__user__first_name'],
                'unique_together': {('staff', 'year')},
            },
        ),
    ]
