# Generated by Django 5.2.10 on 2026-02-03 10:21

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_add_membership_purchase_controls'),
        ('staff', '0011_add_vacation_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='pin_code',
            field=models.CharField(blank=True, help_text='PIN de 4-6 dígitos para fichar en Tablet (debe ser único en el gimnasio)', max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='invalid_pin', message='El PIN debe contener solo dígitos (4-6 caracteres)', regex='^\\d{4,6}$')]),
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('pin_code__isnull', False), models.Q(('pin_code', ''), _negated=True)), fields=('gym', 'pin_code'), name='unique_pin_per_gym', violation_error_message='Este PIN ya está en uso por otro empleado de este gimnasio.'),
        ),
    ]
