# Generated by Django 5.2.10 on 2026-02-03 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_unique_pin_per_gym'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingCheckinAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('alert_type', models.CharField(choices=[('NO_CHECKIN', 'No fichó entrada'), ('LATE_CHECKIN', 'Fichaje tardío'), ('NO_CHECKOUT', 'No fichó salida'), ('EARLY_CHECKOUT', 'Salida anticipada')], max_length=20)),
                ('expected_time', models.TimeField(blank=True, help_text='Hora esperada según horario', null=True)),
                ('actual_time', models.TimeField(blank=True, help_text='Hora real del fichaje (si aplica)', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='El manager revisó/justificó esta alerta')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notas del manager sobre la resolución')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_checkin_alerts', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_alerts', to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Alerta de Fichaje',
                'verbose_name_plural': 'Alertas de Fichaje',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('staff', 'date', 'alert_type')},
            },
        ),
        migrations.CreateModel(
            name='StaffExpectedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField(help_text='Hora esperada de entrada')),
                ('end_time', models.TimeField(help_text='Hora esperada de salida')),
                ('is_active', models.BooleanField(default=True)),
                ('grace_minutes', models.IntegerField(default=15, help_text='Minutos de tolerancia antes de generar alerta')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_schedules', to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Horario Esperado',
                'verbose_name_plural': 'Horarios Esperados',
                'ordering': ['staff', 'day_of_week'],
                'unique_together': {('staff', 'day_of_week')},
            },
        ),
    ]
