# Generated by Django 5.2.10 on 2026-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_expected_schedule_and_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='checkin_method',
            field=models.CharField(choices=[('ANY', 'Cualquiera disponible'), ('PIN', 'Solo PIN'), ('FACIAL', 'Reconocimiento facial'), ('GEO', 'Geolocalización (móvil)'), ('PHOTO', 'Selfie obligatorio')], default='ANY', help_text='Método requerido para este empleado', max_length=10, verbose_name='Método de fichaje'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkin_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkin_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkin_photo',
            field=models.ImageField(blank=True, help_text='Foto capturada al fichar entrada', null=True, upload_to='staff/checkin_photos/'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkout_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkout_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkout_photo',
            field=models.ImageField(blank=True, help_text='Foto capturada al fichar salida', null=True, upload_to='staff/checkout_photos/'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='facial_match_score',
            field=models.IntegerField(blank=True, help_text='Porcentaje de coincidencia del reconocimiento facial', null=True),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='method',
            field=models.CharField(choices=[('WEB', 'Web Dashboard'), ('TABLET', 'Kiosco Tablet'), ('MANUAL', 'Manual Manager'), ('MOBILE', 'Móvil (GPS)'), ('FACIAL', 'Reconocimiento Facial'), ('AUTO', 'Automático')], default='WEB', max_length=20),
        ),
    ]
