# Generated by Django 5.2.10 on 2026-02-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_add_checkin_methods_and_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='id_document',
            field=models.CharField(blank=True, help_text='DNI, NIE, Pasaporte, etc.', max_length=20, verbose_name='Documento de Identidad'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='show_in_public_schedule',
            field=models.BooleanField(default=True, help_text='Si está activo, su foto y bio se mostrarán en el portal del cliente y la app móvil', verbose_name='Mostrar en horario público'),
        ),
    ]
