# Generated by Django 4.2.27 on 2026-01-15 18:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0007_booking_policy_settings'),
        ('services', '0005_service_color'),
        ('clients', '0009_chatroom_chatmessage'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0004_membershipplan_contract_content_and_more'),
        ('sales', '0002_orderpayment_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre interno del descuento', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción visible para clientes')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Porcentaje (%)'), ('FIXED_AMOUNT', 'Cantidad Fija'), ('FIXED_PRICE', 'Precio Fijo')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Porcentaje (0-100), cantidad fija o precio fijo según el tipo', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('code', models.CharField(blank=True, help_text='Código que los clientes pueden ingresar (ej: VERANO2026)', max_length=50, null=True)),
                ('code_case_sensitive', models.BooleanField(default=False)),
                ('applies_to', models.CharField(choices=[('ALL', 'Todo'), ('MEMBERSHIP', 'Membresías'), ('SERVICE', 'Servicios'), ('PRODUCT', 'Productos'), ('SPECIFIC_ITEMS', 'Items Específicos')], default='ALL', max_length=20)),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de compra para aplicar', max_digits=10)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Límite máximo del descuento en dinero (cap)', max_digits=10, null=True)),
                ('target_type', models.CharField(choices=[('ALL', 'Todos los Clientes'), ('NEW_CLIENTS', 'Solo Clientes Nuevos'), ('INDIVIDUAL', 'Clientes Individuales'), ('GROUP', 'Por Grupo'), ('TAG', 'Por Etiqueta'), ('FIRST_PURCHASE', 'Primera Compra')], default='ALL', max_length=20)),
                ('max_uses_total', models.IntegerField(blank=True, help_text='Número máximo de veces que se puede usar en total', null=True)),
                ('max_uses_per_client', models.IntegerField(default=1, help_text='Número máximo de veces que cada cliente puede usarlo')),
                ('current_uses', models.IntegerField(default=0, help_text='Contador de usos actuales')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('stackable', models.BooleanField(default=False, help_text='¿Se puede combinar con otros descuentos?')),
                ('priority', models.IntegerField(default=0, help_text='Mayor número = mayor prioridad (se aplica primero)')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_apply', models.BooleanField(default=False, help_text='Aplicar automáticamente si el cliente cumple condiciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discounts', to=settings.AUTH_USER_MODEL)),
                ('excludes_discounts', models.ManyToManyField(blank=True, help_text='Descuentos incompatibles con este', related_name='excluded_by', to='discounts.discount')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='organizations.gym')),
                ('specific_memberships', models.ManyToManyField(blank=True, related_name='discounts', to='memberships.membershipplan')),
                ('specific_products', models.ManyToManyField(blank=True, related_name='discounts', to='products.product')),
                ('specific_services', models.ManyToManyField(blank=True, related_name='discounts', to='services.service')),
                ('target_clients', models.ManyToManyField(blank=True, related_name='personal_discounts', to='clients.client')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='group_discounts', to='clients.clientgroup')),
                ('target_tags', models.ManyToManyField(blank=True, related_name='tag_discounts', to='clients.clienttag')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('referrer_credit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Crédito en cuenta para quien refiere', max_digits=10)),
                ('min_referrals_for_bonus', models.IntegerField(default=3, help_text='Mínimo de referidos para obtener bonus adicional')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bonus_discount', models.ForeignKey(blank=True, help_text='Bonus al alcanzar el mínimo de referidos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_programs', to='discounts.discount')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_programs', to='organizations.gym')),
                ('referred_discount', models.ForeignKey(blank=True, help_text='Descuento para el referido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_programs', to='discounts.discount')),
                ('referrer_discount', models.ForeignKey(blank=True, help_text='Descuento para quien refiere', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_programs', to='discounts.discount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('REWARDED', 'Recompensado')], default='PENDING', max_length=20)),
                ('referral_code', models.CharField(max_length=50, unique=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='discounts.referralprogram')),
                ('referred', models.ForeignKey(help_text='Cliente referido', on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='clients.client')),
                ('referrer', models.ForeignKey(help_text='Cliente que refirió', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'referred')},
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=200)),
                ('discount_type', models.CharField(max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code_used', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, help_text='Staff que aplicó el descuento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_discounts', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='clients.client')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.discount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='sales.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['discount', 'client'], name='discounts_d_discoun_962cd4_idx'), models.Index(fields=['created_at'], name='discounts_d_created_416937_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['gym', 'is_active'], name='discounts_d_gym_id_7705dd_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['code'], name='discounts_d_code_3a970a_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['valid_from', 'valid_until'], name='discounts_d_valid_f_3893c8_idx'),
        ),
    ]
