# Generated by Django 5.2.10 on 2026-02-03 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0107_referral_system'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='referral',
            name='invited_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Cuándo se envió la invitación'),
        ),
        migrations.AddField(
            model_name='referral',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_credit_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_email',
            field=models.EmailField(blank=True, help_text='Email del invitado', max_length=254),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_name',
            field=models.CharField(blank=True, help_text='Nombre del invitado', max_length=200),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_reward_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_credit_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_reward_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='registered_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se registró', null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='bonus_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Crédito bonus al alcanzar el mínimo de referidos', max_digits=10),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='current_total_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='max_referrals_per_client',
            field=models.IntegerField(default=0, help_text='Máximo de referidos por cliente (0 = ilimitado)'),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='max_total_referrals',
            field=models.IntegerField(default=0, help_text='Máximo total de referidos del programa (0 = ilimitado)'),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='min_membership_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo de la membresía del referido para activar recompensa', max_digits=10),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='referred_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Crédito en cuenta para el referido (€)', max_digits=10),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='referred_free_days',
            field=models.IntegerField(default=0, help_text='Días gratis de membresía para el referido'),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='referrer_free_days',
            field=models.IntegerField(default=0, help_text='Días gratis de membresía para quien refiere'),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='require_membership_purchase',
            field=models.BooleanField(default=True, help_text='El referido debe comprar una membresía para que se active la recompensa'),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='reward_type',
            field=models.CharField(choices=[('DISCOUNT', 'Descuento'), ('CREDIT', 'Crédito en Cuenta'), ('FREE_DAYS', 'Días Gratis'), ('BOTH', 'Descuento + Crédito')], default='DISCOUNT', help_text='Tipo de recompensa para el programa', max_length=20),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo completó la condición', null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(blank=True, help_text='Cliente referido (una vez registrado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_record', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='rewarded_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se otorgó la recompensa', null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('REGISTERED', 'Registrado'), ('COMPLETED', 'Completado'), ('REWARDED', 'Recompensado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='referralprogram',
            name='referrer_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Crédito en cuenta para quien refiere (€)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code'], name='discounts_r_referra_9f8e90_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status'], name='discounts_r_referre_6b5964_idx'),
        ),
    ]
