# Generated by Django 5.1.15 on 2026-01-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='brand_color',
            field=models.CharField(default='#0f172a', help_text='Color corporativo en Hex (ej: #0f172a)', max_length=7),
        ),
    ]
