# Generated by Django 5.1.15 on 2026-01-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_gym_brand_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gym',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='commercial_name',
            field=models.CharField(blank=True, help_text='Nombre Comercial (Público)', max_length=200),
        ),
        migrations.AddField(
            model_name='gym',
            name='country',
            field=models.CharField(blank=True, default='España', max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='gym',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Razón Social / Nombre de Empresa', max_length=200),
        ),
        migrations.AddField(
            model_name='gym',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='gym_logos/'),
        ),
        migrations.AddField(
            model_name='gym',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gym',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='tax_id',
            field=models.CharField(blank=True, help_text='CIF / NIF', max_length=20),
        ),
        migrations.AddField(
            model_name='gym',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(help_text='Nombre interno/sistema', max_length=200),
        ),
    ]
