# Generated by Django 5.1.15 on 2026-01-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_gym_address_gym_city_gym_commercial_name_gym_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='facebook',
            field=models.URLField(blank=True, help_text='URL completa'),
        ),
        migrations.AddField(
            model_name='gym',
            name='instagram',
            field=models.URLField(blank=True, help_text='URL completa (https://instagram.com/...)'),
        ),
        migrations.AddField(
            model_name='gym',
            name='tiktok',
            field=models.URLField(blank=True, help_text='URL completa'),
        ),
        migrations.AddField(
            model_name='gym',
            name='youtube',
            field=models.URLField(blank=True, help_text='URL completa'),
        ),
    ]
