# Generated by Django 4.2.27 on 2026-01-13 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_gym_facebook_gym_instagram_gym_tiktok_gym_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='franchises_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
