# Generated by Django 4.2.27 on 2026-01-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_franchise_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.TimeField(default='06:00', help_text='Hora de apertura')),
                ('monday_close', models.TimeField(default='22:00', help_text='Hora de cierre')),
                ('tuesday_open', models.TimeField(default='06:00')),
                ('tuesday_close', models.TimeField(default='22:00')),
                ('wednesday_open', models.TimeField(default='06:00')),
                ('wednesday_close', models.TimeField(default='22:00')),
                ('thursday_open', models.TimeField(default='06:00')),
                ('thursday_close', models.TimeField(default='22:00')),
                ('friday_open', models.TimeField(default='06:00')),
                ('friday_close', models.TimeField(default='22:00')),
                ('saturday_open', models.TimeField(default='08:00')),
                ('saturday_close', models.TimeField(default='20:00')),
                ('sunday_open', models.TimeField(default='08:00')),
                ('sunday_close', models.TimeField(default='20:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='organizations.gym')),
            ],
            options={
                'verbose_name_plural': 'Opening Hours',
            },
        ),
        migrations.CreateModel(
            name='GymHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha del festivo')),
                ('name', models.CharField(help_text='Nombre del festivo (ej: Navidad, Año Nuevo)', max_length=100)),
                ('is_closed', models.BooleanField(default=True, help_text='¿Está cerrado todo el día?')),
                ('special_open', models.TimeField(blank=True, help_text='Hora de apertura especial (si abre)', null=True)),
                ('special_close', models.TimeField(blank=True, help_text='Hora de cierre especial', null=True)),
                ('allow_classes', models.BooleanField(default=False, help_text='Permitir clases aunque sea festivo (si se fuerza)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organizations.gym')),
            ],
            options={
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
                'unique_together': {('gym', 'date')},
            },
        ),
    ]
