# Generated by Django 4.2.27 on 2026-01-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_gymopeninghours_gymholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='allow_waitlist',
            field=models.BooleanField(default=True, help_text='Permitir lista de espera cuando las clases están llenas'),
        ),
        migrations.AddField(
            model_name='gym',
            name='max_advance_booking_days',
            field=models.PositiveIntegerField(default=7, help_text='Días máximos de antelación para reservar (0 = sin límite)'),
        ),
        migrations.AddField(
            model_name='gym',
            name='require_active_membership',
            field=models.BooleanField(default=True, help_text='Requerir membresía activa para poder reservar clases'),
        ),
    ]
