# Generated by Django 4.2.27 on 2026-01-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_booking_policy_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='allow_waitlist',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='max_advance_booking_days',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='require_active_membership',
        ),
        migrations.AddField(
            model_name='gym',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', help_text='Idioma principal del gimnasio', max_length=2),
        ),
    ]
