# Generated by Django 4.2.27 on 2026-01-16 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0008_remove_gym_allow_waitlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_members', models.PositiveIntegerField(blank=True, help_text='Número objetivo de socios activos', null=True)),
                ('target_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Facturación objetivo en euros', max_digits=10, null=True)),
                ('period', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='monthly', help_text='Período del objetivo', max_length=20)),
                ('start_date', models.DateField(help_text='Inicio del período del objetivo')),
                ('end_date', models.DateField(help_text='Fin del período del objetivo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el objetivo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Owner que estableció el objetivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Objetivo de Gimnasio',
                'verbose_name_plural': 'Objetivos de Gimnasios',
                'ordering': ['-start_date'],
            },
        ),
    ]
