# Generated by Django 4.2.27 on 2026-01-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_gymgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_portal_enabled', models.BooleanField(default=False, help_text='Activa el portal público para este gimnasio')),
                ('public_slug', models.SlugField(help_text="URL amigable del gimnasio (ej: 'qombo-arganzuela')", max_length=100, unique=True)),
                ('show_schedule', models.BooleanField(default=True, help_text='Permite ver el calendario de clases públicamente', verbose_name='Mostrar Horario')),
                ('show_pricing', models.BooleanField(default=True, help_text='Muestra los planes y tarifas', verbose_name='Mostrar Precios')),
                ('show_services', models.BooleanField(default=False, help_text='Muestra los servicios adicionales', verbose_name='Mostrar Servicios')),
                ('show_shop', models.BooleanField(default=False, help_text='Muestra productos en venta', verbose_name='Mostrar Tienda')),
                ('allow_self_registration', models.BooleanField(default=False, help_text='Los clientes pueden crear su propia cuenta desde el portal público', verbose_name='Permitir Auto-Registro')),
                ('require_email_verification', models.BooleanField(default=True, help_text='Requiere verificación de email al auto-registrarse', verbose_name='Verificar Email')),
                ('require_staff_approval', models.BooleanField(default=False, help_text='El staff debe aprobar manualmente cada nuevo registro', verbose_name='Aprobación Manual')),
                ('allow_online_booking', models.BooleanField(default=False, help_text='Permite reservar clases desde el portal público', verbose_name='Reservas Online')),
                ('booking_requires_login', models.BooleanField(default=True, help_text='Requiere cuenta de cliente para reservar', verbose_name='Login Obligatorio')),
                ('booking_requires_payment', models.BooleanField(default=False, help_text='Requiere método de pago vinculado para reservar', verbose_name='Pago Obligatorio')),
                ('meta_title', models.CharField(blank=True, help_text='Título SEO (aparece en Google)', max_length=60)),
                ('meta_description', models.TextField(blank=True, help_text='Descripción SEO (aparece en Google)', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Imagen de portada para redes sociales (Open Graph)', null=True, upload_to='portal/og_images/')),
                ('allow_embedding', models.BooleanField(default=True, help_text='Permite usar el calendario/precios como iframe en otras webs', verbose_name='Permitir Embeber')),
                ('embed_domains', models.TextField(blank=True, help_text='Dominios permitidos para embeber (uno por línea). Dejar vacío para permitir todos.', verbose_name='Dominios Permitidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(help_text='Configuración del portal público del gimnasio', on_delete=django.db.models.deletion.CASCADE, related_name='public_portal_settings', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Configuración Portal Público',
                'verbose_name_plural': 'Configuraciones Portal Público',
            },
        ),
    ]
