# Generated by Django 4.2.27 on 2026-01-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_publicportalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='allow_cross_booking',
            field=models.BooleanField(default=False, help_text='Permite a los clientes reservar clases en cualquier gimnasio de la franquicia', verbose_name='Permitir reservas cruzadas'),
        ),
    ]
