# Generated by Django 4.2.27 on 2026-01-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_add_franchise_cross_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='smtp_from_email',
            field=models.EmailField(blank=True, help_text='Email remitente (From)', max_length=254),
        ),
        migrations.AddField(
            model_name='gym',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='Servidor SMTP (ej: smtp.gmail.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='gym',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Contraseña SMTP', max_length=255),
        ),
        migrations.AddField(
            model_name='gym',
            name='smtp_port',
            field=models.IntegerField(default=587, help_text='Puerto SMTP (587 para TLS, 465 para SSL)'),
        ),
        migrations.AddField(
            model_name='gym',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Usar SSL'),
        ),
        migrations.AddField(
            model_name='gym',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Usar TLS/STARTTLS'),
        ),
        migrations.AddField(
            model_name='gym',
            name='smtp_username',
            field=models.CharField(blank=True, help_text='Usuario/Email SMTP', max_length=255),
        ),
    ]
