# Generated by Django 4.2.27 on 2026-01-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_gym_smtp_from_email_gym_smtp_host_gym_smtp_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='email_footer',
            field=models.TextField(blank=True, help_text='Texto legal/políticas de privacidad para el pie del email'),
        ),
        migrations.AddField(
            model_name='gym',
            name='email_signature',
            field=models.TextField(blank=True, help_text='Firma HTML que se añade al final de cada email'),
        ),
    ]
