# Generated by Django 4.2.27 on 2026-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_add_email_signature_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='email_signature_logo',
            field=models.ImageField(blank=True, help_text='Logo o imagen para la firma del email', null=True, upload_to='email_signatures/'),
        ),
    ]
