# Generated by Django 4.2.27 on 2026-01-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_add_email_signature_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='allow_booking_with_pending_payment',
            field=models.BooleanField(default=False, help_text='Permite que los clientes con suscripción activa pero pago pendiente puedan hacer reservas', verbose_name='Permitir reservas con pago pendiente'),
        ),
    ]
