# Generated by Django 4.2.27 on 2026-01-25 16:46

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Gym = apps.get_model('organizations', 'Gym')
    for gym in Gym.objects.all():
        if not gym.slug:
            base_slug = slugify(gym.commercial_name or gym.name)
            slug = base_slug
            counter = 1
            
            while Gym.objects.filter(slug=slug).exclude(pk=gym.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            gym.slug = slug
            gym.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_allow_booking_pending_payment'),
    ]

    operations = [
        # Paso 1: Agregar campo sin unique constraint
        migrations.AddField(
            model_name='gym',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable (se genera automáticamente)', max_length=200, unique=False),
        ),
        # Paso 2: Generar slugs para todos los gimnasios existentes
        migrations.RunPython(generate_slugs, reverse_code=migrations.RunPython.noop),
        # Paso 3: Hacer el campo unique
        migrations.AlterField(
            model_name='gym',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable (se genera automáticamente)', max_length=200, unique=True),
        ),
    ]
