# Generated by Django 4.2.27 on 2026-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_gym_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='auto_calculate_dni_letter',
            field=models.BooleanField(default=True, help_text='Calcula automáticamente la letra del DNI español si no se proporciona', verbose_name='Calcular letra del DNI automáticamente'),
        ),
        migrations.AddField(
            model_name='gym',
            name='require_unique_dni',
            field=models.BooleanField(default=False, help_text='No permite registrar dos clientes con el mismo DNI/NIE/documento', verbose_name='Exigir DNI único'),
        ),
    ]
