# Generated by Django 4.2.27 on 2026-02-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_gym_auto_calculate_dni_letter_gym_require_unique_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicportalsettings',
            name='allow_duplicate_membership_purchase',
            field=models.BooleanField(default=True, help_text='Si está desactivado, los clientes con cuota activa no podrán comprar otra', verbose_name='Permitir Compra de Cuota Duplicada'),
        ),
        migrations.AddField(
            model_name='publicportalsettings',
            name='allow_membership_change_at_renewal',
            field=models.BooleanField(default=False, help_text='Permite a los clientes programar un cambio de cuota para cuando finalice la actual', verbose_name='Permitir Cambio de Plan al Renovar'),
        ),
        migrations.AddField(
            model_name='publicportalsettings',
            name='duplicate_membership_message',
            field=models.CharField(blank=True, default="Ya tienes una cuota activa. Si deseas renovarla, ve a 'Mi Cuota' y selecciona 'Renovar'.", help_text='Mensaje que se muestra al cliente cuando intenta comprar otra cuota', max_length=255),
        ),
    ]
