# Generated by Django 5.2.10 on 2026-02-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_add_membership_purchase_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicportalsettings',
            name='referral_program_enabled',
            field=models.BooleanField(default=False, help_text='Permite a los clientes invitar amigos y obtener recompensas', verbose_name='Habilitar Programa de Referidos'),
        ),
        migrations.AddField(
            model_name='publicportalsettings',
            name='referral_share_message',
            field=models.TextField(blank=True, default='¡Únete a mi gimnasio! Usa mi código de referido y ambos obtendremos descuentos.', help_text='Mensaje predeterminado cuando el cliente comparte su código', verbose_name='Mensaje para Compartir'),
        ),
    ]
