# Generated by Django 5.2.10 on 2026-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_referral_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='allowed_checkin_methods',
            field=models.JSONField(blank=True, default=list, help_text='Lista de métodos: PIN, FACIAL, GEO, PHOTO. Vacío = todos permitidos', verbose_name='Métodos de fichaje permitidos'),
        ),
        migrations.AddField(
            model_name='gym',
            name='geofence_radius',
            field=models.IntegerField(default=100, help_text='Distancia máxima permitida para fichar por GPS', verbose_name='Radio de geofence (metros)'),
        ),
        migrations.AddField(
            model_name='gym',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS del gimnasio', max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='gym',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS del gimnasio', max_digits=10, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='gym',
            name='require_checkin_geolocation',
            field=models.BooleanField(default=False, help_text='Valida que el empleado esté dentro del radio del gimnasio', verbose_name='Requerir geolocalización'),
        ),
        migrations.AddField(
            model_name='gym',
            name='require_checkin_photo',
            field=models.BooleanField(default=False, help_text='Obliga a capturar selfie en cada fichaje como evidencia', verbose_name='Requerir foto al fichar'),
        ),
    ]
