# Generated by Django 5.1.15 on 2026-01-11 20:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_gym_brand_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('content_html', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='marketing/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='organizations.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('audience_type', models.CharField(choices=[('ALL_ACTIVE', 'Todos los Activos'), ('ALL_CLIENTS', 'Todos los Clientes'), ('INACTIVE', 'Inactivos/Expirados'), ('STAFF', 'Staff'), ('CUSTOM_TAG', 'Etiqueta Personalizada')], default='ALL_ACTIVE', max_length=50)),
                ('audience_filter_value', models.CharField(blank=True, help_text='Tag name or specific filter ID', max_length=255, null=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SCHEDULED', 'Programada'), ('SENDING', 'Enviando'), ('SENT', 'Enviada'), ('FAILED', 'Fallida')], default='DRAFT', max_length=20)),
                ('sent_count', models.IntegerField(default=0)),
                ('open_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='organizations.gym')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('default_sender_email', models.EmailField(help_text='From address for emails', max_length=254)),
                ('default_sender_name', models.CharField(default='Mi Gimnasio', max_length=255)),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='marketing/logos/')),
                ('footer_text', models.TextField(blank=True, help_text='HTML allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_settings', to='organizations.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='HTML content allowed')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing/popups/')),
                ('target_group', models.CharField(choices=[('CLIENTS', 'Clientes'), ('STAFF', 'Staff'), ('ALL', 'Todos')], default='ALL', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popups', to='organizations.gym')),
            ],
        ),
    ]
