# Generated by Django 5.1.15 on 2026-01-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popup',
            name='target_group',
        ),
        migrations.AddField(
            model_name='popup',
            name='audience_filter_value',
            field=models.CharField(blank=True, help_text='Tag name or specific filter ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='audience_type',
            field=models.CharField(choices=[('ALL_ACTIVE', 'Todos los Activos'), ('ALL_CLIENTS', 'Todos los Clientes'), ('INACTIVE', 'Inactivos/Expirados'), ('STAFF', 'Staff'), ('CUSTOM_TAG', 'Etiqueta Personalizada')], default='ALL_ACTIVE', max_length=50),
        ),
    ]
