# Generated by Django 5.1.15 on 2026-01-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_stripe_customer_id'),
        ('marketing', '0002_remove_popup_target_group_and_more'),
        ('organizations', '0004_gym_facebook_gym_instagram_gym_tiktok_gym_youtube'),
        ('staff', '0005_alter_workshift_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_pipelines', to='organizations.gym')),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('monthly_quota', models.IntegerField(default=0, help_text='Monthly goal (0 = no quota)')),
                ('is_won', models.BooleanField(default=False, help_text="Mark this as the 'Converted' stage")),
                ('is_lost', models.BooleanField(default=False, help_text="Mark this as the 'Lost' stage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='marketing.leadpipeline')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeadCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('WEB', 'Formulario Web'), ('WALKIN', 'Walk-in'), ('REFERRAL', 'Referido'), ('SOCIAL', 'Redes Sociales'), ('ADS', 'Publicidad'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='staff.staffprofile')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_card', to='clients.client')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_cards', to='marketing.leadstage')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadStageAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('FIRST_VISIT', 'Primera Visita'), ('MEMBERSHIP_CREATED', 'Membresía Creada'), ('DAYS_INACTIVE', 'Días Sin Actividad'), ('TRIAL_ENDED', 'Periodo de Prueba Finalizado'), ('ORDER_CREATED', 'Compra Realizada')], max_length=50)),
                ('trigger_value', models.IntegerField(blank=True, help_text='Days for DAYS_INACTIVE trigger', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_stage', models.ForeignKey(help_text='Source stage', on_delete=django.db.models.deletion.CASCADE, related_name='automations_from', to='marketing.leadstage')),
                ('to_stage', models.ForeignKey(help_text='Destination stage', on_delete=django.db.models.deletion.CASCADE, related_name='automations_to', to='marketing.leadstage')),
            ],
            options={
                'verbose_name': 'Lead Automation Rule',
                'verbose_name_plural': 'Lead Automation Rules',
            },
        ),
    ]
