# Generated by Django 4.2.27 on 2026-01-14 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_stripe_customer_id'),
        ('marketing', '0003_leadpipeline_leadstage_leadcard_leadstageautomation'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='priority',
            field=models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Aviso Important'), ('URGENT', 'Urgente')], default='INFO', max_length=20),
        ),
        migrations.AddField(
            model_name='popup',
            name='target_client',
            field=models.ForeignKey(blank=True, help_text='Si se selecciona, este popup solo se mostrará a este cliente específico', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_popups', to='clients.client'),
        ),
        migrations.CreateModel(
            name='PopupRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_popups', to='clients.client')),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='marketing.popup')),
            ],
            options={
                'unique_together': {('popup', 'client')},
            },
        ),
    ]
