# Generated by Django 4.2.27 on 2026-01-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_popup_enhancements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingsettings',
            name='smtp_password',
        ),
        migrations.AddField(
            model_name='marketingsettings',
            name='_smtp_password_encrypted',
            field=models.CharField(blank=True, db_column='smtp_password', max_length=512),
        ),
    ]
