# Generated by Django 4.2.27 on 2026-01-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auditlog'),
        ('clients', '0012_clientmembership_current_period_end_and_more'),
        ('organizations', '0009_gymgoal'),
        ('marketing', '0005_remove_marketingsettings_smtp_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Secuencia Bienvenida Nuevos', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_event', models.CharField(choices=[('LEAD_CREATED', 'Lead Creado'), ('MEMBERSHIP_CREATED', 'Membresía Creada'), ('TRIAL_STARTED', 'Prueba Iniciada'), ('FIRST_VISIT', 'Primera Visita'), ('INACTIVE_DAYS', 'Días Sin Actividad')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_workflows', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Email Workflow',
                'verbose_name_plural': 'Email Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailWorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'En Progreso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_executions', to='clients.client')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Orden de ejecución')),
                ('delay_days', models.IntegerField(default=0, help_text='Días después del trigger o paso anterior')),
                ('subject', models.CharField(max_length=255)),
                ('content_html', models.TextField(blank=True, help_text='HTML del email si no usa template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.emailtemplate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='marketing.emailworkflow')),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('last_positive_event', models.DateTimeField(blank=True, null=True)),
                ('last_negative_event', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_score', to='clients.client')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='RetentionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('NO_ATTENDANCE', 'Sin Asistencia'), ('MEMBERSHIP_EXPIRING', 'Membresía Por Expirar'), ('LOW_CLASS_BOOKING', 'Pocas Reservas'), ('PAYMENT_FAILED', 'Fallo en Pago'), ('HIGH_CANCELLATION_RATE', 'Muchas Cancelaciones')], max_length=50)),
                ('days_threshold', models.IntegerField(help_text='Ej: 14 días sin asistencia')),
                ('risk_score', models.IntegerField(default=50, help_text='Score de riesgo 0-100')),
                ('auto_assign_to_staff', models.BooleanField(default=False)),
                ('send_notification', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_rules', to='organizations.gym')),
                ('start_workflow', models.ForeignKey(blank=True, help_text='Workflow a iniciar automáticamente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.emailworkflow')),
            ],
            options={
                'verbose_name': 'Retention Rule',
                'verbose_name_plural': 'Retention Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('NO_ATTENDANCE', 'Sin Asistencia'), ('MEMBERSHIP_EXPIRING', 'Membresía Por Expirar'), ('LOW_CLASS_BOOKING', 'Pocas Reservas'), ('PAYMENT_FAILED', 'Fallo en Pago'), ('HIGH_CANCELLATION_RATE', 'Muchas Cancelaciones')], max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('IN_PROGRESS', 'En Progreso'), ('RESOLVED', 'Resuelta'), ('DISMISSED', 'Descartada')], default='OPEN', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('days_inactive', models.IntegerField(blank=True, null=True)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100, donde 100 es alto riesgo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_retention_alerts', to='staff.staffprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_alerts', to='clients.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_alerts', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Retention Alert',
                'verbose_name_plural': 'Retention Alerts',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Puntos por visita', max_length=200)),
                ('event_type', models.CharField(choices=[('EMAIL_OPENED', 'Email Abierto'), ('EMAIL_CLICKED', 'Link en Email Clicado'), ('FORM_SUBMITTED', 'Formulario Enviado'), ('VISIT_REGISTERED', 'Visita Registrada'), ('CLASS_BOOKED', 'Clase Reservada'), ('RESPONDED_MESSAGE', 'Respondió Mensaje'), ('DAYS_NO_RESPONSE', 'Días Sin Respuesta'), ('PURCHASE_MADE', 'Compra Realizada')], max_length=50)),
                ('points', models.IntegerField(help_text='Puede ser negativo para penalizaciones')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Lead Scoring Rule',
                'verbose_name_plural': 'Lead Scoring Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadScoringAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_score', models.IntegerField(help_text='Score mínimo para activar')),
                ('max_score', models.IntegerField(blank=True, help_text='Score máximo (dejar vacío para ilimitado)', null=True)),
                ('action_type', models.CharField(choices=[('MOVE_TO_STAGE', 'Mover a Etapa'), ('ASSIGN_TO_STAFF', 'Asignar a Vendedor'), ('SEND_NOTIFICATION', 'Enviar Notificación'), ('START_WORKFLOW', 'Iniciar Workflow')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_automations', to='organizations.gym')),
                ('target_staff', models.ForeignKey(blank=True, help_text='Para acción ASSIGN_TO_STAFF', null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
                ('target_stage', models.ForeignKey(blank=True, help_text='Para acción MOVE_TO_STAGE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.leadstage')),
                ('target_workflow', models.ForeignKey(blank=True, help_text='Para acción START_WORKFLOW', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.emailworkflow')),
            ],
            options={
                'verbose_name': 'Lead Scoring Automation',
                'verbose_name_plural': 'Lead Scoring Automations',
                'ordering': ['-min_score'],
            },
        ),
        migrations.CreateModel(
            name='LeadScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketing.leadscore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailWorkflowStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(help_text='Cuándo debía enviarse')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='marketing.emailworkflowexecution')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketing.emailworkflowstep')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='emailworkflowexecution',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_executions', to='marketing.emailworkflowstep'),
        ),
        migrations.AddField(
            model_name='emailworkflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='marketing.emailworkflow'),
        ),
        migrations.AlterUniqueTogether(
            name='emailworkflowexecution',
            unique_together={('workflow', 'client')},
        ),
    ]
