# Generated by Django 4.2.27 on 2026-01-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auditlog'),
        ('marketing', '0006_emailworkflow_emailworkflowexecution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionrule',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='Staff al que asignar automáticamente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile'),
        ),
    ]
