# Generated by Django 4.2.27 on 2026-01-17 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_gymgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0012_clientmembership_current_period_end_and_more'),
        ('marketing', '0007_retentionrule_assigned_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título interno (no se muestra al cliente)', max_length=255)),
                ('position', models.CharField(choices=[('HERO_CAROUSEL', 'Hero Carousel (Home)'), ('STICKY_FOOTER', 'Banner Inferior Fijo'), ('INLINE_MIDDLE', 'Banner Intermedio'), ('STORIES', 'Stories Verticales')], default='HERO_CAROUSEL', help_text='Ubicación del anuncio en la app', max_length=50)),
                ('ad_type', models.CharField(choices=[('INTERNAL_PROMO', 'Promoción Interna'), ('SPONSOR', 'Sponsor/Partner'), ('CROSS_SELL', 'Cross-selling'), ('EDUCATIONAL', 'Contenido Educativo')], default='INTERNAL_PROMO', max_length=50)),
                ('image_desktop', models.ImageField(help_text='1080x600px recomendado para carousel hero', upload_to='marketing/advertisements/desktop/')),
                ('image_mobile', models.ImageField(blank=True, help_text='Si está vacío, se usa image_desktop', null=True, upload_to='marketing/advertisements/mobile/')),
                ('video_url', models.URLField(blank=True, help_text='URL de video (opcional)', null=True)),
                ('cta_text', models.CharField(blank=True, help_text="Texto del botón (ej: '¡Reserva Ahora!')", max_length=100)),
                ('cta_action', models.CharField(choices=[('NONE', 'Sin acción'), ('BOOK_CLASS', 'Reservar Clase'), ('VIEW_CATALOG', 'Ver Catálogo'), ('EXTERNAL_URL', 'URL Externa'), ('VIEW_PROMO', 'Ver Promoción')], default='NONE', max_length=50)),
                ('cta_url', models.CharField(blank=True, help_text='URL o parámetro según la acción (ej: clase_id, producto_id, url externa)', max_length=500)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Dejar vacío para indefinido', null=True)),
                ('priority', models.IntegerField(default=1, help_text='Orden en carrusel (menor = primero)')),
                ('duration_seconds', models.IntegerField(default=5, help_text='Segundos que se muestra en carrusel')),
                ('is_collapsible', models.BooleanField(default=True, help_text='Permitir cerrar/ocultar (para sticky footer)')),
                ('is_active', models.BooleanField(default=True)),
                ('impressions', models.IntegerField(default=0, help_text='Número de veces mostrado')),
                ('clicks', models.IntegerField(default=0, help_text='Número de clicks en CTA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advertisements', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='organizations.gym')),
                ('target_gyms', models.ManyToManyField(blank=True, help_text='Dejar vacío para todos los gimnasios de la franquicia', related_name='targeted_ads', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Anuncio Publicitario',
                'verbose_name_plural': 'Anuncios Publicitarios',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.BooleanField(default=False)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_logs', to='marketing.advertisement')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
            options={
                'indexes': [models.Index(fields=['advertisement', 'timestamp'], name='marketing_a_adverti_4d76a8_idx')],
            },
        ),
    ]
