# Generated by Django 4.2.27 on 2026-01-18 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_gymgoal'),
        ('marketing', '0008_advertisement_advertisementimpression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailworkflow',
            name='trigger_event',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Creado'), ('MEMBERSHIP_CREATED', 'Membresía Creada'), ('TRIAL_STARTED', 'Prueba Iniciada'), ('FIRST_VISIT', 'Primera Visita'), ('INACTIVE_DAYS', 'Días Sin Actividad'), ('CLASS_BOOKED', 'Clase Reservada'), ('CLASS_CANCELLED', 'Clase Cancelada'), ('WAITLIST_JOINED', 'Añadido a Lista de Espera'), ('WAITLIST_SPOT_AVAILABLE', 'Plaza Disponible'), ('WAITLIST_PROMOTED', 'Promovido a Clase'), ('CLASS_REMINDER_24H', 'Recordatorio 24h Antes'), ('CLASS_REMINDER_2H', 'Recordatorio 2h Antes')], max_length=50),
        ),
        migrations.CreateModel(
            name='ClassNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_booking_confirmation', models.BooleanField(default=True, verbose_name='Email: Confirmación de reserva')),
                ('email_cancellation_confirmation', models.BooleanField(default=True, verbose_name='Email: Confirmación de cancelación')),
                ('email_waitlist_joined', models.BooleanField(default=True, verbose_name='Email: Añadido a lista de espera')),
                ('email_spot_available', models.BooleanField(default=True, verbose_name='Email: Plaza disponible')),
                ('email_reminder_24h', models.BooleanField(default=True, verbose_name='Email: Recordatorio 24h')),
                ('email_reminder_2h', models.BooleanField(default=False, verbose_name='Email: Recordatorio 2h')),
                ('popup_booking_confirmation', models.BooleanField(default=True, verbose_name='Popup: Confirmación de reserva')),
                ('popup_cancellation_confirmation', models.BooleanField(default=True, verbose_name='Popup: Confirmación de cancelación')),
                ('popup_waitlist_joined', models.BooleanField(default=True, verbose_name='Popup: Añadido a lista de espera')),
                ('popup_spot_available', models.BooleanField(default=True, verbose_name='Popup: Plaza disponible')),
                ('popup_promoted', models.BooleanField(default=True, verbose_name='Popup: Promovido a clase')),
                ('waitlist_broadcast_count', models.IntegerField(default=3, help_text='Cuántas personas notificar simultáneamente cuando se libera una plaza', verbose_name='Notificar a X personas (Broadcast)')),
                ('waitlist_claim_timeout_minutes', models.IntegerField(default=15, help_text='Minutos que tiene el cliente para confirmar la plaza', verbose_name='Tiempo para reclamar (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_notification_settings', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones de Clases',
                'verbose_name_plural': 'Configuraciones de Notificaciones de Clases',
            },
        ),
    ]
