# Generated by Django 4.2.27 on 2026-01-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_class_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='target_screens',
            field=models.JSONField(blank=True, default=list, help_text="Lista de pantallas donde mostrar el anuncio. Vacío = todas las pantallas. Ej: ['HOME', 'CLASS_CATALOG']"),
        ),
    ]
