# Generated by Django 4.2.27 on 2026-01-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_add_target_screens_to_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='audience_filter_value',
            field=models.CharField(blank=True, help_text='Tag o filtro específico según tipo de audiencia', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='audience_type',
            field=models.CharField(choices=[('ALL_ACTIVE', 'Todos los Activos'), ('ALL_CLIENTS', 'Todos los Clientes'), ('INACTIVE', 'Inactivos/Expirados'), ('STAFF', 'Staff'), ('CUSTOM_TAG', 'Etiqueta Personalizada')], default='ALL_ACTIVE', help_text='Tipo de audiencia objetivo', max_length=50),
        ),
    ]
