# Generated by Django 4.2.27 on 2026-01-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_color'),
        ('memberships', '0101_remove_membershipplan_plan_gym_active_idx_and_more'),
        ('marketing', '0011_add_audience_to_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstage',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la etapa'),
        ),
        migrations.AddField(
            model_name='leadstage',
            name='required_plans',
            field=models.ManyToManyField(blank=True, help_text='Planes de membresía asociados a esta etapa', related_name='lead_stages', to='memberships.membershipplan'),
        ),
        migrations.AddField(
            model_name='leadstage',
            name='required_services',
            field=models.ManyToManyField(blank=True, help_text='Servicios que debe contratar el lead en esta etapa', related_name='lead_stages', to='services.service'),
        ),
    ]
