# Generated by Django 4.2.27 on 2026-01-30 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_add_stage_services_plans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadstageautomation',
            options={'ordering': ['-priority', 'from_stage__order'], 'verbose_name': 'Regla de Automatización', 'verbose_name_plural': 'Reglas de Automatización'},
        ),
        migrations.RemoveField(
            model_name='leadstageautomation',
            name='trigger_value',
        ),
        migrations.AddField(
            model_name='leadstageautomation',
            name='action_type',
            field=models.CharField(choices=[('MOVE_STAGE', 'Mover a otra fase'), ('SEND_EMAIL', 'Enviar email'), ('CREATE_TASK', 'Crear tarea para comercial'), ('NOTIFY_STAFF', 'Notificar al equipo')], default='MOVE_STAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='leadstageautomation',
            name='email_template',
            field=models.ForeignKey(blank=True, help_text='Plantilla de email a enviar (si la acción es SEND_EMAIL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_automations', to='marketing.emailtemplate'),
        ),
        migrations.AddField(
            model_name='leadstageautomation',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre descriptivo de la regla', max_length=100),
        ),
        migrations.AddField(
            model_name='leadstageautomation',
            name='notify_message',
            field=models.TextField(blank=True, help_text='Mensaje de notificación (si la acción es NOTIFY_STAFF)'),
        ),
        migrations.AddField(
            model_name='leadstageautomation',
            name='priority',
            field=models.IntegerField(default=0, help_text='Mayor prioridad se ejecuta primero'),
        ),
        migrations.AddField(
            model_name='leadstageautomation',
            name='trigger_days',
            field=models.IntegerField(default=0, help_text='Días para triggers basados en tiempo (0 = inmediato)'),
        ),
        migrations.AddField(
            model_name='leadstageautomation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leadstageautomation',
            name='from_stage',
            field=models.ForeignKey(help_text='Fase origen (donde está el lead)', on_delete=django.db.models.deletion.CASCADE, related_name='automations_from', to='marketing.leadstage'),
        ),
        migrations.AlterField(
            model_name='leadstageautomation',
            name='to_stage',
            field=models.ForeignKey(blank=True, help_text='Fase destino (a donde mover el lead)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automations_to', to='marketing.leadstage'),
        ),
        migrations.AlterField(
            model_name='leadstageautomation',
            name='trigger_type',
            field=models.CharField(choices=[('FIRST_VISIT', 'Primera Visita Realizada'), ('MEMBERSHIP_CREATED', 'Membresía Contratada'), ('ORDER_CREATED', 'Compra Realizada'), ('SERVICE_BOOKED', 'Servicio Reservado'), ('TRIAL_STARTED', 'Prueba Iniciada'), ('DAYS_IN_STAGE', 'Días en esta Fase (timeout)'), ('DAYS_NO_RESPONSE', 'Días Sin Respuesta'), ('DAYS_NO_PURCHASE', 'Días Sin Compra'), ('DAYS_NO_VISIT', 'Días Sin Visita'), ('TRIAL_ENDED', 'Periodo de Prueba Finalizado'), ('DAYS_INACTIVE', 'Días Sin Actividad General')], max_length=50),
        ),
    ]
