# Generated by Django 4.2.27 on 2026-02-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_add_vacation_system'),
        ('organizations', '0018_add_membership_purchase_controls'),
        ('marketing', '0013_improve_automation_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcard',
            name='source',
            field=models.CharField(choices=[('WEB', 'Formulario Web'), ('WALKIN', 'Walk-in'), ('REFERRAL', 'Referido'), ('SOCIAL', 'Redes Sociales'), ('ADS', 'Publicidad'), ('FACEBOOK', 'Facebook Lead Ads'), ('INSTAGRAM', 'Instagram Lead Ads'), ('GOOGLE', 'Google Ads'), ('PHONE', 'Llamada Telefónica'), ('EMAIL', 'Email'), ('EVENT', 'Evento/Feria'), ('PARTNER', 'Partner/Colaborador'), ('OTHER', 'Otro')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='MetaLeadIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, help_text='Meta App ID', max_length=100)),
                ('app_secret', models.CharField(blank=True, help_text='Meta App Secret (encriptado)', max_length=255)),
                ('access_token', models.TextField(blank=True, help_text='Page Access Token (long-lived)')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('page_id', models.CharField(blank=True, help_text='Facebook Page ID', max_length=100)),
                ('page_name', models.CharField(blank=True, max_length=255)),
                ('instagram_business_account_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('auto_create_lead', models.BooleanField(default=True, help_text='Crear lead automáticamente al recibir')),
                ('webhook_verify_token', models.CharField(blank=True, help_text='Token de verificación del webhook', max_length=100)),
                ('webhook_url', models.CharField(blank=True, help_text='URL del webhook (auto-generada)', max_length=500)),
                ('leads_received', models.IntegerField(default=0)),
                ('last_lead_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_stage', models.ForeignKey(blank=True, help_text='Etapa inicial para leads de Meta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.leadstage')),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_integration', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Meta Lead Integration',
                'verbose_name_plural': 'Meta Lead Integrations',
            },
        ),
        migrations.CreateModel(
            name='MetaLeadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=100, unique=True)),
                ('form_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('field_mapping', models.JSONField(blank=True, default=dict, help_text='Mapeo de campos del formulario Meta a campos del lead')),
                ('leads_received', models.IntegerField(default=0)),
                ('last_lead_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assign_to', models.ForeignKey(blank=True, help_text='Asignar automáticamente a este vendedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_forms', to='marketing.metaleadintegration')),
                ('target_stage', models.ForeignKey(blank=True, help_text='Etapa específica para este formulario (override default)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.leadstage')),
            ],
            options={
                'verbose_name': 'Meta Lead Form',
                'verbose_name_plural': 'Meta Lead Forms',
            },
        ),
        migrations.CreateModel(
            name='MetaLeadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadgen_id', models.CharField(help_text='Meta Lead ID', max_length=100, unique=True)),
                ('ad_id', models.CharField(blank=True, max_length=100)),
                ('ad_name', models.CharField(blank=True, max_length=255)),
                ('campaign_id', models.CharField(blank=True, max_length=100)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSED', 'Procesado'), ('ERROR', 'Error'), ('DUPLICATE', 'Duplicado')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('platform', models.CharField(default='facebook', help_text='facebook or instagram', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='marketing.metaleadform')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_entries', to='marketing.metaleadintegration')),
                ('lead_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_entries', to='marketing.leadcard')),
            ],
            options={
                'verbose_name': 'Meta Lead Entry',
                'verbose_name_plural': 'Meta Lead Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_previous_stage', models.DurationField(blank=True, help_text='Tiempo que estuvo en la etapa anterior', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
                ('changed_by_automation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.leadstageautomation')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='marketing.leadstage')),
                ('lead_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='marketing.leadcard')),
                ('to_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='marketing.leadstage')),
            ],
            options={
                'verbose_name': 'Lead Stage History',
                'verbose_name_plural': 'Lead Stage Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadDistributionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('ROUND_ROBIN', 'Round Robin (rotación)'), ('LOAD_BALANCED', 'Balanceado por Carga'), ('RANDOM', 'Aleatorio'), ('FIXED', 'Asignación Fija')], default='ROUND_ROBIN', max_length=20)),
                ('source_filter', models.CharField(blank=True, help_text='Solo aplicar a leads de esta fuente (vacío = todas)', max_length=30)),
                ('current_index', models.IntegerField(default=0)),
                ('max_leads_per_day', models.IntegerField(default=0, help_text='Máximo leads por vendedor por día (0 = sin límite)')),
                ('max_active_leads', models.IntegerField(default=0, help_text='Máximo leads activos por vendedor (0 = sin límite)')),
                ('notify_on_assignment', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Mayor prioridad se evalúa primero')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_distribution_rules', to='organizations.gym')),
                ('staff_members', models.ManyToManyField(help_text='Vendedores que participan en la distribución', related_name='distribution_rules', to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Lead Distribution Rule',
                'verbose_name_plural': 'Lead Distribution Rules',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('AUTO', 'Automática'), ('MANUAL', 'Manual'), ('REASSIGN', 'Reasignación')], default='MANUAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to='staff.staffprofile')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
                ('lead_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='marketing.leadcard')),
                ('rule', models.ForeignKey(blank=True, help_text='Regla que realizó la asignación automática', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.leaddistributionrule')),
            ],
            options={
                'verbose_name': 'Lead Assignment Log',
                'verbose_name_plural': 'Lead Assignment Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
