# Generated by Django 4.2.27 on 2026-02-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_add_meta_integration_lead_distribution_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='display_frequency',
            field=models.CharField(choices=[('ONCE', 'Solo una vez (cuando marque Entendido)'), ('EVERY_SESSION', 'Cada vez que abra la app'), ('DAILY', 'Una vez al día'), ('WEEKLY', 'Una vez por semana')], default='ONCE', help_text='Controla cuántas veces se muestra el popup a cada usuario', max_length=20, verbose_name='Frecuencia de visualización'),
        ),
        migrations.AddField(
            model_name='popupread',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated each time popup is shown again'),
        ),
        migrations.AddField(
            model_name='popupread',
            name='times_seen',
            field=models.PositiveIntegerField(default=1, help_text='How many times user has seen this popup'),
        ),
    ]
