# Generated by Django 5.2.10 on 2026-02-01 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0106_add_health_records'),
        ('marketing', '0015_add_popup_display_frequency'),
        ('organizations', '0018_add_membership_purchase_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='audience_type',
            field=models.CharField(choices=[('ALL_ACTIVE', 'Todos los Activos'), ('ALL_CLIENTS', 'Todos los Clientes'), ('INACTIVE', 'Inactivos/Expirados'), ('STAFF', 'Staff'), ('CUSTOM_TAG', 'Etiqueta Personalizada'), ('SAVED_AUDIENCE', 'Audiencia Guardada')], default='ALL_ACTIVE', help_text='Tipo de audiencia objetivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='audience_type',
            field=models.CharField(choices=[('ALL_ACTIVE', 'Todos los Activos'), ('ALL_CLIENTS', 'Todos los Clientes'), ('INACTIVE', 'Inactivos/Expirados'), ('STAFF', 'Staff'), ('CUSTOM_TAG', 'Etiqueta Personalizada'), ('SAVED_AUDIENCE', 'Audiencia Guardada')], default='ALL_ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='popup',
            name='audience_type',
            field=models.CharField(choices=[('ALL_ACTIVE', 'Todos los Activos'), ('ALL_CLIENTS', 'Todos los Clientes'), ('INACTIVE', 'Inactivos/Expirados'), ('STAFF', 'Staff'), ('CUSTOM_TAG', 'Etiqueta Personalizada'), ('SAVED_AUDIENCE', 'Audiencia Guardada')], default='ALL_ACTIVE', max_length=50),
        ),
        migrations.CreateModel(
            name='SavedAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('audience_type', models.CharField(choices=[('DYNAMIC', 'Dinámica (filtros)'), ('STATIC', 'Estática (lista fija)'), ('MIXED', 'Mixta (filtros + exclusiones)')], default='DYNAMIC', max_length=20, verbose_name='Tipo de audiencia')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filtros para audiencia dinámica: {status, gender, age_min, age_max, membership_plan, tags, etc.}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_cached_count', models.IntegerField(db_column='cached_count', default=0)),
                ('_count_updated_at', models.DateTimeField(blank=True, db_column='count_updated_at', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audiences', to=settings.AUTH_USER_MODEL)),
                ('excluded_members', models.ManyToManyField(blank=True, related_name='excluded_from_audiences', to='clients.client', verbose_name='Clientes excluidos')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_audiences', to='organizations.gym')),
                ('static_members', models.ManyToManyField(blank=True, related_name='static_audiences', to='clients.client', verbose_name='Miembros estáticos')),
            ],
            options={
                'verbose_name': 'Audiencia guardada',
                'verbose_name_plural': 'Audiencias guardadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='saved_audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='marketing.savedaudience', verbose_name='Audiencia guardada'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='saved_audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.savedaudience', verbose_name='Audiencia guardada'),
        ),
        migrations.AddField(
            model_name='popup',
            name='saved_audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popups', to='marketing.savedaudience', verbose_name='Audiencia guardada'),
        ),
    ]
