# Generated by Django 5.1.15 on 2026-01-11 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('finance', '0001_initial'),
        ('organizations', '0002_gym_brand_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Duración (min)')),
                ('max_attendees', models.PositiveIntegerField(default=1, verbose_name='Asistentes Máximos')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('price_strategy', models.CharField(choices=[('TAX_INCLUDED', 'Impuestos Incluidos'), ('TAX_EXCLUDED', 'Impuestos Excluidos')], default='TAX_INCLUDED', max_length=20, verbose_name='Estrategia de Precio')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activitycategory')),
                ('default_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.room')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organizations.gym')),
                ('tax_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.taxrate')),
            ],
        ),
    ]
