# Generated by Django 5.1.15 on 2026-01-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_tax_rate_servicecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si se desactiva, no aparecerá en el punto de venta.', verbose_name='Activo (Visible en POS)'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_visible_online',
            field=models.BooleanField(default=False, help_text='Si se activa, los clientes podrán comprarlo desde la App/Web.', verbose_name='Venta Online (App/Web)'),
        ),
    ]
