# Generated by Django 5.1.15 on 2026-01-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_schedulerule_activitysession'),
        ('clients', '0005_clientsale_staff_clientvisit_staff'),
        ('organizations', '0002_gym_brand_color'),
        ('sales', '0001_initial'),
        ('services', '0003_service_is_active_service_is_visible_online'),
        ('staff', '0005_alter_workshift_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fin')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmada'), ('PENDING', 'Pendiente'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada'), ('NOSHOW', 'No Show')], default='CONFIRMED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='organizations.gym')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_link', to='sales.order')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.room')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
