# Generated by Django 5.1.15 on 2026-01-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.CharField(default='#8B5CF6', help_text='Código HEX (ej: #8B5CF6)', max_length=7, verbose_name='Color en Calendario'),
        ),
    ]
