# Generated by Django 4.2.27 on 2026-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_add_new_client_only_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='eligibility_badge_text',
            field=models.CharField(blank=True, default='', help_text="Badge promocional (ej: '🎁 Solo Nuevos', '⭐ VIP')", max_length=30, verbose_name='Texto del Badge'),
        ),
        migrations.AddField(
            model_name='service',
            name='eligibility_criteria',
            field=models.CharField(choices=[('NONE', 'Sin restricción (disponible para todos)'), ('NEVER_HAD_MEMBERSHIP', 'Solo clientes que NUNCA han tenido membresía'), ('NEVER_BOUGHT_THIS', 'Solo clientes que NUNCA han comprado este servicio'), ('HAS_BOUGHT_THIS', 'Solo clientes que YA han comprado este servicio (fidelización)'), ('REGISTERED_RECENTLY', 'Solo registrados recientemente'), ('INACTIVE_PERIOD', 'Solo clientes inactivos (re-captación)'), ('NO_ACTIVE_MEMBERSHIP', 'Solo clientes SIN membresía activa actualmente'), ('HAS_ACTIVE_MEMBERSHIP', 'Solo clientes CON membresía activa (upgrade/complemento)')], default='NONE', help_text='Define quién puede ver/comprar este servicio', max_length=30, verbose_name='Criterio de Elegibilidad'),
        ),
        migrations.AddField(
            model_name='service',
            name='eligibility_days_threshold',
            field=models.PositiveIntegerField(default=30, help_text="Para 'Registrado recientemente': días. Para 'Inactivos': meses.", verbose_name='Umbral de Días/Meses'),
        ),
        migrations.AddField(
            model_name='service',
            name='visibility_for_ineligible',
            field=models.CharField(choices=[('HIDE', 'Ocultar completamente'), ('SHOW_LOCKED', 'Mostrar bloqueado (genera interés)')], default='HIDE', help_text='Qué hacer con el servicio cuando el cliente no cumple el criterio', max_length=15, verbose_name='Visibilidad para No Elegibles'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_new_client_only',
            field=models.BooleanField(default=False, verbose_name='Solo para Nuevos Clientes (legacy)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='new_client_badge_text',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='new_client_criteria',
            field=models.CharField(blank=True, default='NEVER_HAD_MEMBERSHIP', max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='new_client_days_threshold',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
