# Generated by Django 5.1.15 on 2026-01-11 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientmembership_clientsale_clientvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='clients.clientgroup'),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('VIP', 'VIP (Dorado)'), ('WARNING', 'Alerta Amarilla'), ('DANGER', 'Alerta Roja')], default='NORMAL', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Contrato de Adhesión', max_length=200)),
                ('file', models.FileField(upload_to='clients/documents/')),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
            ],
        ),
    ]
