# Generated by Django 5.1.15 on 2026-01-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientgroup_parent_clientnote_type_clientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='access_code',
            field=models.CharField(blank=True, help_text='Código de acceso o PIN simplificado', max_length=50),
        ),
    ]
