# Generated by Django 5.1.15 on 2026-01-11 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_access_code'),
        ('staff', '0003_incentiverule_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsale',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Vendedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='clientvisit',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Staff que atendió/impartió', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_visits', to='staff.staffprofile'),
        ),
    ]
