# Generated by Django 5.1.15 on 2026-01-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientsale_staff_clientvisit_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='ID de cliente en Stripe (cus_...)', max_length=255, null=True),
        ),
    ]
