# Generated by Django 4.2.27 on 2026-01-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmembership',
            name='sessions_total',
            field=models.IntegerField(blank=True, help_text='Total de sesiones (0 o None = ilimitado)', null=True),
        ),
        migrations.AddField(
            model_name='clientmembership',
            name='sessions_used',
            field=models.IntegerField(default=0, help_text='Sesiones consumidas'),
        ),
    ]
