# Generated by Django 4.2.27 on 2026-01-15 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0004_membershipplan_contract_content_and_more'),
        ('clients', '0007_clientmembership_sessions_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='content',
            field=models.TextField(blank=True, help_text='Contenido HTML/texto del documento'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('CONTRACT', 'Contrato'), ('TERMS', 'Términos y Condiciones'), ('WAIVER', 'Exención de Responsabilidad'), ('CONSENT', 'Consentimiento'), ('OTHER', 'Otro Documento')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='memberships.membershipplan'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='requires_signature',
            field=models.BooleanField(default=True, help_text='¿Requiere que el cliente lo firme?'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se envió al cliente', null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/signatures/'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Firma'), ('SIGNED', 'Firmado'), ('EXPIRED', 'Caducado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='clients/documents/'),
        ),
    ]
