# Generated by Django 4.2.27 on 2026-01-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_clientfield_clientfieldoption_client_is_company_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfield',
            name='field_type',
            field=models.CharField(choices=[('SELECT', 'Selección'), ('TOGGLE', 'Interruptor')], default='SELECT', max_length=20),
        ),
    ]
