# Generated by Django 4.2.27 on 2026-01-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_clientfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmembership',
            name='current_period_end',
            field=models.DateField(blank=True, help_text='Fin del periodo de facturación actual', null=True),
        ),
        migrations.AddField(
            model_name='clientmembership',
            name='current_period_start',
            field=models.DateField(blank=True, help_text='Inicio del periodo de facturación actual', null=True),
        ),
        migrations.AddField(
            model_name='clientmembership',
            name='next_billing_date',
            field=models.DateField(blank=True, help_text='Fecha del próximo cobro', null=True),
        ),
    ]
