# Generated by Django 4.2.27 on 2026-01-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_clientmembership_current_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Si el cliente quiere recibir emails del gimnasio'),
        ),
    ]
