# Generated by Django 4.2.27 on 2026-01-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_email_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisit',
            name='cancellation_type',
            field=models.CharField(blank=True, choices=[('EARLY', 'Cancelación temprana'), ('LATE', 'Cancelación tardía con penalización')], help_text='Tipo de cancelación si el estado es CANCELLED', max_length=20, null=True),
        ),
    ]
