# Generated by Django 4.2.27 on 2026-01-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_clientvisit_cancellation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientfield',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='clientfield',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en el formulario (menor = primero)'),
        ),
        migrations.AddField(
            model_name='clientfield',
            name='show_in_registration',
            field=models.BooleanField(default=False, help_text='Si está activo, este campo aparecerá en el formulario de auto-registro', verbose_name='Mostrar en Registro Público'),
        ),
    ]
