# Generated by Django 4.2.27 on 2026-01-18 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_publicportalsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0005_membershipplan_allow_pause_and_more'),
        ('finance', '0009_alter_paymentmethod_options_and_more'),
        ('clients', '0015_alter_clientfield_options_clientfield_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientmembership',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_memberships', to='organizations.gym'),
        ),
        migrations.AddField(
            model_name='clientmembership',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentmethod'),
        ),
        migrations.AddField(
            model_name='clientmembership',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_memberships', to='memberships.membershipplan'),
        ),
        migrations.AlterField(
            model_name='clientmembership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('EXPIRED', 'Caducada'), ('CANCELLED', 'Cancelada'), ('PENDING', 'Pendiente'), ('PAUSED', 'Pausada'), ('PENDING_PAYMENT', 'Pendiente de pago')], default='ACTIVE', max_length=20),
        ),
    ]
