# Generated by Django 4.2.27 on 2026-01-21 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_publicportalsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0005_membershipplan_allow_pause_and_more'),
        ('clients', '0016_clientmembership_created_by_clientmembership_gym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('CONTRACT', 'Contrato'), ('TERMS', 'Términos y Condiciones'), ('WAIVER', 'Exención de Responsabilidad'), ('CONSENT', 'Consentimiento'), ('MEDICAL', 'Certificado Médico'), ('OTHER', 'Otro Documento')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_documents', to='memberships.membershipplan'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente de Firma'), ('SIGNED', 'Firmado'), ('EXPIRED', 'Caducado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Contrato de Adhesión 2024', max_length=200)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contrato'), ('TERMS', 'Términos y Condiciones'), ('WAIVER', 'Exención de Responsabilidad'), ('CONSENT', 'Consentimiento'), ('MEDICAL', 'Certificado Médico'), ('OTHER', 'Otro Documento')], default='OTHER', max_length=20)),
                ('content', models.TextField(help_text='Contenido HTML del documento')),
                ('requires_signature', models.BooleanField(default=True, help_text='¿Requiere firma del cliente?')),
                ('is_active', models.BooleanField(default=True, help_text='¿Está disponible para enviar?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Plantilla origen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='clients.documenttemplate'),
        ),
    ]
