# Generated by Django 4.2.27 on 2026-01-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_add_document_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='app_access_count',
            field=models.IntegerField(default=0, help_text='Número de veces que ha accedido'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_app_access',
            field=models.DateTimeField(blank=True, help_text='Última vez que accedió a la app o portal', null=True),
        ),
    ]
