# Generated by Django 4.2.27 on 2026-01-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_add_client_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmembership',
            name='failed_charge_attempts',
            field=models.IntegerField(default=0, help_text='Intentos de cobro fallidos consecutivos'),
        ),
        migrations.AddField(
            model_name='clientmembership',
            name='last_charge_attempt',
            field=models.DateTimeField(blank=True, help_text='Última fecha de intento de cobro', null=True),
        ),
        migrations.AddField(
            model_name='clientmembership',
            name='last_charge_error',
            field=models.CharField(blank=True, help_text='Último error de cobro', max_length=255),
        ),
    ]
