# Generated by Django 4.2.27 on 2026-01-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_add_spot_booking'),
        ('services', '0005_service_color'),
        ('clients', '0020_add_charge_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmembership',
            name='allowed_activities',
            field=models.ManyToManyField(blank=True, help_text='Actividades permitidas para este cliente', related_name='client_memberships', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='clientmembership',
            name='allowed_services',
            field=models.ManyToManyField(blank=True, help_text='Servicios permitidos para este cliente', related_name='client_memberships', to='services.service'),
        ),
    ]
