# Generated by Django 4.2.27 on 2026-01-23 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_color'),
        ('activities', '0013_add_spot_booking'),
        ('clients', '0021_add_allowed_activities_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmembership',
            name='allowed_activities',
        ),
        migrations.RemoveField(
            model_name='clientmembership',
            name='allowed_services',
        ),
        migrations.CreateModel(
            name='ClientMembershipAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='0 = Ilimitado', verbose_name='Cantidad')),
                ('quantity_used', models.IntegerField(default=0, verbose_name='Cantidad usada')),
                ('period', models.CharField(choices=[('TOTAL', 'Total (Bono)'), ('PER_CYCLE', 'Por Ciclo (Recurrente)')], default='PER_CYCLE', max_length=20)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('activity_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='clients.clientmembership')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Regla de acceso de membresía',
                'verbose_name_plural': 'Reglas de acceso de membresías',
            },
        ),
    ]
