# Generated by Django 4.2.27 on 2026-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_add_client_membership_access_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='preferred_gateway',
            field=models.CharField(choices=[('AUTO', 'Automático (según configuración del gym)'), ('STRIPE', 'Stripe'), ('REDSYS', 'Redsys')], default='AUTO', help_text='Pasarela de pago preferida para este cliente', max_length=20),
        ),
    ]
