# Generated by Django 4.2.27 on 2026-01-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0100_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_unread_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatroom',
            name='chatroom_lastmsg_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_gym_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_gym_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_dni_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientmembership',
            name='membership_client_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientmembership',
            name='membership_gym_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientmembership',
            name='membership_billing_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientmembership',
            name='membership_expiry_idx',
        ),
    ]
