# Generated by Django 4.2.27 on 2026-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0101_remove_chatmessage_chat_unread_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('NIE', 'NIE'), ('PASSPORT', 'Pasaporte'), ('OTHER', 'Otro')], default='DNI', max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
