# Generated by Django 4.2.27 on 2026-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0102_client_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='other_document_type',
            field=models.CharField(blank=True, help_text="Indica el tipo de documento si seleccionaste 'Otro'", max_length=100, verbose_name='Especificar otro documento'),
        ),
    ]
