# Generated by Django 4.2.27 on 2026-01-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0103_client_other_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='calendar_token',
            field=models.CharField(blank=True, help_text='Token único para la URL de suscripción al calendario', max_length=64, null=True, unique=True),
        ),
    ]
