# Generated by Django 4.2.27 on 2026-02-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_add_membership_purchase_controls'),
        ('memberships', '0101_remove_membershipplan_plan_gym_active_idx_and_more'),
        ('clients', '0104_add_calendar_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMembershipChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Fecha en que se aplicará el cambio (normalmente el end_date de la membresía actual)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPLIED', 'Aplicado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_membership_changes', to='clients.client')),
                ('current_membership', models.ForeignKey(help_text='La membresía activa que se desactivará', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_changes', to='clients.clientmembership')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_membership_changes', to='organizations.gym')),
                ('new_membership', models.ForeignKey(blank=True, help_text='La nueva membresía creada cuando se aplicó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_scheduled_change', to='clients.clientmembership')),
                ('new_plan', models.ForeignKey(help_text='El nuevo plan que se activará', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_upgrades', to='memberships.membershipplan')),
            ],
            options={
                'verbose_name': 'Cambio Programado de Plan',
                'verbose_name_plural': 'Cambios Programados de Plan',
                'ordering': ['-created_at'],
            },
        ),
    ]
