# Generated by Django 4.2.27 on 2026-02-01 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0105_add_membership_purchase_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Notas generales sobre la salud del cliente (alergias, lesiones, etc.)')),
                ('has_medical_clearance', models.BooleanField(default=False, help_text='¿Tiene autorización médica para actividad física?')),
                ('medical_clearance_date', models.DateField(blank=True, help_text='Fecha de la última autorización médica', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Alergias conocidas')),
                ('medical_conditions', models.TextField(blank=True, help_text='Condiciones médicas relevantes')),
                ('medications', models.TextField(blank=True, help_text='Medicamentos que toma actualmente')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Nombre del contacto de emergencia', max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Teléfono del contacto de emergencia', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_record', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Salud',
                'verbose_name_plural': 'Registros de Salud',
            },
        ),
        migrations.CreateModel(
            name='ClientHealthDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del documento', max_length=200)),
                ('document_type', models.CharField(choices=[('MEDICAL_CERT', 'Certificado Médico'), ('FITNESS_TEST', 'Test de Aptitud Física'), ('LAB_RESULTS', 'Resultados de Laboratorio'), ('PRESCRIPTION', 'Prescripción Médica'), ('INJURY_REPORT', 'Informe de Lesión'), ('REHABILITATION', 'Plan de Rehabilitación'), ('OTHER', 'Otro Documento')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='clients/health_documents/')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre el documento')),
                ('document_date', models.DateField(blank=True, help_text='Fecha del documento', null=True)),
                ('expires_at', models.DateField(blank=True, help_text='Fecha de caducidad (si aplica)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.clienthealthrecord')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_health_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Salud',
                'verbose_name_plural': 'Documentos de Salud',
                'ordering': ['-created_at'],
            },
        ),
    ]
