# Generated by Django 5.2.10 on 2026-02-03 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0106_add_health_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Código único de referido del cliente', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Crédito acumulado por referidos', max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Cliente que refirió a este cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_direct', to='clients.client'),
        ),
    ]
