# Generated by Django 5.2.10 on 2026-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0107_referral_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_address',
            field=models.TextField(blank=True, help_text='Dirección fiscal completa de la empresa', verbose_name='Dirección Fiscal'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_email',
            field=models.EmailField(blank=True, help_text='Email para enviar facturas (si es distinto al personal)', max_length=254, null=True, verbose_name='Email de Facturación'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, help_text='Nombre fiscal de la empresa', max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_tax_id',
            field=models.CharField(blank=True, help_text='CIF o NIF de la empresa', max_length=20, verbose_name='CIF/NIF Empresa'),
        ),
        migrations.AddField(
            model_name='client',
            name='use_company_data_in_invoices',
            field=models.BooleanField(default=True, help_text='Si está activo, las facturas y tickets mostrarán los datos de la empresa en lugar de los personales', verbose_name='Usar datos de empresa en facturas'),
        ),
    ]
