# Generated by Django 5.2.10 on 2026-02-03 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0105_add_client_penalty'),
        ('clients', '0108_add_company_and_billing_mode'),
        ('organizations', '0020_add_checkin_methods_and_geolocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('STRIKE', 'Strike (Falta)'), ('FEE', 'Cobro Monetario'), ('FORFEIT', 'Pérdida de Crédito'), ('SUSPENSION', 'Suspensión Temporal')], max_length=20, verbose_name='Tipo de Penalización')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPLIED', 'Aplicada'), ('WAIVED', 'Perdonada'), ('PAID', 'Pagada')], default='APPLIED', max_length=20, verbose_name='Estado')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('waived_reason', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_penalties', to='organizations.gym')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='activities.activitysession')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_waived', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penalización',
                'verbose_name_plural': 'Penalizaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
