from django.contrib.auth.models import Permission

# Define the logical structure for the Permission UI
# This maps a "Module Name" to a list of (Codename, Label) tuples
PERMISSION_STRUCTURE = {
    "Clientes": [
        ("view_client", "Ver Clientes"),
        ("add_client", "Crear Clientes"),
        ("change_client", "Editar Clientes"),
        ("delete_client", "Eliminar Clientes"),
        ("view_clientnote", "Ver Notas"),
        ("add_clientnote", "Añadir Notas"),
        ("change_clientnote", "Editar Notas"),
        ("delete_clientnote", "Eliminar Notas"),
    ],
    "Finanzas": [
        ("view_finance", "Ver Dashboard Financiero"),
        ("add_finance", "Crear Registros Financieros"),
        ("change_finance", "Editar Registros Financieros"),
        ("delete_finance", "Eliminar Registros Financieros"),
        ("view_invoice", "Ver Facturas"),
        ("add_invoice", "Crear Facturas"),
        ("change_invoice", "Editar Facturas"),
        ("delete_invoice", "Eliminar Facturas"),
        ("add_cashsession", "Abrir/Cerrar Caja"),
        ("view_paymentmethod", "Ver Métodos Pago"),
        ("add_paymentmethod", "Crear Métodos Pago"),
        ("change_paymentmethod", "Editar Métodos Pago"),
        ("delete_paymentmethod", "Eliminar Métodos Pago"),
    ],
    "Marketing": [
        ("view_marketing", "Ver Dashboard Marketing"),
        ("add_marketing", "Crear Registros Marketing"),
        ("change_marketing", "Editar Registros Marketing"),
        ("delete_marketing", "Eliminar Registros Marketing"),
        ("view_leadcard", "Ver Leads"),
        ("add_leadcard", "Crear Leads"),
        ("change_leadcard", "Editar Leads"),
        ("delete_leadcard", "Eliminar Leads"),
        ("view_campaign", "Ver Campañas Email"),
        ("add_campaign", "Crear Campañas Email"),
        ("change_campaign", "Editar Campañas Email"),
        ("delete_campaign", "Eliminar Campañas Email"),
        ("view_popup", "Ver Popups/Notificaciones"),
        ("add_popup", "Crear Popups/Notificaciones"),
        ("change_popup", "Editar Popups/Notificaciones"),
        ("delete_popup", "Eliminar Popups/Notificaciones"),
        ("view_advertisement", "Ver Anuncios en App"),
        ("add_advertisement", "Crear Anuncios en App"),
        ("change_advertisement", "Editar Anuncios en App"),
        ("delete_advertisement", "Eliminar Anuncios en App"),
        ("view_emailworkflow", "Ver Automatizaciones"),
        ("add_emailworkflow", "Crear Automatizaciones"),
        ("change_emailworkflow", "Editar Automatizaciones"),
        ("delete_emailworkflow", "Eliminar Automatizaciones"),
    ],
    "Staff (Equipo)": [
        ("view_staffprofile", "Ver Equipo"),
        ("add_staffprofile", "Crear Empleados"),
        ("change_staffprofile", "Editar Equipo"),
        ("delete_staffprofile", "Eliminar Empleados"),
        ("view_workshift", "Ver Turnos"),
        ("add_workshift", "Crear Turnos"),
        ("change_workshift", "Editar Turnos"),
        ("delete_workshift", "Eliminar Turnos"),
        ("view_staffkiosk", "Ver Kiosco de Fichaje"),
        ("access_staffkiosk", "Acceder al Kiosco de Fichaje"),
        ("manage_roles", "Gestionar Roles y Permisos"),
        ("view_incentive", "Ver Incentivos y Comisiones"),
        ("add_incentiverule", "Crear Incentivos"),
        ("change_incentiverule", "Editar Incentivos"),
        ("delete_incentiverule", "Eliminar Incentivos"),
        ("view_all_incentives", "Ver Incentivos de Todo el Staff"),
        ("view_own_incentives", "Ver Solo Incentivos Propios"),
    ],
    "Servicios & Productos": [
        ("view_service", "Ver Servicios"),
        ("add_service", "Crear Servicios"),
        ("change_service", "Editar Servicios"),
        ("delete_service", "Eliminar Servicios"),
        ("view_product", "Ver Productos"),
        ("add_product", "Crear Productos"),
        ("change_product", "Editar Productos"),
        ("delete_product", "Eliminar Productos"),
        ("view_membershipplan", "Ver Cuotas"),
        ("add_membershipplan", "Crear Cuotas"),
        ("change_membershipplan", "Editar Cuotas"),
        ("delete_membershipplan", "Eliminar Cuotas"),
    ],
    "Descuentos": [
        ("view_discount", "Ver Descuentos"),
        ("add_discount", "Crear Descuentos"),
        ("change_discount", "Editar Descuentos"),
        ("delete_discount", "Eliminar Descuentos"),
        ("view_discountusage", "Ver Uso de Descuentos"),
        ("view_referralprogram", "Ver Programas de Referidos"),
        ("add_referralprogram", "Crear Programas de Referidos"),
        ("change_referralprogram", "Editar Programas de Referidos"),
        ("delete_referralprogram", "Eliminar Programas de Referidos"),
    ],
    "Objetivos": [
        ("view_gymgoal", "Ver Objetivos del Gimnasio"),
        ("add_gymgoal", "Crear Objetivos"),
        ("change_gymgoal", "Editar Objetivos"),
        ("delete_gymgoal", "Eliminar Objetivos"),
    ],
    "Calendario y Actividades": [
        ("view_room", "Ver Calendario y Salas"),
        ("add_room", "Crear Salas"),
        ("change_room", "Editar Salas"),
        ("delete_room", "Eliminar Salas"),
        ("view_activity", "Ver Actividades"),
        ("add_activity", "Crear Actividades"),
        ("change_activity", "Editar Actividades"),
        ("delete_activity", "Eliminar Actividades"),
        ("view_activitysession", "Ver Sesiones de Clases"),
        ("add_activitysession", "Crear Sesiones de Clases"),
        ("change_activitysession", "Editar Sesiones de Clases"),
        ("delete_activitysession", "Eliminar Sesiones de Clases"),
        ("view_schedulesettings", "Ver Configuración de Horarios"),
        ("change_schedulesettings", "Modificar Configuración de Horarios"),
        ("view_booking", "Ver Reservas de Clases"),
        ("add_booking", "Crear Reservas de Clases"),
        ("change_booking", "Editar Reservas de Clases"),
        ("delete_booking", "Cancelar Reservas de Clases"),
    ],
    "Rutinas y Ejercicios": [
        ("view_workoutroutine", "Ver Rutinas"),
        ("add_workoutroutine", "Crear Rutinas"),
        ("change_workoutroutine", "Editar Rutinas"),
        ("delete_workoutroutine", "Eliminar Rutinas"),
        ("view_exercise", "Ver Ejercicios"),
        ("add_exercise", "Crear Ejercicios"),
        ("change_exercise", "Editar Ejercicios"),
        ("delete_exercise", "Eliminar Ejercicios"),
    ],
}

def get_all_managed_permissions():
    """
    Returns a flat list of all permission codenames managed by this system.
    """
    perms = []
    for module, actions in PERMISSION_STRUCTURE.items():
        for codename, label in actions:
            perms.append(codename)
    return perms
