# Generated by Django 5.1.15 on 2026-01-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_cancellationpolicy_activity_cancellation_policy'),
        ('finance', '0001_initial'),
        ('organizations', '0002_gym_brand_color'),
        ('services', '0003_service_is_active_service_is_visible_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='membership_images/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('price_strategy', models.CharField(choices=[('TAX_INCLUDED', 'Impuestos Incluidos'), ('TAX_EXCLUDED', 'Impuestos Excluidos')], default='TAX_INCLUDED', max_length=20)),
                ('is_recurring', models.BooleanField(default=True, verbose_name='Es Recurrente (Suscripción)')),
                ('billing_cycle', models.CharField(blank=True, choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=20, null=True, verbose_name='Ciclo de Facturación')),
                ('pack_sessions', models.IntegerField(default=0, help_text='Dejar en 0 si se define por reglas específicas.', verbose_name='Total Sesiones (Solo Bonos)')),
                ('pack_validity_days', models.IntegerField(blank=True, help_text='Caducidad en días para bonos.', null=True, verbose_name='Días de Validez')),
                ('prorate_first_month', models.BooleanField(default=True, verbose_name='Prorratear primer mes')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='organizations.gym')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.taxrate')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='0 = Ilimitado', verbose_name='Cantidad')),
                ('period', models.CharField(choices=[('TOTAL', 'Total (Bono)'), ('PER_CYCLE', 'Por Ciclo (Recurrente)')], default='PER_CYCLE', max_length=20)),
                ('activity_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='memberships.membershipplan')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory')),
            ],
        ),
    ]
