# Generated by Django 5.1.15 on 2026-01-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='is_membership',
            field=models.BooleanField(default=True, help_text='Marcar si este plan cuenta como socio activo para informes.', verbose_name='Es Membresía (Informe)'),
        ),
    ]
