# Generated by Django 5.1.15 on 2026-01-11 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_cancellationpolicy_activity_cancellation_policy'),
        ('memberships', '0002_membershipplan_is_membership'),
        ('services', '0003_service_is_active_service_is_visible_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='pack_sessions',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='frequency_amount',
            field=models.IntegerField(default=1, verbose_name='Cada...'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='frequency_unit',
            field=models.CharField(choices=[('DAY', 'Días'), ('WEEK', 'Semanas'), ('MONTH', 'Meses'), ('YEAR', 'Años')], default='MONTH', max_length=10, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='planaccessrule',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AddField(
            model_name='planaccessrule',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='is_recurring',
            field=models.BooleanField(default=True, verbose_name='Es Recurrente'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='pack_validity_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Días de Validez'),
        ),
    ]
