# Generated by Django 5.1.15 on 2026-01-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_remove_membershipplan_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='contract_content',
            field=models.TextField(blank=True, help_text='Texto legal que el cliente debe aceptar y firmar.', verbose_name='Contenido del Contrato'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='contract_required',
            field=models.BooleanField(default=False, verbose_name='Requiere Firma de Contrato'),
        ),
    ]
