# Generated by Django 4.2.27 on 2026-01-16 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0012_clientmembership_current_period_end_and_more'),
        ('memberships', '0004_membershipplan_contract_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='allow_pause',
            field=models.BooleanField(default=False, help_text='Solo para planes recurrentes', verbose_name='Permitir Pausas'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='pause_advance_notice_days',
            field=models.IntegerField(default=3, help_text='Días mínimos de anticipación para solicitar pausa', verbose_name='Días de Anticipación'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='pause_allows_booking',
            field=models.BooleanField(default=False, help_text='Durante la pausa', verbose_name='Permite Reservas'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='pause_allows_gym_access',
            field=models.BooleanField(default=False, help_text='Durante la pausa', verbose_name='Permite Acceso al Gimnasio'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='pause_extends_end_date',
            field=models.BooleanField(default=True, help_text='Suma los días de pausa al final de la membresía', verbose_name='Extiende Fecha Final'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='pause_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cargo único al activar la pausa', max_digits=10, verbose_name='Cargo por Pausa'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='pause_max_days',
            field=models.IntegerField(default=90, verbose_name='Días Máximos de Pausa'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='pause_max_per_year',
            field=models.IntegerField(default=2, verbose_name='Pausas Máximas al Año'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='pause_min_days',
            field=models.IntegerField(default=7, verbose_name='Días Mínimos de Pausa'),
        ),
        migrations.CreateModel(
            name='MembershipPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activa'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cargo Aplicado')),
                ('reason', models.TextField(blank=True, help_text='Motivo de la pausa', verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym_access_allowed', models.BooleanField(default=False, verbose_name='Acceso Permitido')),
                ('booking_allowed', models.BooleanField(default=False, verbose_name='Reservas Permitidas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pauses', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='clients.clientmembership')),
            ],
            options={
                'verbose_name': 'Pausa de Membresía',
                'verbose_name_plural': 'Pausas de Membresías',
                'ordering': ['-created_at'],
            },
        ),
    ]
