# Generated by Django 4.2.27 on 2026-01-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_membershipplan_allow_pause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='count_late_cancel_as_used',
            field=models.BooleanField(default=False, help_text='Si está activado, las cancelaciones fuera de ventana contarán como sesión gastada', verbose_name='Contar Cancelación Tardía como Sesión Consumida'),
        ),
    ]
