# Generated by Django 4.2.27 on 2026-01-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0100_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='membershipplan',
            name='plan_gym_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='membershipplan',
            name='plan_online_visible_idx',
        ),
        migrations.RemoveIndex(
            model_name='membershipplan',
            name='plan_display_order_idx',
        ),
    ]
