# Generated by Django 4.2.27 on 2026-02-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0101_remove_membershipplan_plan_gym_active_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='is_new_client_only',
            field=models.BooleanField(default=False, help_text='Si se activa, solo los clientes que cumplan el criterio podrán ver/comprar este plan', verbose_name='Solo para Nuevos Clientes'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='new_client_badge_text',
            field=models.CharField(blank=True, default='🎁 Oferta Bienvenida', help_text="Texto que se muestra en el badge promocional (ej: '🎁 Solo Nuevos', 'Oferta Bienvenida')", max_length=30, verbose_name='Texto del Badge'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='new_client_criteria',
            field=models.CharField(choices=[('NEVER_HAD_MEMBERSHIP', 'Nunca ha tenido una membresía'), ('REGISTERED_RECENTLY', 'Registrado recientemente'), ('NEVER_BOUGHT_THIS', 'Nunca ha comprado este plan'), ('INACTIVE_PERIOD', 'Sin actividad en X meses (re-captación)')], default='NEVER_HAD_MEMBERSHIP', help_text="Define qué se considera 'cliente nuevo' para esta oferta", max_length=30, verbose_name='Criterio de Cliente Nuevo'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='new_client_days_threshold',
            field=models.PositiveIntegerField(default=30, help_text="Para 'Registrado recientemente': días desde registro. Para 'Sin actividad': meses sin membresía activa.", verbose_name='Umbral de Días'),
        ),
    ]
