# Generated by Django 4.2.27 on 2026-02-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_gateway_strategy'),
        ('memberships', '0102_add_new_client_only_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='enrollment_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importe base de la matrícula (sin impuestos si aplica)', max_digits=10, verbose_name='Cuota de Inscripción'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='enrollment_fee_tax_rate',
            field=models.ForeignKey(blank=True, help_text='Impuesto aplicable a la cuota de inscripción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_fees', to='finance.taxrate', verbose_name='Impuesto Inscripción'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='enrollment_fee_waivable',
            field=models.BooleanField(default=True, help_text='Permite al staff eximir la cuota de inscripción en casos especiales', verbose_name='Matrícula condonable'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='has_enrollment_fee',
            field=models.BooleanField(default=False, help_text='Cargo único al dar de alta en este plan (matrícula)', verbose_name='Tiene cuota de inscripción'),
        ),
    ]
