# Generated by Django 4.2.27 on 2026-02-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0103_add_enrollment_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='enrollment_fee_channel',
            field=models.CharField(choices=[('BOTH', 'Presencial y Online'), ('ONSITE', 'Solo Presencial (in-situ)'), ('ONLINE', 'Solo Online')], default='BOTH', help_text='Define en qué canales se cobra la cuota de inscripción', max_length=10, verbose_name='Dónde cobrar matrícula'),
        ),
    ]
