# Generated by Django 4.2.27 on 2026-02-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0104_add_enrollment_fee_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='enrollment_fee_price_strategy',
            field=models.CharField(choices=[('TAX_INCLUDED', 'Impuestos Incluidos'), ('TAX_EXCLUDED', 'Impuestos Excluidos')], default='TAX_INCLUDED', help_text='Define si el importe incluye o excluye impuestos', max_length=20, verbose_name='Estrategia Precio Matrícula'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='enrollment_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importe base de la matrícula', max_digits=10, verbose_name='Cuota de Inscripción'),
        ),
    ]
