# Generated by Django 4.2.27 on 2026-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0105_add_enrollment_fee_price_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='eligibility_badge_text',
            field=models.CharField(blank=True, default='', help_text="Badge promocional (ej: '🎁 Solo Nuevos', '⭐ VIP', '🔄 Renueva y ahorra')", max_length=30, verbose_name='Texto del Badge'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='eligibility_criteria',
            field=models.CharField(choices=[('NONE', 'Sin restricción (disponible para todos)'), ('NEVER_HAD_MEMBERSHIP', 'Solo clientes que NUNCA han tenido membresía'), ('NEVER_BOUGHT_THIS', 'Solo clientes que NUNCA han comprado este plan'), ('HAS_BOUGHT_THIS', 'Solo clientes que YA han comprado este plan (fidelización)'), ('REGISTERED_RECENTLY', 'Solo registrados recientemente'), ('INACTIVE_PERIOD', 'Solo clientes inactivos (re-captación)'), ('NO_ACTIVE_MEMBERSHIP', 'Solo clientes SIN membresía activa actualmente'), ('HAS_ACTIVE_MEMBERSHIP', 'Solo clientes CON membresía activa (upgrade/complemento)')], default='NONE', help_text='Define quién puede ver/comprar este plan', max_length=30, verbose_name='Criterio de Elegibilidad'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='eligibility_days_threshold',
            field=models.PositiveIntegerField(default=30, help_text="Para 'Registrado recientemente': días desde registro. Para 'Inactivos': meses sin membresía.", verbose_name='Umbral de Días/Meses'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='visibility_for_ineligible',
            field=models.CharField(choices=[('HIDE', 'Ocultar completamente'), ('SHOW_LOCKED', 'Mostrar bloqueado (genera interés)')], default='HIDE', help_text='Qué hacer con el plan cuando el cliente no cumple el criterio', max_length=15, verbose_name='Visibilidad para No Elegibles'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='is_new_client_only',
            field=models.BooleanField(default=False, help_text='[DEPRECATED] Usar eligibility_criteria en su lugar', verbose_name='Solo para Nuevos Clientes (legacy)'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='new_client_badge_text',
            field=models.CharField(blank=True, default='🎁 Oferta Bienvenida', max_length=30, verbose_name='Texto del Badge (legacy)'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='new_client_criteria',
            field=models.CharField(blank=True, choices=[('NEVER_HAD_MEMBERSHIP', 'Legacy')], default='NEVER_HAD_MEMBERSHIP', max_length=30, verbose_name='Criterio de Cliente Nuevo (legacy)'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='new_client_days_threshold',
            field=models.PositiveIntegerField(default=30, verbose_name='Umbral de Días (legacy)'),
        ),
    ]
