# Generated by Django 5.2.10 on 2026-02-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0106_add_eligibility_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planaccessrule',
            options={'verbose_name': 'Regla de Acceso', 'verbose_name_plural': 'Reglas de Acceso'},
        ),
        migrations.AddField(
            model_name='planaccessrule',
            name='advance_booking_days',
            field=models.PositiveIntegerField(default=0, help_text='Cuántos días en el futuro puede reservar (0 = usar config. global)', verbose_name='Días máximos para reservar'),
        ),
        migrations.AddField(
            model_name='planaccessrule',
            name='advance_booking_hours',
            field=models.PositiveIntegerField(default=0, help_text='Cuántas horas antes puede reservar (0 = usar config. global)', verbose_name='Horas de antelación para reservar'),
        ),
        migrations.AddField(
            model_name='planaccessrule',
            name='allow_waitlist',
            field=models.BooleanField(default=True, help_text='Si la clase está llena, puede unirse a la lista', verbose_name='Permitir lista de espera'),
        ),
        migrations.AddField(
            model_name='planaccessrule',
            name='booking_priority',
            field=models.PositiveIntegerField(default=0, help_text='Mayor número = más prioridad (para desempate en waitlist)', verbose_name='Prioridad de reserva'),
        ),
        migrations.AddField(
            model_name='planaccessrule',
            name='max_per_day',
            field=models.PositiveIntegerField(default=0, help_text='0 = Sin límite diario', verbose_name='Máx. reservas por día'),
        ),
        migrations.AddField(
            model_name='planaccessrule',
            name='max_per_week',
            field=models.PositiveIntegerField(default=0, help_text='0 = Sin límite semanal', verbose_name='Máx. reservas por semana'),
        ),
        migrations.AddField(
            model_name='planaccessrule',
            name='max_simultaneous',
            field=models.PositiveIntegerField(default=0, help_text='0 = Sin límite de reservas futuras a la vez', verbose_name='Máx. reservas simultáneas'),
        ),
        migrations.AlterField(
            model_name='planaccessrule',
            name='period',
            field=models.CharField(choices=[('TOTAL', 'Total (Bono)'), ('PER_CYCLE', 'Por Ciclo (Recurrente)'), ('PER_DAY', 'Por Día'), ('PER_WEEK', 'Por Semana')], default='PER_CYCLE', max_length=20),
        ),
    ]
