# Generated by Django 5.2.10 on 2026-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0107_add_booking_restrictions_to_planaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='receipt_notes',
            field=models.TextField(blank=True, help_text='Texto que aparecerá en el ticket/factura cuando se venda este plan', verbose_name='Notas del Recibo'),
        ),
    ]
