# Generated by Django 5.2.10 on 2026-02-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0108_receipt_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaccessrule',
            name='no_consecutive_days',
            field=models.BooleanField(default=False, help_text='Impide que el cliente reserve o asista en días seguidos', verbose_name='No permite días consecutivos'),
        ),
    ]
