# Generated by Django 5.2.10 on 2026-02-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0109_no_consecutive_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaccessrule',
            name='access_time_end',
            field=models.TimeField(blank=True, help_text='Hora hasta la que se permite reservar/asistir (vacío = sin restricción)', null=True, verbose_name='Hora de acceso hasta'),
        ),
        migrations.AddField(
            model_name='planaccessrule',
            name='access_time_start',
            field=models.TimeField(blank=True, help_text='Hora desde la que se permite reservar/asistir (vacío = sin restricción)', null=True, verbose_name='Hora de acceso desde'),
        ),
    ]
