# Generated by Django 5.2.10 on 2026-02-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0110_access_time_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='scheduling_open_day',
            field=models.PositiveIntegerField(blank=True, help_text='Día del mes en que se abren las reservas del siguiente periodo (vacío = sin restricción)', null=True, verbose_name='Día de apertura de programación'),
        ),
    ]
