# Generated by Django 4.2.27 on 2026-02-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0111_scheduling_open_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='activation_mode',
            field=models.CharField(choices=[('ON_SALE', 'En el día de la venta'), ('ON_FIRST_VISIT', 'En la primera visita del cliente'), ('ON_SPECIFIC_DATE', 'En una fecha específica (manual)')], default='ON_SALE', help_text='Define cuándo se activa la membresía tras la compra', max_length=20, verbose_name='Fecha de Activación'),
        ),
    ]
