# Generated by Django 4.2.27 on 2026-02-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0112_activation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras para venta rápida en TPV', max_length=50, verbose_name='Código de Barras'),
        ),
    ]
