# Generated by Django 4.2.27 on 2026-02-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_wallet_system'),
        ('memberships', '0113_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='additional_tax_rates',
            field=models.ManyToManyField(blank=True, help_text='Impuestos adicionales que se aplican junto al principal (ej: recargos locales)', related_name='membership_plans_additional', to='finance.taxrate', verbose_name='Impuestos Adicionales'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_plans_primary', to='finance.taxrate', verbose_name='Impuesto Principal'),
        ),
    ]
