# Generated by Django 4.2.27 on 2026-02-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0116_max_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaccessrule',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0, help_text='Máximo de usos permitidos en el periodo seleccionado. 0 = sin límite', verbose_name='Límite de uso'),
        ),
        migrations.AddField(
            model_name='planaccessrule',
            name='usage_limit_period',
            field=models.CharField(blank=True, choices=[('', 'Sin límite'), ('PER_DAY', 'Por Día'), ('PER_WEEK', 'Por Semana'), ('PER_MONTH', 'Por Mes')], default='', help_text='Periodo sobre el que aplica el límite de uso', max_length=20, verbose_name='Periodo del límite'),
        ),
    ]
