def translations(request):
    """
    Context processor que provee traducciones básicas basadas en el idioma actual
    """
    translations_dict = {
        'es': {
            # Gym Settings - Brand
            'brand_image': 'Imagen de Marca',
            'logo': 'Logotipo',
            'no_logo': 'Sin Logo',
            'recommended_png': 'Recomendado: PNG fondo transparente (200x200px)',
            'brand_color': 'Color Corporativo',
            'brand_color_usage': 'Se usará en botones, bordes y elementos destacados.',
            'commercial_name': 'Nombre Comercial (Público)',
            'company_data': 'Datos de Empresa',
            'legal_name': 'Razón Social',
            'tax_id': 'CIF / NIF',
            'primary_language': 'Idioma Principal',
            'language_description': 'Idioma por defecto para la interfaz y comunicaciones',
            'contact_location': 'Contacto y Ubicación',
            'address': 'Dirección',
            'city': 'Ciudad',
            'province': 'Provincia',
            'postal_code': 'Código Postal',
            'country': 'País',
            'phone': 'Teléfono',
            'public_email': 'Email Público',
            'website': 'Sitio Web',
            'social_networks': 'Redes Sociales',
            'instagram': 'Instagram',
            'facebook': 'Facebook',
            'tiktok': 'TikTok',
            'youtube': 'YouTube',
            'save_changes': 'Guardar Cambios',
            'cancel': 'Cancelar',
            
            # Gym Settings - SMTP
            'smtp_configuration': 'Configuración SMTP',
            'smtp_description': 'Configura el servidor SMTP para enviar emails desde tu gimnasio (campañas, automatizaciones, etc.)',
            'smtp_server': 'Servidor SMTP',
            'smtp_example': 'Ejemplo: smtp.gmail.com',
            'port': 'Puerto',
            'port_description': '587 para TLS, 465 para SSL',
            'smtp_username': 'Usuario SMTP',
            'smtp_password': 'Contraseña SMTP',
            'encrypted_on_save': 'Se encripta al guardar',
            'sender_email': 'Email Remitente',
            'sender_email_description': 'Email que aparecerá como remitente',
            'use_tls': 'Usar TLS (Recomendado)',
            'use_ssl': 'Usar SSL',
            
            # Gym Settings - Email Signature
            'email_signature_policies': 'Firma y Políticas de Email',
            'email_signature_description': 'Configura la firma y el texto legal que se añadirá automáticamente a todos los emails enviados.',
            'signature_logo': 'Logo para Firma',
            'signature_logo_description': 'Sube un logo o imagen que aparecerá en la firma. Recomendado: PNG transparente, máx 200px de alto.',
            'signature_text': 'Texto de la Firma',
            'signature_text_description': 'Se añade después del contenido del email. Puedes usar HTML básico.',
            'email_footer': 'Pie de Email / Políticas de Privacidad',
            'email_footer_description': 'Texto legal, política de privacidad, enlace de baja, etc.',
            
            # Gym Settings - PWA
            'client_app_pwa': 'App para Clientes (PWA)',
            'pwa_description': 'Tus clientes pueden instalar tu portal como una app en su móvil. Comparte este enlace para que accedan directamente con tu logo y colores corporativos.',
            'scan_to_access': 'Escanear para acceder',
            'portal_link': 'Enlace del Portal',
            'copy': 'Copiar',
            'open_portal': 'Abrir Portal',
            'download_qr': 'Descargar QR',
            'share': 'Compartir',
            'pwa_tip': 'Tip: Comparte este enlace en tu web, redes sociales o por WhatsApp. Los clientes podrán "Instalar" la app desde el navegador de su móvil.',
            'embed_code': 'Código para incrustar en tu web',
            'html_code': 'Código HTML (copia y pega en tu web)',
            'link_copied': '¡Enlace copiado!',
            'code_copied': '¡Código copiado!',
            'qr_downloaded': 'QR descargado',
            'copied_to_clipboard': 'Enlace copiado al portapapeles',
            'access_client_portal': 'Acceder al Portal de Clientes',
            
            # Header
            'select_gym': 'Selecciona Sede',
            'my_gyms': 'Mis Sedes',
            'charge': 'Cobrar',
            'logout': 'Cerrar Sesión',
            'no_gym_assigned': 'Sin gimnasio asignado',
            
            # Sidebar - Main sections
            'superadmin_panel': 'Superadmin Panel',
            'franchise_panel': 'Panel Franquicia',
            'goals': 'Objetivos',
            'dashboard': 'Dashboard',
            'calendar': 'Calendario',
            'clients': 'Clientes',
            'pricing': 'Precios',
            'memberships': 'Cuotas',
            'services': 'Servicios',
            'products': 'Productos',
            'activities': 'Actividades',
            'activities_and_rooms': 'Actividades y Salas',
            'analytics_dashboard': 'Dashboard Analytics',
            'attendance_report': 'Informe de Asistencia',
            'activity_report': 'Informe de Actividades',
            'staff_report': 'Informe de Personal',
            'advanced_analytics': 'Analytics Avanzados',
            
            # Sidebar - Finance
            'finances': 'Finanzas',
            'billing_report': 'Informe de Facturación',
            'expenses': 'Gastos',
            'suppliers': 'Proveedores',
            'financial_settings': 'Configuración',
            
            # Sidebar - POS
            'pos': 'TPV / POS',
            
            # Sidebar - Reporting/Audiences
            'audiences': 'Audiencias',
            'groups_tags': 'Grupos & Etiquetas',
            'client_duplicates': 'Duplicados de Clientes',
            'filter_export': 'Filtrar & Exportar',
            
            # Sidebar - Gamification
            'gamification': 'Gamificación',
            'ranking': 'Ranking',
            'achievements': 'Logros',
            'challenges': 'Retos',
            'settings': 'Ajustes',
            
            # Sidebar - Marketing
            'marketing': 'Marketing',
            'email_campaigns': 'Campañas Email',
            'email_templates': 'Plantillas Email',
            'popups_notifications': 'Popups / Notificaciones',
            'app_ads': 'Anuncios en App',
            'automations': 'Automatizaciones',
            'leads_board': 'Tablero Leads',
            'chat': 'Chat',
            'configuration': 'Configuración',
            
            # Sidebar - Team/Staff
            'team': 'Equipo',
            'employee_list': 'Lista de Empleados',
            'time_clock_kiosk': 'Kiosco de Fichaje',
            'my_commissions': 'Mis Comisiones',
            'vacations': 'Vacaciones',
            'roles_permissions': 'Roles y Permisos',
            'incentives': 'Incentivos',
            'performance': 'Rendimiento',
            'activity_log': 'Registro de Actividad',
            
            # Sidebar - Other
            'providers': 'Proveedores',
            'purchase_orders': 'Órdenes de compra',
            'access_control': 'Control de Acceso',
            'facial_recognition': 'Reconocimiento Facial',
            'lockers': 'Taquillas',
            'routines': 'Rutinas',
            'discounts': 'Descuentos',
            'gym_hours': 'Horario del Gimnasio',
            'holidays': 'Festivos',
            'schedule_settings': 'Configuración de Horarios',
            'documents': 'Documentos',
            'document_templates': 'Plantillas Docs',
            'integrations': 'Integraciones',
            'gym_billing': 'Facturación Gimnasio',
            'close_menu': 'Cerrar Menú',
            'billing_report_title': 'Informe de Facturación',
            'analytics_dashboard_title': 'Dashboard Analytics',
            
            # Dashboard - KPIs
            'change': 'Cambiar',
            'performance_summary_of': 'Resumen de rendimiento de',
            'monthly_billing': 'Facturación (Mes)',
            'vs_previous_month': 'vs mes anterior',
            'without_taxes': 'Sin impuestos:',
            'estimated_taxes': 'Impuestos Estimados',
            'vat_collected': 'IVA Recaudado',
            'active_members': 'Socios Activos',
            'new_this_month': 'nuevos este mes',
            'next_month_prediction': 'Próx. Mes (Predicción)',
            'growth': 'Crecimiento',
            'decline': 'Decrecimiento',
            'stable': 'Estable',
            'breakeven_point': 'Punto de Equilibrio',
            'accumulated_balance': 'Balance Acumulado',
            'month_revenue': 'Ingresos mes:',
            'month_expenses': 'Gastos mes:',
            'month_balance': 'Balance mes:',
            'estimated_breakeven': 'Equilibrio estimado en:',
            'months': 'meses',
            'positive_balance': '¡Ya estás en equilibrio positivo!',
            'review_costs': 'Revisar costos y crecimiento',
            'need_more_data': 'Necesitas al menos 3 meses de datos',
            'view_finances': 'Ver finanzas →',
            
            # Dashboard - Memberships
            'active_memberships': 'Membresías Activas',
            'expiring_soon': 'expiran pronto',
            'view_all': 'Ver todas →',
            
            # Dashboard - Goals
            'month_goals': 'Objetivos del Mes',
            'members_goal': 'Socios',
            'revenue_goal': 'Facturación',
            'goal': 'Meta:',
            'view_all_goals': 'Ver todos los objetivos →',
            'current_goals': 'Objetivos Actuales',
            'period_performance': 'Seguimiento de rendimiento del período',
            
            # Dashboard - Quick Actions
            'quick_access': 'Accesos Rápidos',
            'go_to_pos': 'Ir al TPV',
            'new_member': 'Nuevo Socio',
            
            # Dashboard - Staff Kiosk
            'time_clock': 'Kiosco de Fichaje',
            'staff_control': 'Control de Personal',
            'online_now': 'Online ahora:',
            'open_kiosk': 'Abrir Kiosco',
            'view_all_employees': 'Ver todos los empleados',
            
            # Dashboard - Risk Clients
            'risk_clients': 'Clientes en Riesgo (Scoring)',
            'detected': 'Detectados',
            'action_in_days': 'Acción en',
            'days': 'días',
            'no_risk_clients': 'No hay clientes en riesgo detectados.',
            
            # Dashboard - Top Clients
            'top_clients': 'Top Clientes (LTV)',
            'no_data_yet': 'No hay datos aún.',
            
            # Dashboard - Charts
            'revenue_evolution': 'Evolución de Ingresos (30 días)',
            'updated_today': 'Actualizado hoy',
            'revenue': 'Ingresos (€)',
            
            # Dashboard - Forecast
            'quarterly_forecast': 'Previsión Trimestral',
            'based_on_months': 'Basado en',
            'total_projected': 'Total Proyectado (3 meses)',
            'average': 'Promedio:',
            'per_month': '€/mes',
            'trend': 'TENDENCIA',
            'historical': 'HISTÓRICO',
            'monthly_breakdown': 'Desglose Mensual',
            'confidence': 'Confianza:',
            
            # Common
            'search': 'Buscar...',
            'all': 'Todos',
            'add': 'Añadir',
            'edit': 'Editar',
            'delete': 'Eliminar',
            'duplicate': 'Duplicar',
            'save': 'Guardar',
            'close': 'Cerrar',
            'confirm': 'Confirmar',
            'back': 'Volver',
            'next': 'Siguiente',
            'previous': 'Anterior',
            'loading': 'Cargando...',
            'no_results': 'Sin resultados',
            'error': 'Error',
            'success': 'Éxito',
            'warning': 'Advertencia',
            'info': 'Información',
            'yes': 'Sí',
            'no': 'No',
            'or': 'o',
            'and': 'y',
            'name': 'Nombre',
            'email': 'Email',
            'password': 'Contraseña',
            'phone': 'Teléfono',
            'enter': 'Entrar',
            
            # Auth / Login
            'login_title': 'Accede al backoffice',
            'login_no_access': 'Si no tienes acceso, pídeselo al administrador del gimnasio.',
            'forgot_password': '¿Olvidaste tu contraseña?',
            'remember_me': 'Recordarme',
            'login_error': 'Email o contraseña incorrectos',
            
            # Registration
            'create_account': 'Crear Cuenta',
            'join_us': 'Únete a',
            'select_gym': 'Selecciona tu Sede',
            'choose_gym': 'Elige un gimnasio',
            'select_gym_desc': 'Selecciona el gimnasio al que quieres apuntarte',
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'additional_info': 'Información Adicional',
            'select_option': 'Selecciona',
            'security': 'Seguridad',
            'confirm_password': 'Confirmar Contraseña',
            'min_characters': 'Mínimo 8 caracteres',
            'repeat_password': 'Repite la contraseña',
            'accept_terms': 'Acepto los términos y condiciones',
            'already_have_account': '¿Ya tienes cuenta? Inicia sesión',
            'no_account_register': '¿No tienes cuenta? Regístrate',
            'account_pending_review': 'Tu cuenta será revisada por nuestro equipo antes de activarse.',
            'required_field': 'Campo obligatorio',
            
            # Profile / Portal
            'my_profile': 'Mi Perfil',
            'my_account': 'Mi Cuenta',
            'control_panel': 'Panel de Control',
            'personal_data': 'Datos Personales',
            'name_email_phone_photo': 'Nombre, email, teléfono, foto',
            'my_memberships': 'Mis Membresías',
            'active_plans_renewals': 'Planes activos y renovaciones',
            'messages_inquiries': 'Mensajes y consultas',
            'my_routines': 'Mis Rutinas',
            'your_membership': 'Tu membresía',
            'valid_until': 'Válida hasta',
            'sessions_remaining': 'Sesiones restantes',
            'no_active_membership': 'Sin membresía activa',
            'get_a_plan': 'Adquiere un plan para empezar',
            'view_plans': 'Ver Planes',
            'visits': 'Visitas',
            'bookings_month': 'Reservas mes',
            'bookings_reservations_activity': 'Reservas, membresías, actividad',
            
            # Wallet
            'my_wallet': 'Mi Monedero',
            'available_balance': 'Saldo Disponible',
            'available_with_credit': 'Disponible con crédito',
            'topped_up': 'Recargado',
            'spent': 'Gastado',
            'top_up_balance': 'Recargar Saldo',
            'active_bonus': '¡Bonificación activa!',
            'bonus_percentage': 'Recibe un {0}% extra al recargar',
            'recent_transactions': 'Últimos Movimientos',
            'balance': 'Saldo',
            'no_transactions': 'Sin movimientos todavía',
            'select_amount': 'Selecciona una cantidad',
            'enter_other_amount': 'O introduce otra cantidad',
            'minimum': 'Mínimo',
            'maximum': 'Máximo',
            'bonus': 'Bonificación',
            'you_will_receive': 'Recibirás',
            'confirm_topup': 'Confirmar Recarga',
            'redirect_payment': 'Se te redirigirá a la pasarela de pago segura',
            
            # Shop
            'shop': 'Tienda',
            'shop_description': 'Servicios, productos y planes disponibles',
            'plans_memberships': 'Planes y Cuotas',
            'already_have_membership': 'Ya tienes una cuota activa',
            'view_current_membership': 'Ver mi cuota actual',
            'scheduled_plan_change': 'Cambio de plan programado',
            'plan_will_change_to': 'Tu plan cambiará a',
            'cancel_scheduled_change': 'Cancelar cambio programado',
            'in_stock': 'En stock',
            'low_stock': 'Pocas unidades',
            'out_of_stock': 'Agotado',
            'no_products_available': 'No hay productos disponibles',
            'check_back_later': 'Pronto habrá novedades. ¡Vuelve más tarde!',
            'your_new_plan': 'Tu nuevo plan será',
            'change_applied_automatically': 'El cambio se aplicará automáticamente',
            'charge_saved_card': 'El cobro se realizará con la tarjeta que tienes guardada',
            
            # Dashboard - Sidebar submenu
            'summary': 'Resumen',
            'comparative_analytics': 'Analítica Comparativa',
            
            # Comparative Analytics Dashboard
            'comparative_analytics_title': 'Analíticas Comparativas',
            'year_vs_year_comparison': 'Comparativa año vs año de todas las métricas clave',
            'years': 'Años',
            'vs_previous_year': 'vs año anterior',
            'monthly_billing': 'Facturación Mensual',
            'revenue_comparison_by_month': 'Comparativa de ingresos por mes y año',
            'bar_chart': 'Barras',
            'line_chart': 'Líneas',
            'month': 'Mes',
            'change_variation': 'Var.',
            'total': 'TOTAL',
            'yoy_growth': 'Crecimiento YoY',
            
            # Memberships section
            'membership_evolution': 'Evolución de Membresías',
            'signups_cancellations_churn': 'Altas, bajas y tasa de cancelación',
            'signups': 'Altas',
            'cancellations': 'Bajas',
            'churn_rate': 'Tasa Churn',
            'net': 'Neto',
            'annual_summary': 'Resumen Anual',
            'avg_churn': 'Churn promedio',
            
            # Attendance section
            'attendance': 'Asistencia',
            'checkins_unique_clients': 'Check-ins y clientes únicos',
            'checkins': 'Check-ins',
            'unique_clients': 'Clientes únicos',
            'avg_per_client': 'Promedio por cliente',
            'total_checkins': 'Total check-ins',
            
            # Class occupancy
            'class_occupancy': 'Ocupación de Clases',
            'average_occupancy_per_session': 'Ocupación promedio por sesión',
            'occupancy': 'Ocupación',
            'sessions': 'Sesiones',
            'annual_avg_occupancy': 'Ocupación promedio anual',
            
            # Products section
            'product_sales': 'Ventas de Productos',
            'top_products_by_quantity': 'Top productos por cantidad vendida',
            'product': 'Producto',
            'quantity': 'Cantidad',
            'income': 'Ingresos',
            'no_data': 'Sin datos',
            
            # Peak hours
            'peak_hours': 'Horas Pico',
            'more_attendance': 'Más asistencia',
            'less_attendance': 'Menos asistencia',
            'busiest_hours': 'Horas más concurridas',
            'busiest_days': 'Días más concurridos',
            'no_enough_data': 'Sin datos suficientes',
            
            # MRR section
            'mrr_title': 'MRR (Ingresos Recurrentes Mensuales)',
            'mrr_description': 'Ingresos recurrentes mensuales',
            'revenue_by_category': 'Ingresos por Categoría',
            'revenue_distribution': 'Distribución de facturación',
            
            # LTV section
            'ltv_metrics': 'Métricas LTV',
            'customer_lifetime_value': 'Valor del cliente en el tiempo',
            'ltv': 'LTV',
            'avg_customer_lifespan': 'Vida promedio cliente',
            'monthly_arpc': 'ARPC Mensual',
            
            # Export
            'export': 'Exportar',
            'export_excel': 'Exportar Excel',
            'export_csv': 'Exportar CSV',
            'export_pdf': 'Exportar PDF',
            
            # Profile - Activity Section
            'activity': 'Actividad',
            'book_classes': 'Reservar Clases',
            'schedule_availability': 'Horario y disponibilidad',
            'attendance_history': 'Historial de Asistencia',
            'classes_attended': 'Clases a las que has asistido',
            'my_achievements': 'Mis Logros',
            'unlocked': 'desbloqueados',
            'your_position': 'Tu posición',
            'your_training_plan': 'Tu plan de entrenamiento',
            'account_balance': 'Saldo de tu cuenta',
            'invite_friends': 'Invitar Amigos',
            'share_earn_rewards': 'Comparte y gana recompensas',
            'streak': 'Racha',
            'active_status': 'Activo',
            
            # Profile - Shopping Section
            'buying': 'Comprar',
            'products_supplements': 'Productos y suplementos',
            'my_purchases': 'Mis Compras',
            'order_history': 'Historial de pedidos',
            
            # Profile - Payments Section
            'payments': 'Pagos',
            'payment_history': 'Historial de Pagos',
            'invoices_receipts': 'Facturas y recibos',
            'payment_methods': 'Métodos de Pago',
            'saved_cards': 'Tarjetas guardadas',
            
            # Profile - Support Section
            'support': 'Soporte',
            'help_faq': 'Ayuda y FAQ',
            'frequently_asked_questions': 'Preguntas frecuentes',
            'contact': 'Contactar',
            'terms_conditions': 'Términos y Condiciones',
            'privacy_policy': 'Política de privacidad',
            'chat_with': 'Chat con',
            
            # Edit Profile
            'edit_profile': 'Editar Perfil',
            'change_photo': 'Cambiar Foto',
            'profile_photo': 'Foto de Perfil',
            'click_to_upload': 'Clic para subir o arrastra la foto',
            'photo_format': 'Formato: JPG, PNG (max 5MB)',
            'personal_info': 'Información Personal',
            'birth_date': 'Fecha de Nacimiento',
            'gender': 'Género',
            'male': 'Masculino',
            'female': 'Femenino',
            'other': 'Otro',
            'not_specified': 'No especificado',
            'contact_info': 'Información de Contacto',
            'current_password': 'Contraseña Actual',
            'new_password': 'Nueva Contraseña',
            'leave_blank_no_change': 'Dejar en blanco si no quieres cambiarla',
            'saving': 'Guardando...',
            
            # Dashboard / Client Area
            'manage_account_activities': 'Gestiona tu cuenta y tus actividades',
            'start': 'Inicio',
            'end': 'Fin',
            'unlimited': 'Ilimitado',
            'pause': 'Pausar',
            'cancel_renewal': 'Cancelar renovación',
            'no_active_memberships': 'No tienes membresías activas',
            'get_plan_start_training': 'Adquiere un plan para empezar a entrenar',
            'want_advance_payment': '¿Quieres adelantar tu pago?',
            'pay_next_fee_early': 'Paga tu siguiente cuota antes de la fecha programada y mantén tu membresía siempre activa.',
            'advance_payment': 'Adelantar Cobro',
            'my_upcoming_classes': 'Mis Próximas Clases',
            'no_classes_booked': 'No tienes clases reservadas',
            'book_spot_schedule': 'Reserva tu plaza en el horario',
            'view_schedule': 'Ver Horario',
            'with': 'Con',
            
            # Gamification Dashboard
            'my_progress': 'Mi Progreso',
            'level': 'Nivel',
            'total_xp': 'XP Total',
            'xp_to_next_level': 'XP para nivel',
            'current_streak': 'Racha actual',
            'complete_actions_unlock': '¡Completa acciones para desbloquear logros!',
            'view_full_ranking': 'Ver Ranking Completo →',
            
            # Schedule
            'class_schedule': 'Horario de Clases',
            'check_classes_availability': 'Consulta nuestras clases y disponibilidad en tiempo real',
            'login_to_book': 'Inicia sesión para reservar clases',
            'filter_by_activity': 'Filtrar por actividad',
            'view_all': 'Ver Todas',
            'instructor': 'Instructor',
            'room': 'Sala',
            'availability': 'Disponibilidad',
            'spots_occupied': 'plazas ocupadas',
            'class_full': 'Clase Completa',
            'spots_available': 'plazas disponibles',
            'book_spot': 'Reservar Plaza',
            'login_to_book_btn': 'Inicia Sesión para Reservar',
            'booking_in_progress': 'Reservando...',
            'booking_error': 'Error al realizar la reserva',
            'could_not_complete': 'No se pudo completar la reserva',
            
            # Pricing
            'plans_pricing': 'Planes y Tarifas',
            'find_perfect_plan': 'Encuentra el plan perfecto para ti',
            'automatic_renewal': 'Renovación automática cada',
            'valid_for': 'Válido por',
            'days': 'días',
            'pauses_allowed': 'Pausas permitidas',
            'unlimited_access': 'Acceso ilimitado',
            'sessions_count': 'sesiones',
            'not_available': 'No Disponible',
            'buy_plan': 'Comprar Plan',
            'contract_required': 'Requiere firma de contrato',
            'no_plans_available': 'No hay planes disponibles',
            'contact_gym_info': 'Contacta con el gimnasio para más información',
            'call_to': 'Llamar al',
            'have_questions': '¿Tienes dudas?',
            'payment_methods': 'Métodos de pago',
            'payment_secure': 'Aceptamos tarjeta de crédito/débito. Pago seguro con cifrado SSL.',
            'cancellations_title': 'Cancelaciones',
            'cancellations_desc': 'Puedes cancelar tu membresía en cualquier momento desde tu perfil.',
            'location': 'Ubicación',
            'contact': 'Contacto',
        },
        'en': {
            # Gym Settings - Brand
            'brand_image': 'Brand Image',
            'logo': 'Logo',
            'no_logo': 'No Logo',
            'recommended_png': 'Recommended: Transparent PNG (200x200px)',
            'brand_color': 'Brand Color',
            'brand_color_usage': 'Will be used in buttons, borders and highlighted elements.',
            'commercial_name': 'Commercial Name (Public)',
            'company_data': 'Company Data',
            'legal_name': 'Legal Name',
            'tax_id': 'Tax ID / VAT',
            'primary_language': 'Primary Language',
            'language_description': 'Default language for interface and communications',
            'contact_location': 'Contact & Location',
            'address': 'Address',
            'city': 'City',
            'province': 'Province / State',
            'postal_code': 'Postal Code',
            'country': 'Country',
            'phone': 'Phone',
            'public_email': 'Public Email',
            'website': 'Website',
            'social_networks': 'Social Networks',
            'instagram': 'Instagram',
            'facebook': 'Facebook',
            'tiktok': 'TikTok',
            'youtube': 'YouTube',
            'save_changes': 'Save Changes',
            'cancel': 'Cancel',
            
            # Gym Settings - SMTP
            'smtp_configuration': 'SMTP Configuration',
            'smtp_description': 'Configure the SMTP server to send emails from your gym (campaigns, automations, etc.)',
            'smtp_server': 'SMTP Server',
            'smtp_example': 'Example: smtp.gmail.com',
            'port': 'Port',
            'port_description': '587 for TLS, 465 for SSL',
            'smtp_username': 'SMTP Username',
            'smtp_password': 'SMTP Password',
            'encrypted_on_save': 'Encrypted when saved',
            'sender_email': 'Sender Email',
            'sender_email_description': 'Email that will appear as sender',
            'use_tls': 'Use TLS (Recommended)',
            'use_ssl': 'Use SSL',
            
            # Gym Settings - Email Signature
            'email_signature_policies': 'Email Signature & Policies',
            'email_signature_description': 'Configure the signature and legal text that will be automatically added to all emails sent.',
            'signature_logo': 'Signature Logo',
            'signature_logo_description': 'Upload a logo or image that will appear in the signature. Recommended: Transparent PNG, max 200px height.',
            'signature_text': 'Signature Text',
            'signature_text_description': 'Added after the email content. You can use basic HTML.',
            'email_footer': 'Email Footer / Privacy Policy',
            'email_footer_description': 'Legal text, privacy policy, unsubscribe link, etc.',
            
            # Gym Settings - PWA
            'client_app_pwa': 'Client App (PWA)',
            'pwa_description': 'Your clients can install your portal as an app on their mobile. Share this link for direct access with your logo and brand colors.',
            'scan_to_access': 'Scan to access',
            'portal_link': 'Portal Link',
            'copy': 'Copy',
            'open_portal': 'Open Portal',
            'download_qr': 'Download QR',
            'share': 'Share',
            'pwa_tip': 'Tip: Share this link on your website, social media or via WhatsApp. Clients can "Install" the app from their mobile browser.',
            'embed_code': 'Embed code for your website',
            'html_code': 'HTML Code (copy and paste in your website)',
            'link_copied': 'Link copied!',
            'code_copied': 'Code copied!',
            'qr_downloaded': 'QR downloaded',
            'copied_to_clipboard': 'Link copied to clipboard',
            'access_client_portal': 'Access Client Portal',
            
            # Header
            'select_gym': 'Select Location',
            'my_gyms': 'My Locations',
            'charge': 'Charge',
            'logout': 'Logout',
            'no_gym_assigned': 'No gym assigned',
            
            # Sidebar - Main sections
            'superadmin_panel': 'Superadmin Panel',
            'franchise_panel': 'Franchise Panel',
            'goals': 'Goals',
            'dashboard': 'Dashboard',
            'calendar': 'Calendar',
            'clients': 'Clients',
            'pricing': 'Pricing',
            'memberships': 'Memberships',
            'services': 'Services',
            'products': 'Products',
            'activities': 'Activities',
            'activities_and_rooms': 'Activities & Rooms',
            'analytics_dashboard': 'Analytics Dashboard',
            'attendance_report': 'Attendance Report',
            'activity_report': 'Activity Report',
            'staff_report': 'Staff Report',
            'advanced_analytics': 'Advanced Analytics',
            
            # Sidebar - Finance
            'finances': 'Finances',
            'billing_report': 'Billing Report',
            'expenses': 'Expenses',
            'suppliers': 'Suppliers',
            'financial_settings': 'Settings',
            
            # Sidebar - POS
            'pos': 'POS',
            
            # Sidebar - Reporting/Audiences
            'audiences': 'Audiences',
            'groups_tags': 'Groups & Tags',
            'client_duplicates': 'Client Duplicates',
            'filter_export': 'Filter & Export',
            
            # Sidebar - Gamification
            'gamification': 'Gamification',
            'ranking': 'Ranking',
            'achievements': 'Achievements',
            'challenges': 'Challenges',
            'settings': 'Settings',
            
            # Sidebar - Marketing
            'marketing': 'Marketing',
            'email_campaigns': 'Email Campaigns',
            'email_templates': 'Email Templates',
            'popups_notifications': 'Popups / Notifications',
            'app_ads': 'In-App Ads',
            'automations': 'Automations',
            'leads_board': 'Leads Board',
            'chat': 'Chat',
            'configuration': 'Configuration',
            
            # Sidebar - Team/Staff
            'team': 'Team',
            'employee_list': 'Employee List',
            'time_clock_kiosk': 'Time Clock Kiosk',
            'my_commissions': 'My Commissions',
            'vacations': 'Vacations',
            'roles_permissions': 'Roles & Permissions',
            'incentives': 'Incentives',
            'performance': 'Performance',
            'activity_log': 'Activity Log',
            
            # Sidebar - Other
            'providers': 'Providers',
            'purchase_orders': 'Purchase Orders',
            'access_control': 'Access Control',
            'facial_recognition': 'Facial Recognition',
            'lockers': 'Lockers',
            'routines': 'Routines',
            'discounts': 'Discounts',
            'gym_hours': 'Gym Hours',
            'holidays': 'Holidays',
            'schedule_settings': 'Schedule Settings',
            'documents': 'Documents',
            'document_templates': 'Doc Templates',
            'integrations': 'Integrations',
            'gym_billing': 'Gym Billing',
            'close_menu': 'Close Menu',
            'billing_report_title': 'Billing Report',
            'analytics_dashboard_title': 'Analytics Dashboard',
            
            # Dashboard - KPIs
            'change': 'Change',
            'performance_summary_of': 'Performance summary of',
            'monthly_billing': 'Monthly Billing',
            'vs_previous_month': 'vs previous month',
            'without_taxes': 'Without taxes:',
            'estimated_taxes': 'Estimated Taxes',
            'vat_collected': 'VAT Collected',
            'active_members': 'Active Members',
            'new_this_month': 'new this month',
            'next_month_prediction': 'Next Month (Prediction)',
            'growth': 'Growth',
            'decline': 'Decline',
            'stable': 'Stable',
            'breakeven_point': 'Break-Even Point',
            'accumulated_balance': 'Accumulated Balance',
            'month_revenue': 'Month revenue:',
            'month_expenses': 'Month expenses:',
            'month_balance': 'Month balance:',
            'estimated_breakeven': 'Estimated break-even in:',
            'months': 'months',
            'positive_balance': 'You are already in positive balance!',
            'review_costs': 'Review costs and growth',
            'need_more_data': 'You need at least 3 months of data',
            'view_finances': 'View finances →',
            
            # Dashboard - Memberships
            'active_memberships': 'Active Memberships',
            'expiring_soon': 'expiring soon',
            'view_all': 'View all →',
            
            # Dashboard - Goals
            'month_goals': 'Month Goals',
            'members_goal': 'Members',
            'revenue_goal': 'Revenue',
            'goal': 'Goal:',
            'view_all_goals': 'View all goals →',
            'current_goals': 'Current Goals',
            'period_performance': 'Period performance tracking',
            
            # Dashboard - Quick Actions
            'quick_access': 'Quick Access',
            'go_to_pos': 'Go to POS',
            'new_member': 'New Member',
            
            # Dashboard - Staff Kiosk
            'time_clock': 'Time Clock Kiosk',
            'staff_control': 'Staff Control',
            'online_now': 'Online now:',
            'open_kiosk': 'Open Kiosk',
            'view_all_employees': 'View all employees',
            
            # Dashboard - Risk Clients
            'risk_clients': 'At-Risk Clients (Scoring)',
            'detected': 'Detected',
            'action_in_days': 'Action in',
            'days': 'days',
            'no_risk_clients': 'No at-risk clients detected.',
            
            # Dashboard - Top Clients
            'top_clients': 'Top Clients (LTV)',
            'no_data_yet': 'No data yet.',
            
            # Dashboard - Charts
            'revenue_evolution': 'Revenue Evolution (30 days)',
            'updated_today': 'Updated today',
            'revenue': 'Revenue (€)',
            
            # Dashboard - Forecast
            'quarterly_forecast': 'Quarterly Forecast',
            'based_on_months': 'Based on',
            'total_projected': 'Total Projected (3 months)',
            'average': 'Average:',
            'per_month': '€/month',
            'trend': 'TREND',
            'historical': 'HISTORICAL',
            'monthly_breakdown': 'Monthly Breakdown',
            'confidence': 'Confidence:',
            
            # Common
            'search': 'Search...',
            'all': 'All',
            'add': 'Add',
            'edit': 'Edit',
            'delete': 'Delete',
            'duplicate': 'Duplicate',
            'save': 'Save',
            'close': 'Close',
            'confirm': 'Confirm',
            'back': 'Back',
            'next': 'Next',
            'previous': 'Previous',
            'loading': 'Loading...',
            'no_results': 'No results',
            'error': 'Error',
            'success': 'Success',
            'warning': 'Warning',
            'info': 'Information',
            'yes': 'Yes',
            'no': 'No',
            'or': 'or',
            'and': 'and',
            'name': 'Name',
            'email': 'Email',
            'password': 'Password',
            'phone': 'Phone',
            'enter': 'Enter',
            
            # Auth / Login
            'login_title': 'Access backoffice',
            'login_no_access': 'If you don\'t have access, ask your gym administrator.',
            'forgot_password': 'Forgot your password?',
            'remember_me': 'Remember me',
            'login_error': 'Incorrect email or password',
            
            # Registration
            'create_account': 'Create Account',
            'join_us': 'Join',
            'select_gym': 'Select your Location',
            'choose_gym': 'Choose a gym',
            'select_gym_desc': 'Select the gym you want to join',
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'additional_info': 'Additional Information',
            'select_option': 'Select',
            'security': 'Security',
            'confirm_password': 'Confirm Password',
            'min_characters': 'Minimum 8 characters',
            'repeat_password': 'Repeat password',
            'accept_terms': 'I accept the terms and conditions',
            'already_have_account': 'Already have an account? Sign in',
            'no_account_register': 'Don\'t have an account? Register',
            'account_pending_review': 'Your account will be reviewed by our team before activation.',
            'required_field': 'Required field',
            
            # Profile / Portal
            'my_profile': 'My Profile',
            'my_account': 'My Account',
            'control_panel': 'Control Panel',
            'personal_data': 'Personal Data',
            'name_email_phone_photo': 'Name, email, phone, photo',
            'my_memberships': 'My Memberships',
            'active_plans_renewals': 'Active plans and renewals',
            'messages_inquiries': 'Messages and inquiries',
            'my_routines': 'My Routines',
            'your_membership': 'Your membership',
            'valid_until': 'Valid until',
            'sessions_remaining': 'Sessions remaining',
            'no_active_membership': 'No active membership',
            'get_a_plan': 'Get a plan to start',
            'view_plans': 'View Plans',
            'visits': 'Visits',
            'bookings_month': 'Bookings this month',
            'bookings_reservations_activity': 'Bookings, memberships, activity',
            
            # Wallet
            'my_wallet': 'My Wallet',
            'available_balance': 'Available Balance',
            'available_with_credit': 'Available with credit',
            'topped_up': 'Topped up',
            'spent': 'Spent',
            'top_up_balance': 'Top Up Balance',
            'active_bonus': 'Active bonus!',
            'bonus_percentage': 'Get {0}% extra when topping up',
            'recent_transactions': 'Recent Transactions',
            'balance': 'Balance',
            'no_transactions': 'No transactions yet',
            'select_amount': 'Select an amount',
            'enter_other_amount': 'Or enter another amount',
            'minimum': 'Minimum',
            'maximum': 'Maximum',
            'bonus': 'Bonus',
            'you_will_receive': 'You will receive',
            'confirm_topup': 'Confirm Top Up',
            'redirect_payment': 'You will be redirected to the secure payment gateway',
            
            # Shop
            'shop': 'Shop',
            'shop_description': 'Services, products and plans available',
            'plans_memberships': 'Plans & Memberships',
            'already_have_membership': 'You already have an active membership',
            'view_current_membership': 'View my current membership',
            'scheduled_plan_change': 'Scheduled plan change',
            'plan_will_change_to': 'Your plan will change to',
            'cancel_scheduled_change': 'Cancel scheduled change',
            'in_stock': 'In stock',
            'low_stock': 'Low stock',
            'out_of_stock': 'Out of stock',
            'no_products_available': 'No products available',
            'check_back_later': 'New products coming soon. Check back later!',
            'your_new_plan': 'Your new plan will be',
            'change_applied_automatically': 'The change will be applied automatically',
            'charge_saved_card': 'Payment will be charged to your saved card',
            
            # Dashboard - Sidebar submenu
            'summary': 'Summary',
            'comparative_analytics': 'Comparative Analytics',
            
            # Comparative Analytics Dashboard
            'comparative_analytics_title': 'Comparative Analytics',
            'year_vs_year_comparison': 'Year vs year comparison of all key metrics',
            'years': 'Years',
            'vs_previous_year': 'vs previous year',
            'monthly_billing': 'Monthly Billing',
            'revenue_comparison_by_month': 'Revenue comparison by month and year',
            'bar_chart': 'Bar',
            'line_chart': 'Line',
            'month': 'Month',
            'change_variation': 'Var.',
            'total': 'TOTAL',
            'yoy_growth': 'YoY Growth',
            
            # Memberships section
            'membership_evolution': 'Membership Evolution',
            'signups_cancellations_churn': 'Sign-ups, cancellations and churn rate',
            'signups': 'Sign-ups',
            'cancellations': 'Cancellations',
            'churn_rate': 'Churn Rate',
            'net': 'Net',
            'annual_summary': 'Annual Summary',
            'avg_churn': 'Avg churn',
            
            # Attendance section
            'attendance': 'Attendance',
            'checkins_unique_clients': 'Check-ins and unique clients',
            'checkins': 'Check-ins',
            'unique_clients': 'Unique clients',
            'avg_per_client': 'Avg per client',
            'total_checkins': 'Total check-ins',
            
            # Class occupancy
            'class_occupancy': 'Class Occupancy',
            'average_occupancy_per_session': 'Average occupancy per session',
            'occupancy': 'Occupancy',
            'sessions': 'Sessions',
            'annual_avg_occupancy': 'Annual avg occupancy',
            
            # Products section
            'product_sales': 'Product Sales',
            'top_products_by_quantity': 'Top products by quantity sold',
            'product': 'Product',
            'quantity': 'Quantity',
            'income': 'Revenue',
            'no_data': 'No data',
            
            # Peak hours
            'peak_hours': 'Peak Hours',
            'more_attendance': 'More attendance',
            'less_attendance': 'Less attendance',
            'busiest_hours': 'Busiest hours',
            'busiest_days': 'Busiest days',
            'no_enough_data': 'No enough data',
            
            # MRR section
            'mrr_title': 'MRR (Monthly Recurring Revenue)',
            'mrr_description': 'Monthly recurring revenue',
            'revenue_by_category': 'Revenue by Category',
            'revenue_distribution': 'Revenue distribution',
            
            # LTV section
            'ltv_metrics': 'LTV Metrics',
            'customer_lifetime_value': 'Customer lifetime value',
            'ltv': 'LTV',
            'avg_customer_lifespan': 'Avg customer lifespan',
            'monthly_arpc': 'Monthly ARPC',
            
            # Export
            'export': 'Export',
            'export_excel': 'Export Excel',
            'export_csv': 'Export CSV',
            'export_pdf': 'Export PDF',
            
            # Profile - Activity Section
            'activity': 'Activity',
            'book_classes': 'Book Classes',
            'schedule_availability': 'Schedule and availability',
            'attendance_history': 'Attendance History',
            'classes_attended': 'Classes you have attended',
            'my_achievements': 'My Achievements',
            'unlocked': 'unlocked',
            'your_position': 'Your position',
            'your_training_plan': 'Your training plan',
            'account_balance': 'Your account balance',
            'invite_friends': 'Invite Friends',
            'share_earn_rewards': 'Share and earn rewards',
            'streak': 'Streak',
            'active_status': 'Active',
            
            # Profile - Shopping Section
            'buying': 'Shopping',
            'products_supplements': 'Products and supplements',
            'my_purchases': 'My Purchases',
            'order_history': 'Order history',
            
            # Profile - Payments Section
            'payments': 'Payments',
            'payment_history': 'Payment History',
            'invoices_receipts': 'Invoices and receipts',
            'payment_methods': 'Payment Methods',
            'saved_cards': 'Saved cards',
            
            # Profile - Support Section
            'support': 'Support',
            'help_faq': 'Help & FAQ',
            'frequently_asked_questions': 'Frequently asked questions',
            'contact': 'Contact',
            'terms_conditions': 'Terms & Conditions',
            'privacy_policy': 'Privacy policy',
            'chat_with': 'Chat with',
            
            # Edit Profile
            'edit_profile': 'Edit Profile',
            'change_photo': 'Change Photo',
            'profile_photo': 'Profile Photo',
            'click_to_upload': 'Click to upload or drag photo',
            'photo_format': 'Format: JPG, PNG (max 5MB)',
            'personal_info': 'Personal Information',
            'birth_date': 'Birth Date',
            'gender': 'Gender',
            'male': 'Male',
            'female': 'Female',
            'other': 'Other',
            'not_specified': 'Not specified',
            'contact_info': 'Contact Information',
            'current_password': 'Current Password',
            'new_password': 'New Password',
            'leave_blank_no_change': 'Leave blank if you don\'t want to change it',
            'saving': 'Saving...',
            
            # Dashboard / Client Area
            'manage_account_activities': 'Manage your account and activities',
            'start': 'Start',
            'end': 'End',
            'unlimited': 'Unlimited',
            'pause': 'Pause',
            'cancel_renewal': 'Cancel renewal',
            'no_active_memberships': 'You don\'t have active memberships',
            'get_plan_start_training': 'Get a plan to start training',
            'want_advance_payment': 'Do you want to pay in advance?',
            'pay_next_fee_early': 'Pay your next fee before the scheduled date and keep your membership always active.',
            'advance_payment': 'Advance Payment',
            'my_upcoming_classes': 'My Upcoming Classes',
            'no_classes_booked': 'You don\'t have any classes booked',
            'book_spot_schedule': 'Book your spot in the schedule',
            'view_schedule': 'View Schedule',
            'with': 'With',
            
            # Gamification Dashboard
            'my_progress': 'My Progress',
            'level': 'Level',
            'total_xp': 'Total XP',
            'xp_to_next_level': 'XP to level',
            'current_streak': 'Current streak',
            'complete_actions_unlock': 'Complete actions to unlock achievements!',
            'view_full_ranking': 'View Full Ranking →',
            
            # Schedule
            'class_schedule': 'Class Schedule',
            'check_classes_availability': 'Check our classes and real-time availability',
            'login_to_book': 'Login to book classes',
            'filter_by_activity': 'Filter by activity',
            'view_all': 'View All',
            'instructor': 'Instructor',
            'room': 'Room',
            'availability': 'Availability',
            'spots_occupied': 'spots occupied',
            'class_full': 'Class Full',
            'spots_available': 'spots available',
            'book_spot': 'Book Spot',
            'login_to_book_btn': 'Login to Book',
            'booking_in_progress': 'Booking...',
            'booking_error': 'Error making the reservation',
            'could_not_complete': 'Could not complete the booking',
            
            # Pricing
            'plans_pricing': 'Plans & Pricing',
            'find_perfect_plan': 'Find the perfect plan for you',
            'automatic_renewal': 'Automatic renewal every',
            'valid_for': 'Valid for',
            'days': 'days',
            'pauses_allowed': 'Pauses allowed',
            'unlimited_access': 'Unlimited access',
            'sessions_count': 'sessions',
            'not_available': 'Not Available',
            'buy_plan': 'Buy Plan',
            'contract_required': 'Contract signature required',
            'no_plans_available': 'No plans available',
            'contact_gym_info': 'Contact the gym for more information',
            'call_to': 'Call',
            'have_questions': 'Have questions?',
            'payment_methods': 'Payment Methods',
            'payment_secure': 'We accept credit/debit cards. Secure payment with SSL encryption.',
            'cancellations_title': 'Cancellations',
            'cancellations_desc': 'You can cancel your membership at any time from your profile.',
            'location': 'Location',
            'contact': 'Contact',
        }
    }
    
    # Obtener el idioma actual de la sesión o del gimnasio
    current_language = 'es'  # Default
    
    # Primero intentar obtener del gimnasio
    if hasattr(request, 'gym') and request.gym:
        current_language = getattr(request.gym, 'language', 'es')
    # Si no, intentar de la sesión
    elif hasattr(request, 'session') and 'django_language' in request.session:
        current_language = request.session.get('django_language', 'es')
    # Si no, usar el LANGUAGE_CODE del request
    elif hasattr(request, 'LANGUAGE_CODE'):
        current_language = request.LANGUAGE_CODE
    
    # Asegurar que solo usamos 'es' o 'en'
    if current_language not in translations_dict:
        current_language = 'es'
    
    return {
        't': translations_dict.get(current_language, translations_dict['es'])
    }
