# Generated by Django 4.2.27 on 2026-01-25 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0016_gym_slug'),
        ('clients', '0101_remove_chatmessage_chat_unread_idx_and_more'),
        ('activities', '0102_alter_attendancesettings_checkin_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Activar reconocimiento facial para check-in')),
                ('confidence_threshold', models.FloatField(default=0.6, help_text='Umbral de confianza (0-1). Mayor = más estricto')),
                ('allow_qr_checkin', models.BooleanField(default=True, help_text='Permitir check-in con QR')),
                ('allow_face_checkin', models.BooleanField(default=False, help_text='Permitir check-in con reconocimiento facial')),
                ('allow_manual_checkin', models.BooleanField(default=True, help_text='Permitir check-in manual por staff')),
                ('kiosk_mode_enabled', models.BooleanField(default=False, help_text='Habilitar modo kiosko (pantalla completa para tablet)')),
                ('kiosk_welcome_message', models.CharField(blank=True, default='Bienvenido, mira a la cámara', max_length=200)),
                ('auto_open_turnstile', models.BooleanField(default=False, help_text='Abrir torno automáticamente al reconocer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_recognition_settings', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Configuración de Reconocimiento Facial',
                'verbose_name_plural': 'Configuraciones de Reconocimiento Facial',
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('success', 'Éxito'), ('no_face', 'No se detectó rostro'), ('no_match', 'Sin coincidencia'), ('multiple_faces', 'Múltiples rostros'), ('error', 'Error')], max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(help_text='Tiempo de procesamiento en milisegundos', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activitysession')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_recognition_logs', to='clients.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_recognition_logs', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Log de Reconocimiento',
                'verbose_name_plural': 'Logs de Reconocimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientFaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.BinaryField(help_text='Encoding facial del cliente (128 dimensiones)')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('quality_score', models.FloatField(default=0.0, help_text='Puntuación de calidad del encoding (0-1)')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to='clients.client')),
            ],
            options={
                'verbose_name': 'Encoding Facial',
                'verbose_name_plural': 'Encodings Faciales',
            },
        ),
    ]
