# Generated by Django 5.2.10 on 2026-02-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognitionsettings',
            name='kiosk_allowed_ips',
            field=models.TextField(blank=True, default='', help_text='IPs permitidas para el kiosko (una por línea). Vacío = permitir todas'),
        ),
        migrations.AddField(
            model_name='facerecognitionsettings',
            name='kiosk_token',
            field=models.CharField(blank=True, default='', help_text='Token secreto para autenticar kioskos (dejar vacío para generar)', max_length=64),
        ),
    ]
