# Generated by Django 4.2.27 on 2026-01-22 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0019_add_client_payment_method'),
        ('organizations', '0014_add_email_signature_logo'),
        ('memberships', '0006_add_attendance_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del dispositivo (ej: Torno Principal)', max_length=100)),
                ('device_type', models.CharField(choices=[('TURNSTILE', 'Torno'), ('DOOR', 'Puerta Automática'), ('BARRIER', 'Barrera'), ('RFID_READER', 'Lector RFID/NFC'), ('QR_SCANNER', 'Escáner QR'), ('BIOMETRIC', 'Biométrico'), ('COMBINED', 'Combinado')], default='TURNSTILE', max_length=20)),
                ('direction', models.CharField(choices=[('ENTRY', 'Solo Entrada'), ('EXIT', 'Solo Salida'), ('BIDIRECTIONAL', 'Bidireccional')], default='BIDIRECTIONAL', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Ubicación física (ej: Entrada principal)', max_length=100)),
                ('device_id', models.CharField(help_text='ID único del dispositivo (proporcionado por el fabricante)', max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP del dispositivo en la red local', null=True)),
                ('api_endpoint', models.URLField(blank=True, help_text='URL de la API del dispositivo (si aplica)')),
                ('api_key', models.CharField(blank=True, help_text='API Key para autenticación', max_length=255)),
                ('provider', models.CharField(choices=[('GENERIC', 'Genérico/API REST'), ('GANTNER', 'Gantner'), ('SALTO', 'Salto'), ('ZKTECO', 'ZKTeco'), ('HIKVISION', 'Hikvision'), ('SUPREMA', 'Suprema'), ('DORMAKABA', 'Dormakaba'), ('CUSTOM', 'Personalizado')], default='GENERIC', max_length=20)),
                ('provider_config', models.JSONField(blank=True, default=dict, help_text='Configuración específica del proveedor en formato JSON')),
                ('status', models.CharField(choices=[('ONLINE', 'En línea'), ('OFFLINE', 'Desconectado'), ('MAINTENANCE', 'En mantenimiento'), ('ERROR', 'Error')], default='OFFLINE', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Última comunicación con el dispositivo', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Último mensaje de error')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_offline_mode', models.BooleanField(default=False, help_text='Permitir acceso cuando el dispositivo está offline (usa caché local)')),
                ('timeout_seconds', models.IntegerField(default=5, help_text='Timeout de conexión en segundos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_devices', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Dispositivo de Acceso',
                'verbose_name_plural': 'Dispositivos de Acceso',
                'ordering': ['gym', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la zona (ej: Sala Musculación)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366F1', help_text='Color para identificación visual', max_length=7)),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Aforo máximo permitido (dejar vacío si no aplica)', null=True)),
                ('requires_specific_membership', models.BooleanField(default=False, help_text='¿Requiere membresía específica para acceder?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_membership_plans', models.ManyToManyField(blank=True, help_text='Planes de membresía que permiten acceso a esta zona', related_name='allowed_zones', to='memberships.membershipplan')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_zones', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Zona de Acceso',
                'verbose_name_plural': 'Zonas de Acceso',
                'ordering': ['gym', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del horario (ej: Horario Mañanas)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('days_of_week', models.JSONField(default=list, help_text='Lista de días permitidos [0=Lunes, 6=Domingo]')),
                ('start_time', models.TimeField(help_text='Hora de inicio del acceso permitido')),
                ('end_time', models.TimeField(help_text='Hora de fin del acceso permitido')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_schedules', to='organizations.gym')),
                ('membership_plans', models.ManyToManyField(blank=True, help_text='Planes de membresía que tienen este horario', related_name='access_schedules', to='memberships.membershipplan')),
            ],
            options={
                'verbose_name': 'Horario de Acceso',
                'verbose_name_plural': 'Horarios de Acceso',
                'ordering': ['gym', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida')], max_length=10)),
                ('status', models.CharField(choices=[('GRANTED', 'Acceso Concedido'), ('DENIED', 'Acceso Denegado'), ('ERROR', 'Error de Sistema'), ('MANUAL', 'Acceso Manual'), ('EMERGENCY', 'Apertura de Emergencia')], max_length=20)),
                ('denial_reason', models.CharField(blank=True, choices=[('NO_MEMBERSHIP', 'Sin membresía activa'), ('MEMBERSHIP_EXPIRED', 'Membresía expirada'), ('PAYMENT_OVERDUE', 'Pago pendiente'), ('INVALID_CREDENTIAL', 'Credencial inválida'), ('CREDENTIAL_EXPIRED', 'Credencial expirada'), ('ZONE_NOT_ALLOWED', 'Zona no permitida'), ('CAPACITY_EXCEEDED', 'Aforo completo'), ('SCHEDULE_RESTRICTED', 'Fuera de horario permitido'), ('ACCOUNT_BLOCKED', 'Cuenta bloqueada'), ('UNKNOWN_PERSON', 'Persona no identificada'), ('DEVICE_ERROR', 'Error del dispositivo'), ('OTHER', 'Otro')], help_text='Razón del rechazo (si aplica)', max_length=30)),
                ('credential_type', models.CharField(blank=True, max_length=20)),
                ('credential_value_masked', models.CharField(blank=True, help_text='Valor enmascarado de la credencial (últimos 4 dígitos, etc.)', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Datos crudos recibidos del dispositivo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='clients.client')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='access_control.accessdevice')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='organizations.gym')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Usuario que procesó manualmente (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='accessdevice',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zona a la que da acceso este dispositivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='access_control.accesszone'),
        ),
        migrations.CreateModel(
            name='AccessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('DENIED_ACCESS', 'Acceso Denegado'), ('CAPACITY_WARNING', 'Aviso de Aforo'), ('CAPACITY_EXCEEDED', 'Aforo Excedido'), ('DEVICE_OFFLINE', 'Dispositivo Desconectado'), ('DEVICE_ERROR', 'Error de Dispositivo'), ('SUSPICIOUS_ACTIVITY', 'Actividad Sospechosa'), ('EMERGENCY', 'Emergencia')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.accesslog')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.accessdevice')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_alerts', to='organizations.gym')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Acceso',
                'verbose_name_plural': 'Alertas de Acceso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientAccessCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('QR_DYNAMIC', 'QR Dinámico (App)'), ('QR_STATIC', 'QR Estático'), ('RFID', 'Tarjeta RFID/NFC'), ('BARCODE', 'Código de Barras'), ('PIN', 'Código PIN'), ('FINGERPRINT', 'Huella Dactilar'), ('FACE', 'Reconocimiento Facial'), ('BLUETOOTH', 'Bluetooth/BLE')], max_length=20)),
                ('credential_value', models.CharField(help_text='Valor de la credencial (número de tarjeta, PIN, template biométrico, etc.)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Credencial principal del cliente')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Dejar vacío para sin caducidad', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notas internas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_credentials', to='clients.client')),
            ],
            options={
                'verbose_name': 'Credencial de Acceso',
                'verbose_name_plural': 'Credenciales de Acceso',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('client', 'credential_type', 'credential_value')},
            },
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['gym', 'timestamp'], name='access_cont_gym_id_e46970_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['client', 'timestamp'], name='access_cont_client__9ddb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['device', 'timestamp'], name='access_cont_device__34f9e1_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['status', 'timestamp'], name='access_cont_status_bcf2eb_idx'),
        ),
    ]
