# Generated by Django 4.2.27 on 2026-01-22 19:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0014_add_email_signature_logo'),
        ('clients', '0019_add_client_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('row', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fila')),
                ('column', models.PositiveIntegerField(blank=True, null=True, verbose_name='Columna')),
                ('size', models.CharField(choices=[('S', 'Pequeña'), ('M', 'Mediana'), ('L', 'Grande'), ('XL', 'Extra Grande')], default='M', max_length=2, verbose_name='Tamaño')),
                ('has_key', models.BooleanField(default=True, verbose_name='Tiene llave')),
                ('key_number', models.CharField(blank=True, max_length=50, verbose_name='Número de llave')),
                ('has_lock', models.BooleanField(default=False, verbose_name='Tiene candado')),
                ('lock_combination', models.CharField(blank=True, max_length=50, verbose_name='Combinación')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = gratuita', max_digits=8, verbose_name='Precio mensual')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('ASSIGNED', 'Asignada'), ('MAINTENANCE', 'En mantenimiento'), ('RESERVED', 'Reservada')], default='AVAILABLE', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taquilla',
                'verbose_name_plural': 'Taquillas',
                'ordering': ['zone', 'number'],
            },
        ),
        migrations.CreateModel(
            name='LockerZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la zona')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#6366F1', help_text='Código HEX', max_length=7, verbose_name='Color')),
                ('rows', models.PositiveIntegerField(default=4, help_text='Número de filas de taquillas', verbose_name='Filas')),
                ('columns', models.PositiveIntegerField(default=10, help_text='Número de columnas de taquillas', verbose_name='Columnas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locker_zones', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Zona de Taquillas',
                'verbose_name_plural': 'Zonas de Taquillas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LockerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(blank=True, help_text='Dejar vacío para indefinido', null=True, verbose_name='Fecha fin')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Precio mensual')),
                ('is_included_in_membership', models.BooleanField(default=False, help_text='Si está marcado, no se cobra aparte', verbose_name='Incluida en membresía')),
                ('key_delivered', models.BooleanField(default=False, verbose_name='Llave entregada')),
                ('key_delivered_date', models.DateField(blank=True, null=True, verbose_name='Fecha entrega llave')),
                ('key_returned', models.BooleanField(default=False, verbose_name='Llave devuelta')),
                ('key_returned_date', models.DateField(blank=True, null=True, verbose_name='Fecha devolución llave')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Depósito')),
                ('deposit_paid', models.BooleanField(default=False, verbose_name='Depósito pagado')),
                ('deposit_returned', models.BooleanField(default=False, verbose_name='Depósito devuelto')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('EXPIRED', 'Expirada'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locker_assignments', to='clients.client')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lockers.locker')),
            ],
            options={
                'verbose_name': 'Asignación de Taquilla',
                'verbose_name_plural': 'Asignaciones de Taquillas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='locker',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockers', to='lockers.lockerzone'),
        ),
        migrations.AlterUniqueTogether(
            name='locker',
            unique_together={('zone', 'number')},
        ),
    ]
