# Generated by Django 4.2.27 on 2026-01-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0010_publicportalsettings'),
        ('clients', '0018_add_app_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único (ej: FIRST_CLASS, WEEK_WARRIOR)', max_length=50)),
                ('name', models.CharField(help_text='Nombre del logro', max_length=100)),
                ('description', models.TextField(help_text='Descripción de cómo conseguirlo')),
                ('icon', models.CharField(default='🏅', help_text='Emoji del logro', max_length=10)),
                ('category', models.CharField(choices=[('ATTENDANCE', 'Asistencia'), ('STREAK', 'Rachas'), ('SOCIAL', 'Social'), ('VARIETY', 'Variedad'), ('REVIEWS', 'Reviews'), ('SPECIAL', 'Especial')], default='ATTENDANCE', max_length=20)),
                ('xp_reward', models.IntegerField(default=50, help_text='XP que otorga al desbloquearlo')),
                ('requirement_type', models.CharField(help_text='Tipo de requisito (ej: total_visits, current_streak)', max_length=50)),
                ('requirement_value', models.IntegerField(help_text='Valor necesario para desbloquear')),
                ('is_active', models.BooleanField(default=True)),
                ('is_secret', models.BooleanField(default=False, help_text='Logro secreto (no visible hasta desbloquearlo)')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['order', 'name'],
                'unique_together': {('gym', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='challenges/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_type', models.CharField(choices=[('ATTENDANCE_COUNT', 'Número de asistencias'), ('STREAK_DAYS', 'Días de racha'), ('SPECIFIC_ACTIVITY', 'Actividad específica'), ('TOTAL_XP', 'Puntos de experiencia')], max_length=30)),
                ('target_value', models.IntegerField(help_text='Valor objetivo del desafío')),
                ('reward_xp', models.IntegerField(default=0, help_text='XP al completar')),
                ('reward_discount', models.DecimalField(decimal_places=2, default=0, help_text='Descuento en euros', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Desafío',
                'verbose_name_plural': 'Desafíos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Cantidad de XP ganado (positivo) o perdido (negativo)')),
                ('reason', models.CharField(help_text='Razón de la transacción', max_length=255)),
                ('balance_after', models.IntegerField(help_text='Balance total después de la transacción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='clients.client')),
            ],
            options={
                'verbose_name': 'Transacción de XP',
                'verbose_name_plural': 'Transacciones de XP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Activar sistema de gamificación')),
                ('xp_per_attendance', models.IntegerField(default=10, help_text='XP por asistir a una clase')),
                ('xp_per_routine_completion', models.IntegerField(default=15, help_text='XP por completar rutina del día')),
                ('xp_per_review', models.IntegerField(default=10, help_text='XP por dejar review')),
                ('xp_per_referral', models.IntegerField(default=100, help_text='XP por traer un amigo')),
                ('xp_per_level', models.IntegerField(default=100, help_text='XP necesario por nivel (escala lineal)')),
                ('max_level', models.IntegerField(default=50, help_text='Nivel máximo alcanzable')),
                ('show_leaderboard', models.BooleanField(default=True, help_text='Mostrar tabla de clasificación')),
                ('show_on_portal', models.BooleanField(default=True, help_text='Mostrar en portal del cliente')),
                ('show_on_app', models.BooleanField(default=True, help_text='Mostrar en app móvil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_settings', to='organizations.gym')),
            ],
            options={
                'verbose_name': 'Configuración de Gamificación',
                'verbose_name_plural': 'Configuraciones de Gamificación',
            },
        ),
        migrations.CreateModel(
            name='ClientProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0, help_text='Puntos de experiencia totales')),
                ('current_level', models.IntegerField(default=1, help_text='Nivel actual')),
                ('total_visits', models.IntegerField(default=0, help_text='Total de asistencias')),
                ('total_reviews', models.IntegerField(default=0, help_text='Total de reviews dejadas')),
                ('total_referrals', models.IntegerField(default=0, help_text='Total de amigos referidos')),
                ('total_routines_completed', models.IntegerField(default=0, help_text='Rutinas completadas')),
                ('current_streak', models.IntegerField(default=0, help_text='Días consecutivos con asistencia')),
                ('longest_streak', models.IntegerField(default=0, help_text='Récord personal de racha')),
                ('last_visit_date', models.DateField(blank=True, help_text='Última fecha de asistencia', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='clients.client')),
            ],
            options={
                'verbose_name': 'Progreso del Cliente',
                'verbose_name_plural': 'Progresos de Clientes',
                'ordering': ['-total_xp'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.challenge')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'Participación en Desafío',
                'verbose_name_plural': 'Participaciones en Desafíos',
                'unique_together': {('challenge', 'client')},
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='participants',
            field=models.ManyToManyField(related_name='challenges', through='gamification.ChallengeParticipation', to='clients.client'),
        ),
        migrations.CreateModel(
            name='ClientAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='clients.client')),
            ],
            options={
                'verbose_name': 'Logro Desbloqueado',
                'verbose_name_plural': 'Logros Desbloqueados',
                'ordering': ['-unlocked_at'],
                'unique_together': {('client', 'achievement')},
            },
        ),
    ]
