# Generated by Django 4.2.27 on 2026-02-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationsettings',
            name='hide_leaderboard_names',
            field=models.BooleanField(default=False, help_text='Ocultar nombres de otros clientes en el ranking (solo mostrar iniciales)'),
        ),
    ]
