# Generated by Django 5.1.15 on 2026-01-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Transacción (Stripe)'),
        ),
    ]
