# Generated by Django 4.2.27 on 2026-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_orderpayment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='gateway_used',
            field=models.CharField(choices=[('NONE', 'Sin pasarela (Manual/Efectivo)'), ('STRIPE', 'Stripe'), ('REDSYS', 'Redsys')], default='NONE', max_length=20, verbose_name='Pasarela Usada'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Transacción'),
        ),
    ]
