# Generated by Django 4.2.27 on 2026-01-24 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0103_orderrefund_negative_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_gym_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_client_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_cashsession_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_invoice_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='auto_charge',
            field=models.BooleanField(default=False, help_text='Si está activo, se intentará cobrar automáticamente en la fecha programada', verbose_name='Cobro Automático'),
        ),
        migrations.AddField(
            model_name='order',
            name='deferred_notes',
            field=models.TextField(blank=True, help_text='Razón o comentarios sobre por qué se difirió el pago', verbose_name='Notas del Diferido'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_payment_date',
            field=models.DateField(blank=True, help_text='Fecha en que se debe cobrar esta venta diferida', null=True, verbose_name='Fecha Pago Programado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado'), ('DEFERRED', 'Diferido')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Pago específico que se devuelve (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='sales.orderpayment'),
        ),
    ]
