# Generated by Django 5.2.10 on 2026-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0104_deferred_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas que aparecen en el ticket/factura para este artículo', verbose_name='Notas del Recibo'),
        ),
    ]
