# Generated by Django 5.1.15 on 2026-01-11 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('organizations', '0002_gym_brand_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='product_icons/')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='organizations.gym')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU / Código de Barras')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Compra (Sin IVA)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('price_strategy', models.CharField(choices=[('TAX_INCLUDED', 'Impuestos Incluidos'), ('TAX_EXCLUDED', 'Impuestos Excluidos')], default='TAX_INCLUDED', max_length=20, verbose_name='Estrategia de Precio')),
                ('supplier_name', models.CharField(blank=True, max_length=100, verbose_name='Proveedor')),
                ('supplier_reference', models.CharField(blank=True, max_length=100, verbose_name='Ref. Proveedor')),
                ('track_stock', models.BooleanField(default=True, verbose_name='Controlar Stock')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock Actual')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='Alerta Stock Bajo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo (POS)')),
                ('is_visible_online', models.BooleanField(default=False, verbose_name='Venta Online')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organizations.gym')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.taxrate')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(verbose_name='Cambio (+/-)')),
                ('reason', models.CharField(choices=[('SALE', 'Venta'), ('RESTOCK', 'Reabastecimiento'), ('ADJUSTMENT', 'Ajuste Manual'), ('LOSS', 'Pérdida/Daño'), ('RETURN', 'Devolución')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_moves', to='products.product')),
            ],
        ),
    ]
