# Generated by Django 5.2.10 on 2026-02-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_wallet_system'),
        ('organizations', '0020_add_checkin_methods_and_geolocation'),
        ('products', '0002_product_preferred_provider'),
        ('providers', '0004_add_provider_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Categoría de Producto', 'verbose_name_plural': 'Categorías de Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='EAN-13/EAN-8 del fabricante o código escaneado', max_length=50, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_type',
            field=models.CharField(choices=[('EAN13', 'EAN-13 (Estándar)'), ('EAN8', 'EAN-8 (Compacto)'), ('UPCA', 'UPC-A (USA)'), ('CODE128', 'Code 128 (Interno)'), ('INTERNAL', 'SKU Interno'), ('NONE', 'Sin código')], default='NONE', max_length=10, verbose_name='Tipo de Código'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.CharField(blank=True, help_text='Código corto para SKUs automáticos (ej: BEB, SUP, ROA)', max_length=5, verbose_name='Código Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Código interno del gimnasio (auto-generado si se deja vacío)', max_length=30, verbose_name='SKU Interno'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gym', 'barcode'], name='products_pr_gym_id_c926c6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gym', 'sku'], name='products_pr_gym_id_3835ac_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gym', 'is_active'], name='products_pr_gym_id_5b00ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__gt', '')), fields=('gym', 'barcode'), name='unique_barcode_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__gt', '')), fields=('gym', 'sku'), name='unique_sku_per_gym'),
        ),
    ]
