# Generated by Django 5.2.10 on 2026-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_barcode_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='receipt_notes',
            field=models.TextField(blank=True, help_text='Texto que aparecerá en el ticket/factura cuando se venda este producto', verbose_name='Notas del Recibo'),
        ),
    ]
